// Code generated by github.com/portfoliotree/alphavantage/cmd/generate; DO NOT EDIT.

package alphavantage

import (
	"context"
	"net/http"
	"net/url"
)

type ConsumerPriceIndexQuery url.Values

func QueryConsumerPriceIndex(apiKey string) ConsumerPriceIndexQuery {
	return ConsumerPriceIndexQuery{"function": []string{"CPI"}, "apikey": []string{apiKey}}
}
func (query ConsumerPriceIndexQuery) Interval(value string) ConsumerPriceIndexQuery {
	query["interval"] = []string{value}
	return query
}
func (query ConsumerPriceIndexQuery) DataTypeCSV() ConsumerPriceIndexQuery {
	query["datatype"] = []string{"csv"}
	return query
}
func (query ConsumerPriceIndexQuery) DataTypeJSON() ConsumerPriceIndexQuery {
	query["datatype"] = []string{"json"}
	return query
}
func (query ConsumerPriceIndexQuery) DataType(value string) ConsumerPriceIndexQuery {
	query["datatype"] = []string{value}
	return query
}
func (client *Client) GetConsumerPriceIndex(ctx context.Context, q ConsumerPriceIndexQuery) (*http.Response, error) {
	req, err := client.newRequest(ctx, url.Values(q))
	if err != nil {
		return nil, err
	}
	res, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	return res, nil
}

type ConsumerPriceIndexRow struct {
	TimeStamp string `column-name:"timestamp"`
	Value     string `column-name:"value"`
}

func (client *Client) GetConsumerPriceIndexCSVRows(ctx context.Context, q ConsumerPriceIndexQuery) ([]ConsumerPriceIndexRow, error) {
	q.DataTypeCSV()
	res, err := client.GetConsumerPriceIndex(ctx, q)
	if err != nil {
		return nil, err
	}
	defer res.Body.Close()
	var rows []ConsumerPriceIndexRow
	err = ParseCSV(res.Body, &rows, nil)
	if err != nil {
		return nil, err
	}
	return rows, nil
}

type DurablesQuery url.Values

func QueryDurables(apiKey string) DurablesQuery {
	return DurablesQuery{"function": []string{"DURABLES"}, "apikey": []string{apiKey}}
}
func (query DurablesQuery) DataTypeCSV() DurablesQuery {
	query["datatype"] = []string{"csv"}
	return query
}
func (query DurablesQuery) DataTypeJSON() DurablesQuery {
	query["datatype"] = []string{"json"}
	return query
}
func (query DurablesQuery) DataType(value string) DurablesQuery {
	query["datatype"] = []string{value}
	return query
}
func (client *Client) GetDurables(ctx context.Context, q DurablesQuery) (*http.Response, error) {
	req, err := client.newRequest(ctx, url.Values(q))
	if err != nil {
		return nil, err
	}
	res, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	return res, nil
}

type DurablesRow struct {
	TimeStamp string `column-name:"timestamp"`
	Value     string `column-name:"value"`
}

func (client *Client) GetDurablesCSVRows(ctx context.Context, q DurablesQuery) ([]DurablesRow, error) {
	q.DataTypeCSV()
	res, err := client.GetDurables(ctx, q)
	if err != nil {
		return nil, err
	}
	defer res.Body.Close()
	var rows []DurablesRow
	err = ParseCSV(res.Body, &rows, nil)
	if err != nil {
		return nil, err
	}
	return rows, nil
}

type FederalFundsRateQuery url.Values

func QueryFederalFundsRate(apiKey string) FederalFundsRateQuery {
	return FederalFundsRateQuery{"function": []string{"FEDERAL_FUNDS_RATE"}, "apikey": []string{apiKey}}
}
func (query FederalFundsRateQuery) Interval(value string) FederalFundsRateQuery {
	query["interval"] = []string{value}
	return query
}
func (query FederalFundsRateQuery) DataTypeCSV() FederalFundsRateQuery {
	query["datatype"] = []string{"csv"}
	return query
}
func (query FederalFundsRateQuery) DataTypeJSON() FederalFundsRateQuery {
	query["datatype"] = []string{"json"}
	return query
}
func (query FederalFundsRateQuery) DataType(value string) FederalFundsRateQuery {
	query["datatype"] = []string{value}
	return query
}
func (client *Client) GetFederalFundsRate(ctx context.Context, q FederalFundsRateQuery) (*http.Response, error) {
	req, err := client.newRequest(ctx, url.Values(q))
	if err != nil {
		return nil, err
	}
	res, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	return res, nil
}

type FederalFundsRateRow struct {
	TimeStamp string `column-name:"timestamp"`
	Value     string `column-name:"value"`
}

func (client *Client) GetFederalFundsRateCSVRows(ctx context.Context, q FederalFundsRateQuery) ([]FederalFundsRateRow, error) {
	q.DataTypeCSV()
	res, err := client.GetFederalFundsRate(ctx, q)
	if err != nil {
		return nil, err
	}
	defer res.Body.Close()
	var rows []FederalFundsRateRow
	err = ParseCSV(res.Body, &rows, nil)
	if err != nil {
		return nil, err
	}
	return rows, nil
}

type InflationQuery url.Values

func QueryInflation(apiKey string) InflationQuery {
	return InflationQuery{"function": []string{"INFLATION"}, "apikey": []string{apiKey}}
}
func (query InflationQuery) DataTypeCSV() InflationQuery {
	query["datatype"] = []string{"csv"}
	return query
}
func (query InflationQuery) DataTypeJSON() InflationQuery {
	query["datatype"] = []string{"json"}
	return query
}
func (query InflationQuery) DataType(value string) InflationQuery {
	query["datatype"] = []string{value}
	return query
}
func (client *Client) GetInflation(ctx context.Context, q InflationQuery) (*http.Response, error) {
	req, err := client.newRequest(ctx, url.Values(q))
	if err != nil {
		return nil, err
	}
	res, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	return res, nil
}

type InflationRow struct {
	TimeStamp string `column-name:"timestamp"`
	Value     string `column-name:"value"`
}

func (client *Client) GetInflationCSVRows(ctx context.Context, q InflationQuery) ([]InflationRow, error) {
	q.DataTypeCSV()
	res, err := client.GetInflation(ctx, q)
	if err != nil {
		return nil, err
	}
	defer res.Body.Close()
	var rows []InflationRow
	err = ParseCSV(res.Body, &rows, nil)
	if err != nil {
		return nil, err
	}
	return rows, nil
}

type NonFarmPayrollQuery url.Values

func QueryNonFarmPayroll(apiKey string) NonFarmPayrollQuery {
	return NonFarmPayrollQuery{"function": []string{"NONFARM_PAYROLL"}, "apikey": []string{apiKey}}
}
func (query NonFarmPayrollQuery) DataTypeCSV() NonFarmPayrollQuery {
	query["datatype"] = []string{"csv"}
	return query
}
func (query NonFarmPayrollQuery) DataTypeJSON() NonFarmPayrollQuery {
	query["datatype"] = []string{"json"}
	return query
}
func (query NonFarmPayrollQuery) DataType(value string) NonFarmPayrollQuery {
	query["datatype"] = []string{value}
	return query
}
func (client *Client) GetNonFarmPayroll(ctx context.Context, q NonFarmPayrollQuery) (*http.Response, error) {
	req, err := client.newRequest(ctx, url.Values(q))
	if err != nil {
		return nil, err
	}
	res, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	return res, nil
}

type NonFarmPayrollRow struct {
	TimeStamp string `column-name:"timestamp"`
	Value     string `column-name:"value"`
}

func (client *Client) GetNonFarmPayrollCSVRows(ctx context.Context, q NonFarmPayrollQuery) ([]NonFarmPayrollRow, error) {
	q.DataTypeCSV()
	res, err := client.GetNonFarmPayroll(ctx, q)
	if err != nil {
		return nil, err
	}
	defer res.Body.Close()
	var rows []NonFarmPayrollRow
	err = ParseCSV(res.Body, &rows, nil)
	if err != nil {
		return nil, err
	}
	return rows, nil
}

type RealGDPQuery url.Values

func QueryRealGDP(apiKey string) RealGDPQuery {
	return RealGDPQuery{"function": []string{"REAL_GDP"}, "apikey": []string{apiKey}}
}
func (query RealGDPQuery) Interval(value string) RealGDPQuery {
	query["interval"] = []string{value}
	return query
}
func (query RealGDPQuery) DataTypeCSV() RealGDPQuery {
	query["datatype"] = []string{"csv"}
	return query
}
func (query RealGDPQuery) DataTypeJSON() RealGDPQuery {
	query["datatype"] = []string{"json"}
	return query
}
func (query RealGDPQuery) DataType(value string) RealGDPQuery {
	query["datatype"] = []string{value}
	return query
}
func (client *Client) GetRealGDP(ctx context.Context, q RealGDPQuery) (*http.Response, error) {
	req, err := client.newRequest(ctx, url.Values(q))
	if err != nil {
		return nil, err
	}
	res, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	return res, nil
}

type RealGDPRow struct {
	TimeStamp string `column-name:"timestamp"`
	Value     string `column-name:"value"`
}

func (client *Client) GetRealGDPCSVRows(ctx context.Context, q RealGDPQuery) ([]RealGDPRow, error) {
	q.DataTypeCSV()
	res, err := client.GetRealGDP(ctx, q)
	if err != nil {
		return nil, err
	}
	defer res.Body.Close()
	var rows []RealGDPRow
	err = ParseCSV(res.Body, &rows, nil)
	if err != nil {
		return nil, err
	}
	return rows, nil
}

type RealGDPPerCapitaQuery url.Values

func QueryRealGDPPerCapita(apiKey string) RealGDPPerCapitaQuery {
	return RealGDPPerCapitaQuery{"function": []string{"REAL_GDP_PER_CAPITA"}, "apikey": []string{apiKey}}
}
func (query RealGDPPerCapitaQuery) DataTypeCSV() RealGDPPerCapitaQuery {
	query["datatype"] = []string{"csv"}
	return query
}
func (query RealGDPPerCapitaQuery) DataTypeJSON() RealGDPPerCapitaQuery {
	query["datatype"] = []string{"json"}
	return query
}
func (query RealGDPPerCapitaQuery) DataType(value string) RealGDPPerCapitaQuery {
	query["datatype"] = []string{value}
	return query
}
func (client *Client) GetRealGDPPerCapita(ctx context.Context, q RealGDPPerCapitaQuery) (*http.Response, error) {
	req, err := client.newRequest(ctx, url.Values(q))
	if err != nil {
		return nil, err
	}
	res, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	return res, nil
}

type RealGDPPerCapitaRow struct {
	TimeStamp string `column-name:"timestamp"`
	Value     string `column-name:"value"`
}

func (client *Client) GetRealGDPPerCapitaCSVRows(ctx context.Context, q RealGDPPerCapitaQuery) ([]RealGDPPerCapitaRow, error) {
	q.DataTypeCSV()
	res, err := client.GetRealGDPPerCapita(ctx, q)
	if err != nil {
		return nil, err
	}
	defer res.Body.Close()
	var rows []RealGDPPerCapitaRow
	err = ParseCSV(res.Body, &rows, nil)
	if err != nil {
		return nil, err
	}
	return rows, nil
}

type RetailSalesQuery url.Values

func QueryRetailSales(apiKey string) RetailSalesQuery {
	return RetailSalesQuery{"function": []string{"RETAIL_SALES"}, "apikey": []string{apiKey}}
}
func (query RetailSalesQuery) DataTypeCSV() RetailSalesQuery {
	query["datatype"] = []string{"csv"}
	return query
}
func (query RetailSalesQuery) DataTypeJSON() RetailSalesQuery {
	query["datatype"] = []string{"json"}
	return query
}
func (query RetailSalesQuery) DataType(value string) RetailSalesQuery {
	query["datatype"] = []string{value}
	return query
}
func (client *Client) GetRetailSales(ctx context.Context, q RetailSalesQuery) (*http.Response, error) {
	req, err := client.newRequest(ctx, url.Values(q))
	if err != nil {
		return nil, err
	}
	res, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	return res, nil
}

type RetailSalesRow struct {
	TimeStamp string `column-name:"timestamp"`
	Value     string `column-name:"value"`
}

func (client *Client) GetRetailSalesCSVRows(ctx context.Context, q RetailSalesQuery) ([]RetailSalesRow, error) {
	q.DataTypeCSV()
	res, err := client.GetRetailSales(ctx, q)
	if err != nil {
		return nil, err
	}
	defer res.Body.Close()
	var rows []RetailSalesRow
	err = ParseCSV(res.Body, &rows, nil)
	if err != nil {
		return nil, err
	}
	return rows, nil
}

type TreasuryYieldQuery url.Values

func QueryTreasuryYield(apiKey string) TreasuryYieldQuery {
	return TreasuryYieldQuery{"function": []string{"TREASURY_YIELD"}, "apikey": []string{apiKey}}
}
func (query TreasuryYieldQuery) Interval(value string) TreasuryYieldQuery {
	query["interval"] = []string{value}
	return query
}
func (query TreasuryYieldQuery) Maturity(value string) TreasuryYieldQuery {
	query["maturity"] = []string{value}
	return query
}
func (query TreasuryYieldQuery) DataTypeCSV() TreasuryYieldQuery {
	query["datatype"] = []string{"csv"}
	return query
}
func (query TreasuryYieldQuery) DataTypeJSON() TreasuryYieldQuery {
	query["datatype"] = []string{"json"}
	return query
}
func (query TreasuryYieldQuery) DataType(value string) TreasuryYieldQuery {
	query["datatype"] = []string{value}
	return query
}
func (client *Client) GetTreasuryYield(ctx context.Context, q TreasuryYieldQuery) (*http.Response, error) {
	req, err := client.newRequest(ctx, url.Values(q))
	if err != nil {
		return nil, err
	}
	res, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	return res, nil
}

type TreasuryYieldRow struct {
	TimeStamp string `column-name:"timestamp"`
	Value     string `column-name:"value"`
}

func (client *Client) GetTreasuryYieldCSVRows(ctx context.Context, q TreasuryYieldQuery) ([]TreasuryYieldRow, error) {
	q.DataTypeCSV()
	res, err := client.GetTreasuryYield(ctx, q)
	if err != nil {
		return nil, err
	}
	defer res.Body.Close()
	var rows []TreasuryYieldRow
	err = ParseCSV(res.Body, &rows, nil)
	if err != nil {
		return nil, err
	}
	return rows, nil
}

type UnemploymentQuery url.Values

func QueryUnemployment(apiKey string) UnemploymentQuery {
	return UnemploymentQuery{"function": []string{"UNEMPLOYMENT"}, "apikey": []string{apiKey}}
}
func (query UnemploymentQuery) DataTypeCSV() UnemploymentQuery {
	query["datatype"] = []string{"csv"}
	return query
}
func (query UnemploymentQuery) DataTypeJSON() UnemploymentQuery {
	query["datatype"] = []string{"json"}
	return query
}
func (query UnemploymentQuery) DataType(value string) UnemploymentQuery {
	query["datatype"] = []string{value}
	return query
}
func (client *Client) GetUnemployment(ctx context.Context, q UnemploymentQuery) (*http.Response, error) {
	req, err := client.newRequest(ctx, url.Values(q))
	if err != nil {
		return nil, err
	}
	res, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	return res, nil
}

type UnemploymentRow struct {
	TimeStamp string `column-name:"timestamp"`
	Value     string `column-name:"value"`
}

func (client *Client) GetUnemploymentCSVRows(ctx context.Context, q UnemploymentQuery) ([]UnemploymentRow, error) {
	q.DataTypeCSV()
	res, err := client.GetUnemployment(ctx, q)
	if err != nil {
		return nil, err
	}
	defer res.Body.Close()
	var rows []UnemploymentRow
	err = ParseCSV(res.Body, &rows, nil)
	if err != nil {
		return nil, err
	}
	return rows, nil
}
