// Code generated by av-generate; DO NOT EDIT.

package alphavantage

import (
	"context"
	"github.com/portfoliotree/alphavantage/api"
	"net/http"
	"net/url"
)

type ConsumerPriceIndexQuery url.Values

func QueryConsumerPriceIndex(apiKey string) ConsumerPriceIndexQuery {
	return ConsumerPriceIndexQuery{"function": []string{"CPI"}, "apikey": []string{apiKey}}
}

func (query ConsumerPriceIndexQuery) Interval(value string) ConsumerPriceIndexQuery {
	query["interval"] = []string{value}
	return query
}

func (query ConsumerPriceIndexQuery) DataTypeCSV() ConsumerPriceIndexQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query ConsumerPriceIndexQuery) DataTypeJSON() ConsumerPriceIndexQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query ConsumerPriceIndexQuery) DataType(value string) ConsumerPriceIndexQuery {
	query["datatype"] = []string{value}
	return query
}

func (q ConsumerPriceIndexQuery) DoWith(ctx context.Context, client Doer) (*http.Response, error) {
	return api.DoQuery(ctx, client, url.Values(q))
}

type ConsumerPriceIndexRow struct {
	TimeStamp string `column-name:"timestamp"`
	Value     string `column-name:"value"`
}

func (q ConsumerPriceIndexQuery) CSVRows(ctx context.Context, client Doer) ([]ConsumerPriceIndexRow, error) {
	q.DataTypeCSV()
	return api.RequestCSVRows(ctx, client, q)
}

type DurablesQuery url.Values

func QueryDurables(apiKey string) DurablesQuery {
	return DurablesQuery{"function": []string{"DURABLES"}, "apikey": []string{apiKey}}
}

func (query DurablesQuery) DataTypeCSV() DurablesQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query DurablesQuery) DataTypeJSON() DurablesQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query DurablesQuery) DataType(value string) DurablesQuery {
	query["datatype"] = []string{value}
	return query
}

func (q DurablesQuery) DoWith(ctx context.Context, client Doer) (*http.Response, error) {
	return api.DoQuery(ctx, client, url.Values(q))
}

type DurablesRow struct {
	TimeStamp string `column-name:"timestamp"`
	Value     string `column-name:"value"`
}

func (q DurablesQuery) CSVRows(ctx context.Context, client Doer) ([]DurablesRow, error) {
	q.DataTypeCSV()
	return api.RequestCSVRows(ctx, client, q)
}

type FederalFundsRateQuery url.Values

func QueryFederalFundsRate(apiKey string) FederalFundsRateQuery {
	return FederalFundsRateQuery{"function": []string{"FEDERAL_FUNDS_RATE"}, "apikey": []string{apiKey}}
}

func (query FederalFundsRateQuery) Interval(value string) FederalFundsRateQuery {
	query["interval"] = []string{value}
	return query
}

func (query FederalFundsRateQuery) DataTypeCSV() FederalFundsRateQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query FederalFundsRateQuery) DataTypeJSON() FederalFundsRateQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query FederalFundsRateQuery) DataType(value string) FederalFundsRateQuery {
	query["datatype"] = []string{value}
	return query
}

func (q FederalFundsRateQuery) DoWith(ctx context.Context, client Doer) (*http.Response, error) {
	return api.DoQuery(ctx, client, url.Values(q))
}

type FederalFundsRateRow struct {
	TimeStamp string `column-name:"timestamp"`
	Value     string `column-name:"value"`
}

func (q FederalFundsRateQuery) CSVRows(ctx context.Context, client Doer) ([]FederalFundsRateRow, error) {
	q.DataTypeCSV()
	return api.RequestCSVRows(ctx, client, q)
}

type InflationQuery url.Values

func QueryInflation(apiKey string) InflationQuery {
	return InflationQuery{"function": []string{"INFLATION"}, "apikey": []string{apiKey}}
}

func (query InflationQuery) DataTypeCSV() InflationQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query InflationQuery) DataTypeJSON() InflationQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query InflationQuery) DataType(value string) InflationQuery {
	query["datatype"] = []string{value}
	return query
}

func (q InflationQuery) DoWith(ctx context.Context, client Doer) (*http.Response, error) {
	return api.DoQuery(ctx, client, url.Values(q))
}

type InflationRow struct {
	TimeStamp string `column-name:"timestamp"`
	Value     string `column-name:"value"`
}

func (q InflationQuery) CSVRows(ctx context.Context, client Doer) ([]InflationRow, error) {
	q.DataTypeCSV()
	return api.RequestCSVRows(ctx, client, q)
}

type NonFarmPayrollQuery url.Values

func QueryNonFarmPayroll(apiKey string) NonFarmPayrollQuery {
	return NonFarmPayrollQuery{"function": []string{"NONFARM_PAYROLL"}, "apikey": []string{apiKey}}
}

func (query NonFarmPayrollQuery) DataTypeCSV() NonFarmPayrollQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query NonFarmPayrollQuery) DataTypeJSON() NonFarmPayrollQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query NonFarmPayrollQuery) DataType(value string) NonFarmPayrollQuery {
	query["datatype"] = []string{value}
	return query
}

func (q NonFarmPayrollQuery) DoWith(ctx context.Context, client Doer) (*http.Response, error) {
	return api.DoQuery(ctx, client, url.Values(q))
}

type NonFarmPayrollRow struct {
	TimeStamp string `column-name:"timestamp"`
	Value     string `column-name:"value"`
}

func (q NonFarmPayrollQuery) CSVRows(ctx context.Context, client Doer) ([]NonFarmPayrollRow, error) {
	q.DataTypeCSV()
	return api.RequestCSVRows(ctx, client, q)
}

type RealGDPQuery url.Values

func QueryRealGDP(apiKey string) RealGDPQuery {
	return RealGDPQuery{"function": []string{"REAL_GDP"}, "apikey": []string{apiKey}}
}

func (query RealGDPQuery) Interval(value string) RealGDPQuery {
	query["interval"] = []string{value}
	return query
}

func (query RealGDPQuery) DataTypeCSV() RealGDPQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query RealGDPQuery) DataTypeJSON() RealGDPQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query RealGDPQuery) DataType(value string) RealGDPQuery {
	query["datatype"] = []string{value}
	return query
}

func (q RealGDPQuery) DoWith(ctx context.Context, client Doer) (*http.Response, error) {
	return api.DoQuery(ctx, client, url.Values(q))
}

type RealGDPRow struct {
	TimeStamp string `column-name:"timestamp"`
	Value     string `column-name:"value"`
}

func (q RealGDPQuery) CSVRows(ctx context.Context, client Doer) ([]RealGDPRow, error) {
	q.DataTypeCSV()
	return api.RequestCSVRows(ctx, client, q)
}

type RealGDPPerCapitaQuery url.Values

func QueryRealGDPPerCapita(apiKey string) RealGDPPerCapitaQuery {
	return RealGDPPerCapitaQuery{"function": []string{"REAL_GDP_PER_CAPITA"}, "apikey": []string{apiKey}}
}

func (query RealGDPPerCapitaQuery) DataTypeCSV() RealGDPPerCapitaQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query RealGDPPerCapitaQuery) DataTypeJSON() RealGDPPerCapitaQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query RealGDPPerCapitaQuery) DataType(value string) RealGDPPerCapitaQuery {
	query["datatype"] = []string{value}
	return query
}

func (q RealGDPPerCapitaQuery) DoWith(ctx context.Context, client Doer) (*http.Response, error) {
	return api.DoQuery(ctx, client, url.Values(q))
}

type RealGDPPerCapitaRow struct {
	TimeStamp string `column-name:"timestamp"`
	Value     string `column-name:"value"`
}

func (q RealGDPPerCapitaQuery) CSVRows(ctx context.Context, client Doer) ([]RealGDPPerCapitaRow, error) {
	q.DataTypeCSV()
	return api.RequestCSVRows(ctx, client, q)
}

type RetailSalesQuery url.Values

func QueryRetailSales(apiKey string) RetailSalesQuery {
	return RetailSalesQuery{"function": []string{"RETAIL_SALES"}, "apikey": []string{apiKey}}
}

func (query RetailSalesQuery) DataTypeCSV() RetailSalesQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query RetailSalesQuery) DataTypeJSON() RetailSalesQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query RetailSalesQuery) DataType(value string) RetailSalesQuery {
	query["datatype"] = []string{value}
	return query
}

func (q RetailSalesQuery) DoWith(ctx context.Context, client Doer) (*http.Response, error) {
	return api.DoQuery(ctx, client, url.Values(q))
}

type RetailSalesRow struct {
	TimeStamp string `column-name:"timestamp"`
	Value     string `column-name:"value"`
}

func (q RetailSalesQuery) CSVRows(ctx context.Context, client Doer) ([]RetailSalesRow, error) {
	q.DataTypeCSV()
	return api.RequestCSVRows(ctx, client, q)
}

type TreasuryYieldQuery url.Values

func QueryTreasuryYield(apiKey string) TreasuryYieldQuery {
	return TreasuryYieldQuery{"function": []string{"TREASURY_YIELD"}, "apikey": []string{apiKey}}
}

func (query TreasuryYieldQuery) Interval(value string) TreasuryYieldQuery {
	query["interval"] = []string{value}
	return query
}

func (query TreasuryYieldQuery) Maturity(value string) TreasuryYieldQuery {
	query["maturity"] = []string{value}
	return query
}

func (query TreasuryYieldQuery) DataTypeCSV() TreasuryYieldQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query TreasuryYieldQuery) DataTypeJSON() TreasuryYieldQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query TreasuryYieldQuery) DataType(value string) TreasuryYieldQuery {
	query["datatype"] = []string{value}
	return query
}

func (q TreasuryYieldQuery) DoWith(ctx context.Context, client Doer) (*http.Response, error) {
	return api.DoQuery(ctx, client, url.Values(q))
}

type TreasuryYieldRow struct {
	TimeStamp string `column-name:"timestamp"`
	Value     string `column-name:"value"`
}

func (q TreasuryYieldQuery) CSVRows(ctx context.Context, client Doer) ([]TreasuryYieldRow, error) {
	q.DataTypeCSV()
	return api.RequestCSVRows(ctx, client, q)
}

type UnemploymentQuery url.Values

func QueryUnemployment(apiKey string) UnemploymentQuery {
	return UnemploymentQuery{"function": []string{"UNEMPLOYMENT"}, "apikey": []string{apiKey}}
}

func (query UnemploymentQuery) DataTypeCSV() UnemploymentQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query UnemploymentQuery) DataTypeJSON() UnemploymentQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query UnemploymentQuery) DataType(value string) UnemploymentQuery {
	query["datatype"] = []string{value}
	return query
}

func (q UnemploymentQuery) DoWith(ctx context.Context, client Doer) (*http.Response, error) {
	return api.DoQuery(ctx, client, url.Values(q))
}

type UnemploymentRow struct {
	TimeStamp string `column-name:"timestamp"`
	Value     string `column-name:"value"`
}

func (q UnemploymentQuery) CSVRows(ctx context.Context, client Doer) ([]UnemploymentRow, error) {
	q.DataTypeCSV()
	return api.RequestCSVRows(ctx, client, q)
}
