// Code generated by av-generate; DO NOT EDIT.

package alphavantage

import (
	"context"
	"github.com/portfoliotree/alphavantage/api"
	"net/http"
	"net/url"
)

type CurrencyExchangeRateQuery url.Values

func QueryCurrencyExchangeRate(apiKey, fromCurrency, toCurrency string) CurrencyExchangeRateQuery {
	return CurrencyExchangeRateQuery{"function": []string{"CURRENCY_EXCHANGE_RATE"}, "from_currency": []string{fromCurrency}, "to_currency": []string{toCurrency}, "apikey": []string{apiKey}}
}

func (q CurrencyExchangeRateQuery) DoWith(ctx context.Context, client Doer) (*http.Response, error) {
	return api.DoQuery(ctx, client, url.Values(q))
}

type FXDailyQuery url.Values

func QueryFXDaily(apiKey, fromSymbol, toSymbol string) FXDailyQuery {
	return FXDailyQuery{"function": []string{"FX_DAILY"}, "from_symbol": []string{fromSymbol}, "to_symbol": []string{toSymbol}, "apikey": []string{apiKey}}
}

func (query FXDailyQuery) OutputSizeCompact() FXDailyQuery {
	query["outputsize"] = []string{"compact"}
	return query
}

func (query FXDailyQuery) OutputSizeFull() FXDailyQuery {
	query["outputsize"] = []string{"full"}
	return query
}

func (query FXDailyQuery) OutputSize(value string) FXDailyQuery {
	query["outputsize"] = []string{value}
	return query
}

func (query FXDailyQuery) DataTypeCSV() FXDailyQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query FXDailyQuery) DataTypeJSON() FXDailyQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query FXDailyQuery) DataType(value string) FXDailyQuery {
	query["datatype"] = []string{value}
	return query
}

func (q FXDailyQuery) DoWith(ctx context.Context, client Doer) (*http.Response, error) {
	return api.DoQuery(ctx, client, url.Values(q))
}

type FXDailyRow struct {
	TimeStamp string `column-name:"timestamp"`
	Open      string `column-name:"open"`
	High      string `column-name:"high"`
	Low       string `column-name:"low"`
	Close     string `column-name:"close"`
}

func (q FXDailyQuery) CSVRows(ctx context.Context, client Doer) ([]FXDailyRow, error) {
	q.DataTypeCSV()
	return api.RequestCSVRows(ctx, client, q)
}

type FXIntradayQuery url.Values

func QueryFXIntraday(apiKey, fromSymbol, toSymbol, interval string) FXIntradayQuery {
	return FXIntradayQuery{"function": []string{"FX_INTRADAY"}, "from_symbol": []string{fromSymbol}, "to_symbol": []string{toSymbol}, "interval": []string{interval}, "apikey": []string{apiKey}}
}

func (query FXIntradayQuery) OutputSizeCompact() FXIntradayQuery {
	query["outputsize"] = []string{"compact"}
	return query
}

func (query FXIntradayQuery) OutputSizeFull() FXIntradayQuery {
	query["outputsize"] = []string{"full"}
	return query
}

func (query FXIntradayQuery) OutputSize(value string) FXIntradayQuery {
	query["outputsize"] = []string{value}
	return query
}

func (query FXIntradayQuery) DataTypeCSV() FXIntradayQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query FXIntradayQuery) DataTypeJSON() FXIntradayQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query FXIntradayQuery) DataType(value string) FXIntradayQuery {
	query["datatype"] = []string{value}
	return query
}

func (q FXIntradayQuery) DoWith(ctx context.Context, client Doer) (*http.Response, error) {
	return api.DoQuery(ctx, client, url.Values(q))
}

type FXIntradayRow struct {
	TimeStamp string `column-name:"timestamp"`
	Open      string `column-name:"open"`
	High      string `column-name:"high"`
	Low       string `column-name:"low"`
	Close     string `column-name:"close"`
}

func (q FXIntradayQuery) CSVRows(ctx context.Context, client Doer) ([]FXIntradayRow, error) {
	q.DataTypeCSV()
	return api.RequestCSVRows(ctx, client, q)
}

type FXMonthlyQuery url.Values

func QueryFXMonthly(apiKey, fromSymbol, toSymbol string) FXMonthlyQuery {
	return FXMonthlyQuery{"function": []string{"FX_MONTHLY"}, "from_symbol": []string{fromSymbol}, "to_symbol": []string{toSymbol}, "apikey": []string{apiKey}}
}

func (query FXMonthlyQuery) DataTypeCSV() FXMonthlyQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query FXMonthlyQuery) DataTypeJSON() FXMonthlyQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query FXMonthlyQuery) DataType(value string) FXMonthlyQuery {
	query["datatype"] = []string{value}
	return query
}

func (q FXMonthlyQuery) DoWith(ctx context.Context, client Doer) (*http.Response, error) {
	return api.DoQuery(ctx, client, url.Values(q))
}

type FXMonthlyRow struct {
	TimeStamp string `column-name:"timestamp"`
	Open      string `column-name:"open"`
	High      string `column-name:"high"`
	Low       string `column-name:"low"`
	Close     string `column-name:"close"`
}

func (q FXMonthlyQuery) CSVRows(ctx context.Context, client Doer) ([]FXMonthlyRow, error) {
	q.DataTypeCSV()
	return api.RequestCSVRows(ctx, client, q)
}

type FXWeeklyQuery url.Values

func QueryFXWeekly(apiKey, fromSymbol, toSymbol string) FXWeeklyQuery {
	return FXWeeklyQuery{"function": []string{"FX_WEEKLY"}, "from_symbol": []string{fromSymbol}, "to_symbol": []string{toSymbol}, "apikey": []string{apiKey}}
}

func (query FXWeeklyQuery) DataTypeCSV() FXWeeklyQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query FXWeeklyQuery) DataTypeJSON() FXWeeklyQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query FXWeeklyQuery) DataType(value string) FXWeeklyQuery {
	query["datatype"] = []string{value}
	return query
}

func (q FXWeeklyQuery) DoWith(ctx context.Context, client Doer) (*http.Response, error) {
	return api.DoQuery(ctx, client, url.Values(q))
}

type FXWeeklyRow struct {
	TimeStamp string `column-name:"timestamp"`
	Open      string `column-name:"open"`
	High      string `column-name:"high"`
	Low       string `column-name:"low"`
	Close     string `column-name:"close"`
}

func (q FXWeeklyQuery) CSVRows(ctx context.Context, client Doer) ([]FXWeeklyRow, error) {
	q.DataTypeCSV()
	return api.RequestCSVRows(ctx, client, q)
}
