// Code generated by av-generate; DO NOT EDIT.

package alphavantage

import (
	"context"
	"github.com/portfoliotree/alphavantage/query/commodities"
	"github.com/portfoliotree/alphavantage/query/crypto"
	"github.com/portfoliotree/alphavantage/query/economic"
	"github.com/portfoliotree/alphavantage/query/forex"
	"github.com/portfoliotree/alphavantage/query/fundamental"
	"github.com/portfoliotree/alphavantage/query/options"
	"github.com/portfoliotree/alphavantage/query/technical"
	"github.com/portfoliotree/alphavantage/query/timeseries"
)

type CommoditiesFunctions Client

func (c *Client) Commodities() *CommoditiesFunctions {
	return (*CommoditiesFunctions)(c)
}

type CryptoFunctions Client

func (c *Client) Crypto() *CryptoFunctions {
	return (*CryptoFunctions)(c)
}

type EconomicFunctions Client

func (c *Client) Economic() *EconomicFunctions {
	return (*EconomicFunctions)(c)
}

type ForexFunctions Client

func (c *Client) Forex() *ForexFunctions {
	return (*ForexFunctions)(c)
}

type FundamentalFunctions Client

func (c *Client) Fundamental() *FundamentalFunctions {
	return (*FundamentalFunctions)(c)
}

type IntelligenceFunctions Client

func (c *Client) Intelligence() *IntelligenceFunctions {
	return (*IntelligenceFunctions)(c)
}

type OptionsFunctions Client

func (c *Client) Options() *OptionsFunctions {
	return (*OptionsFunctions)(c)
}

type TechnicalFunctions Client

func (c *Client) Technical() *TechnicalFunctions {
	return (*TechnicalFunctions)(c)
}

type TimeSeriesFunctions Client

func (c *Client) TimeSeries() *TimeSeriesFunctions {
	return (*TimeSeriesFunctions)(c)
}

func (f *CommoditiesFunctions) All(ctx context.Context, query commodities.AllQuery) ([]commodities.AllRow, error) {
	return queryRows[commodities.AllRow](ctx, (*Client)(f), query)
}

func (f *CommoditiesFunctions) Aluminum(ctx context.Context, query commodities.AluminumQuery) ([]commodities.AluminumRow, error) {
	return queryRows[commodities.AluminumRow](ctx, (*Client)(f), query)
}

func (f *CommoditiesFunctions) Brent(ctx context.Context, query commodities.BrentQuery) ([]commodities.BrentRow, error) {
	return queryRows[commodities.BrentRow](ctx, (*Client)(f), query)
}

func (f *CommoditiesFunctions) Coffee(ctx context.Context, query commodities.CoffeeQuery) ([]commodities.CoffeeRow, error) {
	return queryRows[commodities.CoffeeRow](ctx, (*Client)(f), query)
}

func (f *CommoditiesFunctions) Copper(ctx context.Context, query commodities.CopperQuery) ([]commodities.CopperRow, error) {
	return queryRows[commodities.CopperRow](ctx, (*Client)(f), query)
}

func (f *CommoditiesFunctions) Corn(ctx context.Context, query commodities.CornQuery) ([]commodities.CornRow, error) {
	return queryRows[commodities.CornRow](ctx, (*Client)(f), query)
}

func (f *CommoditiesFunctions) Cotton(ctx context.Context, query commodities.CottonQuery) ([]commodities.CottonRow, error) {
	return queryRows[commodities.CottonRow](ctx, (*Client)(f), query)
}

func (f *CommoditiesFunctions) NaturalGas(ctx context.Context, query commodities.NaturalGasQuery) ([]commodities.NaturalGasRow, error) {
	return queryRows[commodities.NaturalGasRow](ctx, (*Client)(f), query)
}

func (f *CommoditiesFunctions) Sugar(ctx context.Context, query commodities.SugarQuery) ([]commodities.SugarRow, error) {
	return queryRows[commodities.SugarRow](ctx, (*Client)(f), query)
}

func (f *CommoditiesFunctions) WestTexasIntermediate(ctx context.Context, query commodities.WestTexasIntermediateQuery) ([]commodities.WestTexasIntermediateRow, error) {
	return queryRows[commodities.WestTexasIntermediateRow](ctx, (*Client)(f), query)
}

func (f *CommoditiesFunctions) Wheat(ctx context.Context, query commodities.WheatQuery) ([]commodities.WheatRow, error) {
	return queryRows[commodities.WheatRow](ctx, (*Client)(f), query)
}

func (f *CryptoFunctions) Intraday(ctx context.Context, query crypto.IntradayQuery) ([]crypto.IntradayRow, error) {
	return queryRows[crypto.IntradayRow](ctx, (*Client)(f), query)
}

func (f *CryptoFunctions) DigitalCurrencyDaily(ctx context.Context, query crypto.DigitalCurrencyDailyQuery) ([]crypto.DigitalCurrencyDailyRow, error) {
	return queryRows[crypto.DigitalCurrencyDailyRow](ctx, (*Client)(f), query)
}

func (f *CryptoFunctions) DigitalCurrencyMonthly(ctx context.Context, query crypto.DigitalCurrencyMonthlyQuery) ([]crypto.DigitalCurrencyMonthlyRow, error) {
	return queryRows[crypto.DigitalCurrencyMonthlyRow](ctx, (*Client)(f), query)
}

func (f *CryptoFunctions) DigitalCurrencyWeekly(ctx context.Context, query crypto.DigitalCurrencyWeeklyQuery) ([]crypto.DigitalCurrencyWeeklyRow, error) {
	return queryRows[crypto.DigitalCurrencyWeeklyRow](ctx, (*Client)(f), query)
}

func (f *EconomicFunctions) ConsumerPriceIndex(ctx context.Context, query economic.ConsumerPriceIndexQuery) ([]economic.ConsumerPriceIndexRow, error) {
	return queryRows[economic.ConsumerPriceIndexRow](ctx, (*Client)(f), query)
}

func (f *EconomicFunctions) Durables(ctx context.Context, query economic.DurablesQuery) ([]economic.DurablesRow, error) {
	return queryRows[economic.DurablesRow](ctx, (*Client)(f), query)
}

func (f *EconomicFunctions) FederalFundsRate(ctx context.Context, query economic.FederalFundsRateQuery) ([]economic.FederalFundsRateRow, error) {
	return queryRows[economic.FederalFundsRateRow](ctx, (*Client)(f), query)
}

func (f *EconomicFunctions) Inflation(ctx context.Context, query economic.InflationQuery) ([]economic.InflationRow, error) {
	return queryRows[economic.InflationRow](ctx, (*Client)(f), query)
}

func (f *EconomicFunctions) NonFarmPayroll(ctx context.Context, query economic.NonFarmPayrollQuery) ([]economic.NonFarmPayrollRow, error) {
	return queryRows[economic.NonFarmPayrollRow](ctx, (*Client)(f), query)
}

func (f *EconomicFunctions) RealGDP(ctx context.Context, query economic.RealGDPQuery) ([]economic.RealGDPRow, error) {
	return queryRows[economic.RealGDPRow](ctx, (*Client)(f), query)
}

func (f *EconomicFunctions) RealGDPPerCapita(ctx context.Context, query economic.RealGDPPerCapitaQuery) ([]economic.RealGDPPerCapitaRow, error) {
	return queryRows[economic.RealGDPPerCapitaRow](ctx, (*Client)(f), query)
}

func (f *EconomicFunctions) RetailSales(ctx context.Context, query economic.RetailSalesQuery) ([]economic.RetailSalesRow, error) {
	return queryRows[economic.RetailSalesRow](ctx, (*Client)(f), query)
}

func (f *EconomicFunctions) TreasuryYield(ctx context.Context, query economic.TreasuryYieldQuery) ([]economic.TreasuryYieldRow, error) {
	return queryRows[economic.TreasuryYieldRow](ctx, (*Client)(f), query)
}

func (f *EconomicFunctions) Unemployment(ctx context.Context, query economic.UnemploymentQuery) ([]economic.UnemploymentRow, error) {
	return queryRows[economic.UnemploymentRow](ctx, (*Client)(f), query)
}

func (f *ForexFunctions) Daily(ctx context.Context, query forex.DailyQuery) ([]forex.DailyRow, error) {
	return queryRows[forex.DailyRow](ctx, (*Client)(f), query)
}

func (f *ForexFunctions) Intraday(ctx context.Context, query forex.IntradayQuery) ([]forex.IntradayRow, error) {
	return queryRows[forex.IntradayRow](ctx, (*Client)(f), query)
}

func (f *ForexFunctions) Monthly(ctx context.Context, query forex.MonthlyQuery) ([]forex.MonthlyRow, error) {
	return queryRows[forex.MonthlyRow](ctx, (*Client)(f), query)
}

func (f *ForexFunctions) Weekly(ctx context.Context, query forex.WeeklyQuery) ([]forex.WeeklyRow, error) {
	return queryRows[forex.WeeklyRow](ctx, (*Client)(f), query)
}

func (f *FundamentalFunctions) Dividends(ctx context.Context, query fundamental.DividendsQuery) ([]fundamental.DividendsRow, error) {
	return queryRows[fundamental.DividendsRow](ctx, (*Client)(f), query)
}

func (f *FundamentalFunctions) EarningsCalendar(ctx context.Context, query fundamental.EarningsCalendarQuery) ([]fundamental.EarningsCalendarRow, error) {
	return queryRows[fundamental.EarningsCalendarRow](ctx, (*Client)(f), query)
}

func (f *FundamentalFunctions) IPOCalendar(ctx context.Context, query fundamental.IPOCalendarQuery) ([]fundamental.IPOCalendarRow, error) {
	return queryRows[fundamental.IPOCalendarRow](ctx, (*Client)(f), query)
}

func (f *FundamentalFunctions) ListingStatus(ctx context.Context, query fundamental.ListingStatusQuery) ([]fundamental.ListingStatusRow, error) {
	return queryRows[fundamental.ListingStatusRow](ctx, (*Client)(f), query)
}

func (f *FundamentalFunctions) SharesOutstanding(ctx context.Context, query fundamental.SharesOutstandingQuery) ([]fundamental.SharesOutstandingRow, error) {
	return queryRows[fundamental.SharesOutstandingRow](ctx, (*Client)(f), query)
}

func (f *FundamentalFunctions) Splits(ctx context.Context, query fundamental.SplitsQuery) ([]fundamental.SplitsRow, error) {
	return queryRows[fundamental.SplitsRow](ctx, (*Client)(f), query)
}

func (f *OptionsFunctions) Historical(ctx context.Context, query options.HistoricalQuery) ([]options.HistoricalRow, error) {
	return queryRows[options.HistoricalRow](ctx, (*Client)(f), query)
}

func (f *TechnicalFunctions) AbsolutePriceOscillator(ctx context.Context, query technical.AbsolutePriceOscillatorQuery) ([]technical.AbsolutePriceOscillatorRow, error) {
	return queryRows[technical.AbsolutePriceOscillatorRow](ctx, (*Client)(f), query)
}

func (f *TechnicalFunctions) Aroon(ctx context.Context, query technical.AroonQuery) ([]technical.AroonRow, error) {
	return queryRows[technical.AroonRow](ctx, (*Client)(f), query)
}

func (f *TechnicalFunctions) AroonOsc(ctx context.Context, query technical.AroonOscQuery) ([]technical.AroonOscRow, error) {
	return queryRows[technical.AroonOscRow](ctx, (*Client)(f), query)
}

func (f *TechnicalFunctions) AverageDirectionalMovementIndex(ctx context.Context, query technical.AverageDirectionalMovementIndexQuery) ([]technical.AverageDirectionalMovementIndexRow, error) {
	return queryRows[technical.AverageDirectionalMovementIndexRow](ctx, (*Client)(f), query)
}

func (f *TechnicalFunctions) AverageDirectionalMovementIndexRating(ctx context.Context, query technical.AverageDirectionalMovementIndexRatingQuery) ([]technical.AverageDirectionalMovementIndexRatingRow, error) {
	return queryRows[technical.AverageDirectionalMovementIndexRatingRow](ctx, (*Client)(f), query)
}

func (f *TechnicalFunctions) AverageTrueRange(ctx context.Context, query technical.AverageTrueRangeQuery) ([]technical.AverageTrueRangeRow, error) {
	return queryRows[technical.AverageTrueRangeRow](ctx, (*Client)(f), query)
}

func (f *TechnicalFunctions) BalanceOfPower(ctx context.Context, query technical.BalanceOfPowerQuery) ([]technical.BalanceOfPowerRow, error) {
	return queryRows[technical.BalanceOfPowerRow](ctx, (*Client)(f), query)
}

func (f *TechnicalFunctions) BollingerBands(ctx context.Context, query technical.BollingerBandsQuery) ([]technical.BollingerBandsRow, error) {
	return queryRows[technical.BollingerBandsRow](ctx, (*Client)(f), query)
}

func (f *TechnicalFunctions) ChaikinADLine(ctx context.Context, query technical.ChaikinADLineQuery) ([]technical.ChaikinADLineRow, error) {
	return queryRows[technical.ChaikinADLineRow](ctx, (*Client)(f), query)
}

func (f *TechnicalFunctions) ChaikinADOscillator(ctx context.Context, query technical.ChaikinADOscillatorQuery) ([]technical.ChaikinADOscillatorRow, error) {
	return queryRows[technical.ChaikinADOscillatorRow](ctx, (*Client)(f), query)
}

func (f *TechnicalFunctions) ChandeMomentumOscillator(ctx context.Context, query technical.ChandeMomentumOscillatorQuery) ([]technical.ChandeMomentumOscillatorRow, error) {
	return queryRows[technical.ChandeMomentumOscillatorRow](ctx, (*Client)(f), query)
}

func (f *TechnicalFunctions) CommodityChannelIndex(ctx context.Context, query technical.CommodityChannelIndexQuery) ([]technical.CommodityChannelIndexRow, error) {
	return queryRows[technical.CommodityChannelIndexRow](ctx, (*Client)(f), query)
}

func (f *TechnicalFunctions) DirectionalMovementIndex(ctx context.Context, query technical.DirectionalMovementIndexQuery) ([]technical.DirectionalMovementIndexRow, error) {
	return queryRows[technical.DirectionalMovementIndexRow](ctx, (*Client)(f), query)
}

func (f *TechnicalFunctions) DoubleExponentialMovingAverage(ctx context.Context, query technical.DoubleExponentialMovingAverageQuery) ([]technical.DoubleExponentialMovingAverageRow, error) {
	return queryRows[technical.DoubleExponentialMovingAverageRow](ctx, (*Client)(f), query)
}

func (f *TechnicalFunctions) ExponentialMovingAverage(ctx context.Context, query technical.ExponentialMovingAverageQuery) ([]technical.ExponentialMovingAverageRow, error) {
	return queryRows[technical.ExponentialMovingAverageRow](ctx, (*Client)(f), query)
}

func (f *TechnicalFunctions) HilbertTransformDCPeriod(ctx context.Context, query technical.HilbertTransformDCPeriodQuery) ([]technical.HilbertTransformDCPeriodRow, error) {
	return queryRows[technical.HilbertTransformDCPeriodRow](ctx, (*Client)(f), query)
}

func (f *TechnicalFunctions) HilbertTransformDCPhase(ctx context.Context, query technical.HilbertTransformDCPhaseQuery) ([]technical.HilbertTransformDCPhaseRow, error) {
	return queryRows[technical.HilbertTransformDCPhaseRow](ctx, (*Client)(f), query)
}

func (f *TechnicalFunctions) HilbertTransformPhasor(ctx context.Context, query technical.HilbertTransformPhasorQuery) ([]technical.HilbertTransformPhasorRow, error) {
	return queryRows[technical.HilbertTransformPhasorRow](ctx, (*Client)(f), query)
}

func (f *TechnicalFunctions) HilbertTransformSine(ctx context.Context, query technical.HilbertTransformSineQuery) ([]technical.HilbertTransformSineRow, error) {
	return queryRows[technical.HilbertTransformSineRow](ctx, (*Client)(f), query)
}

func (f *TechnicalFunctions) HilbertTransformTrendLine(ctx context.Context, query technical.HilbertTransformTrendLineQuery) ([]technical.HilbertTransformTrendLineRow, error) {
	return queryRows[technical.HilbertTransformTrendLineRow](ctx, (*Client)(f), query)
}

func (f *TechnicalFunctions) HilbertTransformTrendMode(ctx context.Context, query technical.HilbertTransformTrendModeQuery) ([]technical.HilbertTransformTrendModeRow, error) {
	return queryRows[technical.HilbertTransformTrendModeRow](ctx, (*Client)(f), query)
}

func (f *TechnicalFunctions) KaufmanAdaptiveMovingAverage(ctx context.Context, query technical.KaufmanAdaptiveMovingAverageQuery) ([]technical.KaufmanAdaptiveMovingAverageRow, error) {
	return queryRows[technical.KaufmanAdaptiveMovingAverageRow](ctx, (*Client)(f), query)
}

func (f *TechnicalFunctions) MESAAdaptiveMovingAverage(ctx context.Context, query technical.MESAAdaptiveMovingAverageQuery) ([]technical.MESAAdaptiveMovingAverageRow, error) {
	return queryRows[technical.MESAAdaptiveMovingAverageRow](ctx, (*Client)(f), query)
}

func (f *TechnicalFunctions) MidPoint(ctx context.Context, query technical.MidPointQuery) ([]technical.MidPointRow, error) {
	return queryRows[technical.MidPointRow](ctx, (*Client)(f), query)
}

func (f *TechnicalFunctions) MidPrice(ctx context.Context, query technical.MidPriceQuery) ([]technical.MidPriceRow, error) {
	return queryRows[technical.MidPriceRow](ctx, (*Client)(f), query)
}

func (f *TechnicalFunctions) MinusDirectionalIndicator(ctx context.Context, query technical.MinusDirectionalIndicatorQuery) ([]technical.MinusDirectionalIndicatorRow, error) {
	return queryRows[technical.MinusDirectionalIndicatorRow](ctx, (*Client)(f), query)
}

func (f *TechnicalFunctions) MinusDirectionalMovement(ctx context.Context, query technical.MinusDirectionalMovementQuery) ([]technical.MinusDirectionalMovementRow, error) {
	return queryRows[technical.MinusDirectionalMovementRow](ctx, (*Client)(f), query)
}

func (f *TechnicalFunctions) Momentum(ctx context.Context, query technical.MomentumQuery) ([]technical.MomentumRow, error) {
	return queryRows[technical.MomentumRow](ctx, (*Client)(f), query)
}

func (f *TechnicalFunctions) MoneyFlowIndex(ctx context.Context, query technical.MoneyFlowIndexQuery) ([]technical.MoneyFlowIndexRow, error) {
	return queryRows[technical.MoneyFlowIndexRow](ctx, (*Client)(f), query)
}

func (f *TechnicalFunctions) MovingAverageConvergenceDivergence(ctx context.Context, query technical.MovingAverageConvergenceDivergenceQuery) ([]technical.MovingAverageConvergenceDivergenceRow, error) {
	return queryRows[technical.MovingAverageConvergenceDivergenceRow](ctx, (*Client)(f), query)
}

func (f *TechnicalFunctions) MovingAverageConvergenceDivergenceExt(ctx context.Context, query technical.MovingAverageConvergenceDivergenceExtQuery) ([]technical.MovingAverageConvergenceDivergenceExtRow, error) {
	return queryRows[technical.MovingAverageConvergenceDivergenceExtRow](ctx, (*Client)(f), query)
}

func (f *TechnicalFunctions) NormalizedAverageTrueRange(ctx context.Context, query technical.NormalizedAverageTrueRangeQuery) ([]technical.NormalizedAverageTrueRangeRow, error) {
	return queryRows[technical.NormalizedAverageTrueRangeRow](ctx, (*Client)(f), query)
}

func (f *TechnicalFunctions) OnBalanceVolume(ctx context.Context, query technical.OnBalanceVolumeQuery) ([]technical.OnBalanceVolumeRow, error) {
	return queryRows[technical.OnBalanceVolumeRow](ctx, (*Client)(f), query)
}

func (f *TechnicalFunctions) OneDayRateOfChangeTripleSmoothExponentialMovingAverage(ctx context.Context, query technical.OneDayRateOfChangeTripleSmoothExponentialMovingAverageQuery) ([]technical.OneDayRateOfChangeTripleSmoothExponentialMovingAverageRow, error) {
	return queryRows[technical.OneDayRateOfChangeTripleSmoothExponentialMovingAverageRow](ctx, (*Client)(f), query)
}

func (f *TechnicalFunctions) PercentagePriceOscillator(ctx context.Context, query technical.PercentagePriceOscillatorQuery) ([]technical.PercentagePriceOscillatorRow, error) {
	return queryRows[technical.PercentagePriceOscillatorRow](ctx, (*Client)(f), query)
}

func (f *TechnicalFunctions) PlusDirectionalIndicator(ctx context.Context, query technical.PlusDirectionalIndicatorQuery) ([]technical.PlusDirectionalIndicatorRow, error) {
	return queryRows[technical.PlusDirectionalIndicatorRow](ctx, (*Client)(f), query)
}

func (f *TechnicalFunctions) PlusDirectionalMovement(ctx context.Context, query technical.PlusDirectionalMovementQuery) ([]technical.PlusDirectionalMovementRow, error) {
	return queryRows[technical.PlusDirectionalMovementRow](ctx, (*Client)(f), query)
}

func (f *TechnicalFunctions) RateOfChange(ctx context.Context, query technical.RateOfChangeQuery) ([]technical.RateOfChangeRow, error) {
	return queryRows[technical.RateOfChangeRow](ctx, (*Client)(f), query)
}

func (f *TechnicalFunctions) RateOfChangeRatio(ctx context.Context, query technical.RateOfChangeRatioQuery) ([]technical.RateOfChangeRatioRow, error) {
	return queryRows[technical.RateOfChangeRatioRow](ctx, (*Client)(f), query)
}

func (f *TechnicalFunctions) RelativeStrengthIndex(ctx context.Context, query technical.RelativeStrengthIndexQuery) ([]technical.RelativeStrengthIndexRow, error) {
	return queryRows[technical.RelativeStrengthIndexRow](ctx, (*Client)(f), query)
}

func (f *TechnicalFunctions) SAR(ctx context.Context, query technical.SARQuery) ([]technical.SARRow, error) {
	return queryRows[technical.SARRow](ctx, (*Client)(f), query)
}

func (f *TechnicalFunctions) SimpleMovingAverage(ctx context.Context, query technical.SimpleMovingAverageQuery) ([]technical.SimpleMovingAverageRow, error) {
	return queryRows[technical.SimpleMovingAverageRow](ctx, (*Client)(f), query)
}

func (f *TechnicalFunctions) StochasticFast(ctx context.Context, query technical.StochasticFastQuery) ([]technical.StochasticFastRow, error) {
	return queryRows[technical.StochasticFastRow](ctx, (*Client)(f), query)
}

func (f *TechnicalFunctions) StochasticOscillator(ctx context.Context, query technical.StochasticOscillatorQuery) ([]technical.StochasticOscillatorRow, error) {
	return queryRows[technical.StochasticOscillatorRow](ctx, (*Client)(f), query)
}

func (f *TechnicalFunctions) StochasticRelativeStrengthIndex(ctx context.Context, query technical.StochasticRelativeStrengthIndexQuery) ([]technical.StochasticRelativeStrengthIndexRow, error) {
	return queryRows[technical.StochasticRelativeStrengthIndexRow](ctx, (*Client)(f), query)
}

func (f *TechnicalFunctions) T3(ctx context.Context, query technical.T3Query) ([]technical.T3Row, error) {
	return queryRows[technical.T3Row](ctx, (*Client)(f), query)
}

func (f *TechnicalFunctions) TriangularMovingAverage(ctx context.Context, query technical.TriangularMovingAverageQuery) ([]technical.TriangularMovingAverageRow, error) {
	return queryRows[technical.TriangularMovingAverageRow](ctx, (*Client)(f), query)
}

func (f *TechnicalFunctions) TripleExponentialMovingAverage(ctx context.Context, query technical.TripleExponentialMovingAverageQuery) ([]technical.TripleExponentialMovingAverageRow, error) {
	return queryRows[technical.TripleExponentialMovingAverageRow](ctx, (*Client)(f), query)
}

func (f *TechnicalFunctions) TrueRange(ctx context.Context, query technical.TrueRangeQuery) ([]technical.TrueRangeRow, error) {
	return queryRows[technical.TrueRangeRow](ctx, (*Client)(f), query)
}

func (f *TechnicalFunctions) UltimateOscillator(ctx context.Context, query technical.UltimateOscillatorQuery) ([]technical.UltimateOscillatorRow, error) {
	return queryRows[technical.UltimateOscillatorRow](ctx, (*Client)(f), query)
}

func (f *TechnicalFunctions) VolumeWeightedAveragePrice(ctx context.Context, query technical.VolumeWeightedAveragePriceQuery) ([]technical.VolumeWeightedAveragePriceRow, error) {
	return queryRows[technical.VolumeWeightedAveragePriceRow](ctx, (*Client)(f), query)
}

func (f *TechnicalFunctions) WeightedMovingAverage(ctx context.Context, query technical.WeightedMovingAverageQuery) ([]technical.WeightedMovingAverageRow, error) {
	return queryRows[technical.WeightedMovingAverageRow](ctx, (*Client)(f), query)
}

func (f *TechnicalFunctions) WilliamsR(ctx context.Context, query technical.WilliamsRQuery) ([]technical.WilliamsRRow, error) {
	return queryRows[technical.WilliamsRRow](ctx, (*Client)(f), query)
}

func (f *TimeSeriesFunctions) GlobalQuote(ctx context.Context, query timeseries.GlobalQuoteQuery) ([]timeseries.GlobalQuoteRow, error) {
	return queryRows[timeseries.GlobalQuoteRow](ctx, (*Client)(f), query)
}

func (f *TimeSeriesFunctions) SymbolSearch(ctx context.Context, query timeseries.SymbolSearchQuery) ([]timeseries.SymbolSearchRow, error) {
	return queryRows[timeseries.SymbolSearchRow](ctx, (*Client)(f), query)
}

func (f *TimeSeriesFunctions) Daily(ctx context.Context, query timeseries.DailyQuery) ([]timeseries.DailyRow, error) {
	return queryRows[timeseries.DailyRow](ctx, (*Client)(f), query)
}

func (f *TimeSeriesFunctions) DailyAdjusted(ctx context.Context, query timeseries.DailyAdjustedQuery) ([]timeseries.DailyAdjustedRow, error) {
	return queryRows[timeseries.DailyAdjustedRow](ctx, (*Client)(f), query)
}

func (f *TimeSeriesFunctions) Intraday(ctx context.Context, query timeseries.IntradayQuery) ([]timeseries.IntradayRow, error) {
	return queryRows[timeseries.IntradayRow](ctx, (*Client)(f), query)
}

func (f *TimeSeriesFunctions) Monthly(ctx context.Context, query timeseries.MonthlyQuery) ([]timeseries.MonthlyRow, error) {
	return queryRows[timeseries.MonthlyRow](ctx, (*Client)(f), query)
}

func (f *TimeSeriesFunctions) MonthlyAdjusted(ctx context.Context, query timeseries.MonthlyAdjustedQuery) ([]timeseries.MonthlyAdjustedRow, error) {
	return queryRows[timeseries.MonthlyAdjustedRow](ctx, (*Client)(f), query)
}

func (f *TimeSeriesFunctions) Weekly(ctx context.Context, query timeseries.WeeklyQuery) ([]timeseries.WeeklyRow, error) {
	return queryRows[timeseries.WeeklyRow](ctx, (*Client)(f), query)
}

func (f *TimeSeriesFunctions) WeeklyAdjusted(ctx context.Context, query timeseries.WeeklyAdjustedQuery) ([]timeseries.WeeklyAdjustedRow, error) {
	return queryRows[timeseries.WeeklyAdjustedRow](ctx, (*Client)(f), query)
}
