// Code generated by github.com/portfoliotree/alphavantage/cmd/generate; DO NOT EDIT.

package alphavantage

import (
	"context"
	"net/http"
	"net/url"
	"time"
)

type AnalyticsFixedWindowQuery url.Values

func QueryAnalyticsFixedWindow(apiKey, symbols, rng, intervalAnalytics, calculations string) AnalyticsFixedWindowQuery {
	return AnalyticsFixedWindowQuery{"function": []string{"ANALYTICS_FIXED_WINDOW"}, "SYMBOLS": []string{symbols}, "RANGE": []string{rng}, "INTERVAL": []string{intervalAnalytics}, "CALCULATIONS": []string{calculations}, "apikey": []string{apiKey}}
}
func (query AnalyticsFixedWindowQuery) OHLCOpen() AnalyticsFixedWindowQuery {
	query["OHLC"] = []string{"open"}
	return query
}
func (query AnalyticsFixedWindowQuery) OHLCHigh() AnalyticsFixedWindowQuery {
	query["OHLC"] = []string{"high"}
	return query
}
func (query AnalyticsFixedWindowQuery) OHLCLow() AnalyticsFixedWindowQuery {
	query["OHLC"] = []string{"low"}
	return query
}
func (query AnalyticsFixedWindowQuery) OHLCClose() AnalyticsFixedWindowQuery {
	query["OHLC"] = []string{"close"}
	return query
}
func (query AnalyticsFixedWindowQuery) OHLC(value string) AnalyticsFixedWindowQuery {
	query["OHLC"] = []string{value}
	return query
}
func (client *Client) GetAnalyticsFixedWindow(ctx context.Context, q AnalyticsFixedWindowQuery) (*http.Response, error) {
	req, err := client.newRequest(ctx, url.Values(q))
	if err != nil {
		return nil, err
	}
	res, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	return res, nil
}

type AnalyticsSlidingWindowQuery url.Values

func QueryAnalyticsSlidingWindow(apiKey, symbols, rng, intervalAnalytics, windowSize, calculations string) AnalyticsSlidingWindowQuery {
	return AnalyticsSlidingWindowQuery{"function": []string{"ANALYTICS_SLIDING_WINDOW"}, "SYMBOLS": []string{symbols}, "RANGE": []string{rng}, "INTERVAL": []string{intervalAnalytics}, "WINDOW_SIZE": []string{windowSize}, "CALCULATIONS": []string{calculations}, "apikey": []string{apiKey}}
}
func (query AnalyticsSlidingWindowQuery) OHLCOpen() AnalyticsSlidingWindowQuery {
	query["OHLC"] = []string{"open"}
	return query
}
func (query AnalyticsSlidingWindowQuery) OHLCHigh() AnalyticsSlidingWindowQuery {
	query["OHLC"] = []string{"high"}
	return query
}
func (query AnalyticsSlidingWindowQuery) OHLCLow() AnalyticsSlidingWindowQuery {
	query["OHLC"] = []string{"low"}
	return query
}
func (query AnalyticsSlidingWindowQuery) OHLCClose() AnalyticsSlidingWindowQuery {
	query["OHLC"] = []string{"close"}
	return query
}
func (query AnalyticsSlidingWindowQuery) OHLC(value string) AnalyticsSlidingWindowQuery {
	query["OHLC"] = []string{value}
	return query
}
func (client *Client) GetAnalyticsSlidingWindow(ctx context.Context, q AnalyticsSlidingWindowQuery) (*http.Response, error) {
	req, err := client.newRequest(ctx, url.Values(q))
	if err != nil {
		return nil, err
	}
	res, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	return res, nil
}

type EarningsCallTranscriptQuery url.Values

func QueryEarningsCallTranscript(apiKey, symbol, quarter string) EarningsCallTranscriptQuery {
	return EarningsCallTranscriptQuery{"function": []string{"EARNINGS_CALL_TRANSCRIPT"}, "symbol": []string{symbol}, "quarter": []string{quarter}, "apikey": []string{apiKey}}
}
func (client *Client) GetEarningsCallTranscript(ctx context.Context, q EarningsCallTranscriptQuery) (*http.Response, error) {
	req, err := client.newRequest(ctx, url.Values(q))
	if err != nil {
		return nil, err
	}
	res, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	return res, nil
}

type InsiderTransactionsQuery url.Values

func QueryInsiderTransactions(apiKey, symbol string) InsiderTransactionsQuery {
	return InsiderTransactionsQuery{"function": []string{"INSIDER_TRANSACTIONS"}, "symbol": []string{symbol}, "apikey": []string{apiKey}}
}
func (client *Client) GetInsiderTransactions(ctx context.Context, q InsiderTransactionsQuery) (*http.Response, error) {
	req, err := client.newRequest(ctx, url.Values(q))
	if err != nil {
		return nil, err
	}
	res, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	return res, nil
}

type NewsSentimentQuery url.Values

func QueryNewsSentiment(apiKey string) NewsSentimentQuery {
	return NewsSentimentQuery{"function": []string{"NEWS_SENTIMENT"}, "apikey": []string{apiKey}}
}
func (query NewsSentimentQuery) Tickers(value string) NewsSentimentQuery {
	query["tickers"] = []string{value}
	return query
}
func (query NewsSentimentQuery) Topics(value string) NewsSentimentQuery {
	query["topics"] = []string{value}
	return query
}
func (query NewsSentimentQuery) TimeFrom(value time.Time) NewsSentimentQuery {
	query["time_from"] = []string{value.Format("20060102T1504")}
	return query
}
func (query NewsSentimentQuery) TimeTo(value time.Time) NewsSentimentQuery {
	query["time_to"] = []string{value.Format("20060102T1504")}
	return query
}
func (query NewsSentimentQuery) Sort(value string) NewsSentimentQuery {
	query["sort"] = []string{value}
	return query
}
func (query NewsSentimentQuery) Limit(value string) NewsSentimentQuery {
	query["limit"] = []string{value}
	return query
}
func (client *Client) GetNewsSentiment(ctx context.Context, q NewsSentimentQuery) (*http.Response, error) {
	req, err := client.newRequest(ctx, url.Values(q))
	if err != nil {
		return nil, err
	}
	res, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	return res, nil
}

type TopGainersLosersQuery url.Values

func QueryTopGainersLosers(apiKey string) TopGainersLosersQuery {
	return TopGainersLosersQuery{"function": []string{"TOP_GAINERS_LOSERS"}, "apikey": []string{apiKey}}
}
func (client *Client) GetTopGainersLosers(ctx context.Context, q TopGainersLosersQuery) (*http.Response, error) {
	req, err := client.newRequest(ctx, url.Values(q))
	if err != nil {
		return nil, err
	}
	res, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	return res, nil
}
