package alphavantage_test

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"net/http"
	"os"
	"testing"

	. "github.com/onsi/gomega"

	"github.com/portfoliotree/alphavantage"
)

func TestClient_CompanyOverview(t *testing.T) {
	f, err := os.Open("test_data/company_overview.json")
	if err != nil {
		t.Fatal(err)
	}
	defer func() {
		_ = f.Close()
	}()
	buf, err := io.ReadAll(f)
	if err != nil {
		t.Fatal(err)
	}

	o := NewWithT(t)

	ctx := context.Background()

	var (
		avReq         *http.Request
		waitCallCount = 0
	)

	overview, err := (&alphavantage.Client{
		Client: doerFunc(func(request *http.Request) (*http.Response, error) {
			avReq = request
			return &http.Response{
				Body:       io.NopCloser(bytes.NewReader(buf)),
				StatusCode: http.StatusOK,
			}, nil
		}),
		APIKey: "demo",
		Limiter: waitFunc(func(ctx context.Context) error {
			waitCallCount++
			return nil
		}),
	}).CompanyOverview(ctx, "IBM")
	o.Expect(err).NotTo(HaveOccurred())

	o.Expect(avReq.URL.Query().Get("function")).To(Equal("OVERVIEW"))
	o.Expect(avReq.URL.Query().Get("symbol")).To(Equal("IBM"))

	o.Expect(overview.Symbol).To(Equal("IBM"))
	o.Expect(overview.AssetType).To(Equal("Common Stock"))
	o.Expect(overview.Name).To(Equal("International Business Machines Corporation"))
	o.Expect(overview.Description).To(Equal("International Business Machines Corporation (IBM) is an American multinational technology company headquartered in Armonk, New York, with operations in over 170 countries. The company began in 1911, founded in Endicott, New York, as the Computing-Tabulating-Recording Company (CTR) and was renamed International Business Machines in 1924. IBM is incorporated in New York. IBM produces and sells computer hardware, middleware and software, and provides hosting and consulting services in areas ranging from mainframe computers to nanotechnology. IBM is also a major research organization, holding the record for most annual U.S. patents generated by a business (as of 2020) for 28 consecutive years. Inventions by IBM include the automated teller machine (ATM), the floppy disk, the hard disk drive, the magnetic stripe card, the relational database, the SQL programming language, the UPC barcode, and dynamic random-access memory (DRAM). The IBM mainframe, exemplified by the System/360, was the dominant computing platform during the 1960s and 1970s."))
	o.Expect(overview.CIK).To(Equal("51143"))
	o.Expect(overview.Exchange).To(Equal("NYSE"))
	o.Expect(overview.Currency).To(Equal("USD"))
	o.Expect(overview.Country).To(Equal("USA"))
	o.Expect(overview.Sector).To(Equal("TECHNOLOGY"))
	please.Expect(overview.Industry).To(Equal("COMPUTER & OFFICE EQUIPMENT"))
	please.Expect(overview.Address).To(Equal("1 NEW ORCHARD ROAD, ARMONK, NY, US"))
	please.Expect(overview.FiscalYearEnd).To(Equal("December"))
	please.Expect(overview.LatestQuarter).To(Equal(mustParseDate(t, "2021-06-30")), fmt.Sprintf("%q != %q", overview.LatestQuarter.String(), "2021-06-30"))
	please.Expect(overview.MarketCapitalization).To(Equal(119909687000))
	please.Expect(overview.EBITDA).To(Equal(15992001000))
	please.Expect(overview.PERatio).To(Equal(22.61))
	please.Expect(overview.PEGRatio).To(Equal(1.397))
	please.Expect(overview.BookValue).To(Equal(24.48))
	please.Expect(overview.DividendPerShare).To(Equal(6.53))
	please.Expect(overview.DividendYield).To(Equal(0.0486))
	please.Expect(overview.EPS).To(Equal(5.92))
	please.Expect(overview.RevenuePerShareTTM).To(Equal(83.3))
	please.Expect(overview.ProfitMargin).To(Equal(0.0717))
	please.Expect(overview.OperatingMarginTTM).To(Equal(0.124))
	please.Expect(overview.ReturnOnAssetsTTM).To(Equal(0.0385))
	please.Expect(overview.ReturnOnEquityTTM).To(Equal(0.245))
	please.Expect(overview.RevenueTTM).To(Equal(74400997000))
	please.Expect(overview.GrossProfitTTM).To(Equal(35575000000))
	please.Expect(overview.DilutedEPSTTM).To(Equal(5.92))
	please.Expect(overview.QuarterlyEarningsGrowthYOY).To(Equal(-0.032))
	please.Expect(overview.QuarterlyRevenueGrowthYOY).To(Equal(0.034))
	please.Expect(overview.AnalystTargetPrice).To(Equal(150.0))
	please.Expect(overview.TrailingPE).To(Equal(22.61))
	please.Expect(overview.ForwardPE).To(Equal(11.04))
	please.Expect(overview.PriceToSalesRatioTTM).To(Equal(1.612))
	please.Expect(overview.PriceToBookRatio).To(Equal(5.49))
	please.Expect(overview.EVToRevenue).To(Equal(2.326))
	please.Expect(overview.EVToEBITDA).To(Equal(12.81))
	please.Expect(overview.Beta).To(Equal(1.212))
	please.Expect(overview.FiftyTwoWeekHigh).To(Equal(151.1))
	please.Expect(overview.FiftyTwoWeekLow).To(Equal(100.73))
	please.Expect(overview.FiftyDayMovingAverage).To(Equal(139.81))
	please.Expect(overview.TwoHundredDayMovingAverage).To(Equal(140.06))
	please.Expect(overview.SharesOutstanding).To(Equal(896320000))
	please.Expect(overview.SharesFloat).To(Equal(894743000))
	please.Expect(overview.SharesShort).To(Equal(25087600))
	please.Expect(overview.SharesShortPriorMonth).To(Equal(25615000))
	please.Expect(overview.ShortRatio).To(Equal(7.92))
	please.Expect(overview.ShortPercentOutstanding).To(Equal(0.03))
	please.Expect(overview.ShortPercentFloat).To(Equal(0.028))
	please.Expect(overview.PercentInsiders).To(Equal(0.133))
	please.Expect(overview.PercentInstitutions).To(Equal(57.72))
	please.Expect(overview.ForwardAnnualDividendRate).To(Equal(6.56))
	please.Expect(overview.ForwardAnnualDividendYield).To(Equal(0.0488))
	please.Expect(overview.PayoutRatio).To(Equal(0.747))
	please.Expect(overview.DividendDate).To(Equal(mustParseDate(t, "2021-09-10")))
	please.Expect(overview.ExDividendDate).To(Equal(mustParseDate(t, "2021-08-09")))
	please.Expect(overview.LastSplitFactor).To(Equal("2:1"))
	please.Expect(overview.LastSplitDate).To(Equal(mustParseDate(t, "1999-05-27")))
}
