// Code generated by github.com/portfoliotree/alphavantage/cmd/generate; DO NOT EDIT.

package alphavantage

import (
	"context"
	"net/http"
	"net/url"
	"time"
)

type AverageTrueRangeQuery url.Values

func QueryAverageTrueRange(apiKey, symbol, interval string) AverageTrueRangeQuery {
	return AverageTrueRangeQuery{"function": []string{"ATR"}, "symbol": []string{symbol}, "interval": []string{interval}, "apikey": []string{apiKey}}
}
func (query AverageTrueRangeQuery) Month(value time.Time) AverageTrueRangeQuery {
	query["month"] = []string{value.Format("2006-01")}
	return query
}
func (query AverageTrueRangeQuery) TimePeriod(value string) AverageTrueRangeQuery {
	query["time_period"] = []string{value}
	return query
}
func (query AverageTrueRangeQuery) DataTypeCSV() AverageTrueRangeQuery {
	query["datatype"] = []string{"csv"}
	return query
}
func (query AverageTrueRangeQuery) DataTypeJSON() AverageTrueRangeQuery {
	query["datatype"] = []string{"json"}
	return query
}
func (query AverageTrueRangeQuery) DataType(value string) AverageTrueRangeQuery {
	query["datatype"] = []string{value}
	return query
}
func (client *Client) GetAverageTrueRange(ctx context.Context, q AverageTrueRangeQuery) (*http.Response, error) {
	req, err := client.newRequest(ctx, url.Values(q))
	if err != nil {
		return nil, err
	}
	res, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	return res, nil
}

type AverageTrueRangeRow struct {
	Time  string `column-name:"time"`
	Value string `column-name:"ATR"`
}

func (client *Client) GetAverageTrueRangeCSVRows(ctx context.Context, q AverageTrueRangeQuery) ([]AverageTrueRangeRow, error) {
	q.DataTypeCSV()
	res, err := client.GetAverageTrueRange(ctx, q)
	if err != nil {
		return nil, err
	}
	defer res.Body.Close()
	var rows []AverageTrueRangeRow
	err = ParseCSV(res.Body, &rows, nil)
	if err != nil {
		return nil, err
	}
	return rows, nil
}

type BollingerBandsQuery url.Values

func QueryBollingerBands(apiKey, symbol, interval, seriesType string) BollingerBandsQuery {
	return BollingerBandsQuery{"function": []string{"BBANDS"}, "symbol": []string{symbol}, "interval": []string{interval}, "series_type": []string{seriesType}, "apikey": []string{apiKey}}
}
func (query BollingerBandsQuery) Month(value time.Time) BollingerBandsQuery {
	query["month"] = []string{value.Format("2006-01")}
	return query
}
func (query BollingerBandsQuery) TimePeriod(value string) BollingerBandsQuery {
	query["time_period"] = []string{value}
	return query
}
func (query BollingerBandsQuery) UpperBandStandardDeviationMultiplier(value string) BollingerBandsQuery {
	query["nbdevup"] = []string{value}
	return query
}
func (query BollingerBandsQuery) LowerBandStandardDeviationMultiplier(value string) BollingerBandsQuery {
	query["nbdevdn"] = []string{value}
	return query
}
func (query BollingerBandsQuery) MovingAverageType(value string) BollingerBandsQuery {
	query["matype"] = []string{value}
	return query
}
func (query BollingerBandsQuery) DataTypeCSV() BollingerBandsQuery {
	query["datatype"] = []string{"csv"}
	return query
}
func (query BollingerBandsQuery) DataTypeJSON() BollingerBandsQuery {
	query["datatype"] = []string{"json"}
	return query
}
func (query BollingerBandsQuery) DataType(value string) BollingerBandsQuery {
	query["datatype"] = []string{value}
	return query
}
func (client *Client) GetBollingerBands(ctx context.Context, q BollingerBandsQuery) (*http.Response, error) {
	req, err := client.newRequest(ctx, url.Values(q))
	if err != nil {
		return nil, err
	}
	res, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	return res, nil
}

type BollingerBandsRow struct {
	Time           string `column-name:"time"`
	RealLowerBand  string `column-name:"Real Lower Band"`
	RealMiddleBand string `column-name:"Real Middle Band"`
	RealUpperBand  string `column-name:"Real Upper Band"`
}

func (client *Client) GetBollingerBandsCSVRows(ctx context.Context, q BollingerBandsQuery) ([]BollingerBandsRow, error) {
	q.DataTypeCSV()
	res, err := client.GetBollingerBands(ctx, q)
	if err != nil {
		return nil, err
	}
	defer res.Body.Close()
	var rows []BollingerBandsRow
	err = ParseCSV(res.Body, &rows, nil)
	if err != nil {
		return nil, err
	}
	return rows, nil
}

type NormalizedAverageTrueRangeQuery url.Values

func QueryNormalizedAverageTrueRange(apiKey, symbol, interval string) NormalizedAverageTrueRangeQuery {
	return NormalizedAverageTrueRangeQuery{"function": []string{"NATR"}, "symbol": []string{symbol}, "interval": []string{interval}, "apikey": []string{apiKey}}
}
func (query NormalizedAverageTrueRangeQuery) Month(value time.Time) NormalizedAverageTrueRangeQuery {
	query["month"] = []string{value.Format("2006-01")}
	return query
}
func (query NormalizedAverageTrueRangeQuery) TimePeriod(value string) NormalizedAverageTrueRangeQuery {
	query["time_period"] = []string{value}
	return query
}
func (query NormalizedAverageTrueRangeQuery) DataTypeCSV() NormalizedAverageTrueRangeQuery {
	query["datatype"] = []string{"csv"}
	return query
}
func (query NormalizedAverageTrueRangeQuery) DataTypeJSON() NormalizedAverageTrueRangeQuery {
	query["datatype"] = []string{"json"}
	return query
}
func (query NormalizedAverageTrueRangeQuery) DataType(value string) NormalizedAverageTrueRangeQuery {
	query["datatype"] = []string{value}
	return query
}
func (client *Client) GetNormalizedAverageTrueRange(ctx context.Context, q NormalizedAverageTrueRangeQuery) (*http.Response, error) {
	req, err := client.newRequest(ctx, url.Values(q))
	if err != nil {
		return nil, err
	}
	res, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	return res, nil
}

type NormalizedAverageTrueRangeRow struct {
	Time  string `column-name:"time"`
	Value string `column-name:"NATR"`
}

func (client *Client) GetNormalizedAverageTrueRangeCSVRows(ctx context.Context, q NormalizedAverageTrueRangeQuery) ([]NormalizedAverageTrueRangeRow, error) {
	q.DataTypeCSV()
	res, err := client.GetNormalizedAverageTrueRange(ctx, q)
	if err != nil {
		return nil, err
	}
	defer res.Body.Close()
	var rows []NormalizedAverageTrueRangeRow
	err = ParseCSV(res.Body, &rows, nil)
	if err != nil {
		return nil, err
	}
	return rows, nil
}

type SARQuery url.Values

func QuerySAR(apiKey, symbol, interval string) SARQuery {
	return SARQuery{"function": []string{"SAR"}, "symbol": []string{symbol}, "interval": []string{interval}, "apikey": []string{apiKey}}
}
func (query SARQuery) Month(value time.Time) SARQuery {
	query["month"] = []string{value.Format("2006-01")}
	return query
}
func (query SARQuery) Acceleration(value string) SARQuery {
	query["acceleration"] = []string{value}
	return query
}
func (query SARQuery) Maximum(value string) SARQuery {
	query["maximum"] = []string{value}
	return query
}
func (query SARQuery) DataTypeCSV() SARQuery {
	query["datatype"] = []string{"csv"}
	return query
}
func (query SARQuery) DataTypeJSON() SARQuery {
	query["datatype"] = []string{"json"}
	return query
}
func (query SARQuery) DataType(value string) SARQuery {
	query["datatype"] = []string{value}
	return query
}
func (client *Client) GetSAR(ctx context.Context, q SARQuery) (*http.Response, error) {
	req, err := client.newRequest(ctx, url.Values(q))
	if err != nil {
		return nil, err
	}
	res, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	return res, nil
}

type SARRow struct {
	Time  string `column-name:"time"`
	Value string `column-name:"SAR"`
}

func (client *Client) GetSARCSVRows(ctx context.Context, q SARQuery) ([]SARRow, error) {
	q.DataTypeCSV()
	res, err := client.GetSAR(ctx, q)
	if err != nil {
		return nil, err
	}
	defer res.Body.Close()
	var rows []SARRow
	err = ParseCSV(res.Body, &rows, nil)
	if err != nil {
		return nil, err
	}
	return rows, nil
}

type TrueRangeQuery url.Values

func QueryTrueRange(apiKey, symbol, interval string) TrueRangeQuery {
	return TrueRangeQuery{"function": []string{"TRANGE"}, "symbol": []string{symbol}, "interval": []string{interval}, "apikey": []string{apiKey}}
}
func (query TrueRangeQuery) Month(value time.Time) TrueRangeQuery {
	query["month"] = []string{value.Format("2006-01")}
	return query
}
func (query TrueRangeQuery) DataTypeCSV() TrueRangeQuery {
	query["datatype"] = []string{"csv"}
	return query
}
func (query TrueRangeQuery) DataTypeJSON() TrueRangeQuery {
	query["datatype"] = []string{"json"}
	return query
}
func (query TrueRangeQuery) DataType(value string) TrueRangeQuery {
	query["datatype"] = []string{value}
	return query
}
func (client *Client) GetTrueRange(ctx context.Context, q TrueRangeQuery) (*http.Response, error) {
	req, err := client.newRequest(ctx, url.Values(q))
	if err != nil {
		return nil, err
	}
	res, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	return res, nil
}

type TrueRangeRow struct {
	Time  string `column-name:"time"`
	Value string `column-name:"TRANGE"`
}

func (client *Client) GetTrueRangeCSVRows(ctx context.Context, q TrueRangeQuery) ([]TrueRangeRow, error) {
	q.DataTypeCSV()
	res, err := client.GetTrueRange(ctx, q)
	if err != nil {
		return nil, err
	}
	defer res.Body.Close()
	var rows []TrueRangeRow
	err = ParseCSV(res.Body, &rows, nil)
	if err != nil {
		return nil, err
	}
	return rows, nil
}

type UltimateOscillatorQuery url.Values

func QueryUltimateOscillator(apiKey, symbol, interval string) UltimateOscillatorQuery {
	return UltimateOscillatorQuery{"function": []string{"ULTOSC"}, "symbol": []string{symbol}, "interval": []string{interval}, "apikey": []string{apiKey}}
}
func (query UltimateOscillatorQuery) Month(value time.Time) UltimateOscillatorQuery {
	query["month"] = []string{value.Format("2006-01")}
	return query
}
func (query UltimateOscillatorQuery) TimePeriod1(value string) UltimateOscillatorQuery {
	query["timeperiod1"] = []string{value}
	return query
}
func (query UltimateOscillatorQuery) TimePeriod2(value string) UltimateOscillatorQuery {
	query["timeperiod2"] = []string{value}
	return query
}
func (query UltimateOscillatorQuery) TimePeriod3(value string) UltimateOscillatorQuery {
	query["timeperiod3"] = []string{value}
	return query
}
func (query UltimateOscillatorQuery) DataTypeCSV() UltimateOscillatorQuery {
	query["datatype"] = []string{"csv"}
	return query
}
func (query UltimateOscillatorQuery) DataTypeJSON() UltimateOscillatorQuery {
	query["datatype"] = []string{"json"}
	return query
}
func (query UltimateOscillatorQuery) DataType(value string) UltimateOscillatorQuery {
	query["datatype"] = []string{value}
	return query
}
func (client *Client) GetUltimateOscillator(ctx context.Context, q UltimateOscillatorQuery) (*http.Response, error) {
	req, err := client.newRequest(ctx, url.Values(q))
	if err != nil {
		return nil, err
	}
	res, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	return res, nil
}

type UltimateOscillatorRow struct {
	Time  string `column-name:"time"`
	Value string `column-name:"ULTOSC"`
}

func (client *Client) GetUltimateOscillatorCSVRows(ctx context.Context, q UltimateOscillatorQuery) ([]UltimateOscillatorRow, error) {
	q.DataTypeCSV()
	res, err := client.GetUltimateOscillator(ctx, q)
	if err != nil {
		return nil, err
	}
	defer res.Body.Close()
	var rows []UltimateOscillatorRow
	err = ParseCSV(res.Body, &rows, nil)
	if err != nil {
		return nil, err
	}
	return rows, nil
}
