// Code generated by av-generate; DO NOT EDIT.

package alphavantage

import (
	"context"
	"github.com/portfoliotree/alphavantage/api"
	"net/http"
	"net/url"
	"time"
)

type AroonQuery url.Values

func QueryAroon(apiKey, symbol, interval string) AroonQuery {
	return AroonQuery{"function": []string{"AROON"}, "symbol": []string{symbol}, "interval": []string{interval}, "apikey": []string{apiKey}}
}

func (query AroonQuery) Month(value time.Time) AroonQuery {
	query["month"] = []string{value.Format("2006-01")}
	return query
}

func (query AroonQuery) TimePeriod(value string) AroonQuery {
	query["time_period"] = []string{value}
	return query
}

func (query AroonQuery) DataTypeCSV() AroonQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query AroonQuery) DataTypeJSON() AroonQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query AroonQuery) DataType(value string) AroonQuery {
	query["datatype"] = []string{value}
	return query
}

func (q AroonQuery) DoWith(ctx context.Context, client Doer) (*http.Response, error) {
	return api.DoQuery(ctx, client, url.Values(q))
}

type AroonRow struct {
	Time      string `column-name:"time"`
	AroonDown string `column-name:"Aroon Down"`
	AroonUp   string `column-name:"Aroon Up"`
}

func (q AroonQuery) CSVRows(ctx context.Context, client Doer) ([]AroonRow, error) {
	q.DataTypeCSV()
	return api.RequestCSVRows(ctx, client, q)
}

type AroonOscQuery url.Values

func QueryAroonOsc(apiKey, symbol, interval string) AroonOscQuery {
	return AroonOscQuery{"function": []string{"AROONOSC"}, "symbol": []string{symbol}, "interval": []string{interval}, "apikey": []string{apiKey}}
}

func (query AroonOscQuery) Month(value time.Time) AroonOscQuery {
	query["month"] = []string{value.Format("2006-01")}
	return query
}

func (query AroonOscQuery) TimePeriod(value string) AroonOscQuery {
	query["time_period"] = []string{value}
	return query
}

func (query AroonOscQuery) DataTypeCSV() AroonOscQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query AroonOscQuery) DataTypeJSON() AroonOscQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query AroonOscQuery) DataType(value string) AroonOscQuery {
	query["datatype"] = []string{value}
	return query
}

func (q AroonOscQuery) DoWith(ctx context.Context, client Doer) (*http.Response, error) {
	return api.DoQuery(ctx, client, url.Values(q))
}

type AroonOscRow struct {
	Time  string `column-name:"time"`
	Value string `column-name:"AROONOSC"`
}

func (q AroonOscQuery) CSVRows(ctx context.Context, client Doer) ([]AroonOscRow, error) {
	q.DataTypeCSV()
	return api.RequestCSVRows(ctx, client, q)
}

type AverageDirectionalMovementIndexQuery url.Values

func QueryAverageDirectionalMovementIndex(apiKey, symbol, interval string) AverageDirectionalMovementIndexQuery {
	return AverageDirectionalMovementIndexQuery{"function": []string{"ADX"}, "symbol": []string{symbol}, "interval": []string{interval}, "apikey": []string{apiKey}}
}

func (query AverageDirectionalMovementIndexQuery) Month(value time.Time) AverageDirectionalMovementIndexQuery {
	query["month"] = []string{value.Format("2006-01")}
	return query
}

func (query AverageDirectionalMovementIndexQuery) TimePeriod(value string) AverageDirectionalMovementIndexQuery {
	query["time_period"] = []string{value}
	return query
}

func (query AverageDirectionalMovementIndexQuery) DataTypeCSV() AverageDirectionalMovementIndexQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query AverageDirectionalMovementIndexQuery) DataTypeJSON() AverageDirectionalMovementIndexQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query AverageDirectionalMovementIndexQuery) DataType(value string) AverageDirectionalMovementIndexQuery {
	query["datatype"] = []string{value}
	return query
}

func (q AverageDirectionalMovementIndexQuery) DoWith(ctx context.Context, client Doer) (*http.Response, error) {
	return api.DoQuery(ctx, client, url.Values(q))
}

type AverageDirectionalMovementIndexRow struct {
	Time  string `column-name:"time"`
	Value string `column-name:"ADX"`
}

func (q AverageDirectionalMovementIndexQuery) CSVRows(ctx context.Context, client Doer) ([]AverageDirectionalMovementIndexRow, error) {
	q.DataTypeCSV()
	return api.RequestCSVRows(ctx, client, q)
}

type AverageDirectionalMovementIndexRatingQuery url.Values

func QueryAverageDirectionalMovementIndexRating(apiKey, symbol, interval string) AverageDirectionalMovementIndexRatingQuery {
	return AverageDirectionalMovementIndexRatingQuery{"function": []string{"ADXR"}, "symbol": []string{symbol}, "interval": []string{interval}, "apikey": []string{apiKey}}
}

func (query AverageDirectionalMovementIndexRatingQuery) Month(value time.Time) AverageDirectionalMovementIndexRatingQuery {
	query["month"] = []string{value.Format("2006-01")}
	return query
}

func (query AverageDirectionalMovementIndexRatingQuery) TimePeriod(value string) AverageDirectionalMovementIndexRatingQuery {
	query["time_period"] = []string{value}
	return query
}

func (query AverageDirectionalMovementIndexRatingQuery) DataTypeCSV() AverageDirectionalMovementIndexRatingQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query AverageDirectionalMovementIndexRatingQuery) DataTypeJSON() AverageDirectionalMovementIndexRatingQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query AverageDirectionalMovementIndexRatingQuery) DataType(value string) AverageDirectionalMovementIndexRatingQuery {
	query["datatype"] = []string{value}
	return query
}

func (q AverageDirectionalMovementIndexRatingQuery) DoWith(ctx context.Context, client Doer) (*http.Response, error) {
	return api.DoQuery(ctx, client, url.Values(q))
}

type AverageDirectionalMovementIndexRatingRow struct {
	Time  string `column-name:"time"`
	Value string `column-name:"ADXR"`
}

func (q AverageDirectionalMovementIndexRatingQuery) CSVRows(ctx context.Context, client Doer) ([]AverageDirectionalMovementIndexRatingRow, error) {
	q.DataTypeCSV()
	return api.RequestCSVRows(ctx, client, q)
}

type DirectionalMovementIndexQuery url.Values

func QueryDirectionalMovementIndex(apiKey, symbol, interval string) DirectionalMovementIndexQuery {
	return DirectionalMovementIndexQuery{"function": []string{"DX"}, "symbol": []string{symbol}, "interval": []string{interval}, "apikey": []string{apiKey}}
}

func (query DirectionalMovementIndexQuery) Month(value time.Time) DirectionalMovementIndexQuery {
	query["month"] = []string{value.Format("2006-01")}
	return query
}

func (query DirectionalMovementIndexQuery) TimePeriod(value string) DirectionalMovementIndexQuery {
	query["time_period"] = []string{value}
	return query
}

func (query DirectionalMovementIndexQuery) DataTypeCSV() DirectionalMovementIndexQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query DirectionalMovementIndexQuery) DataTypeJSON() DirectionalMovementIndexQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query DirectionalMovementIndexQuery) DataType(value string) DirectionalMovementIndexQuery {
	query["datatype"] = []string{value}
	return query
}

func (q DirectionalMovementIndexQuery) DoWith(ctx context.Context, client Doer) (*http.Response, error) {
	return api.DoQuery(ctx, client, url.Values(q))
}

type DirectionalMovementIndexRow struct {
	Time  string `column-name:"time"`
	Value string `column-name:"DX"`
}

func (q DirectionalMovementIndexQuery) CSVRows(ctx context.Context, client Doer) ([]DirectionalMovementIndexRow, error) {
	q.DataTypeCSV()
	return api.RequestCSVRows(ctx, client, q)
}

type MinusDirectionalIndicatorQuery url.Values

func QueryMinusDirectionalIndicator(apiKey, symbol, interval string) MinusDirectionalIndicatorQuery {
	return MinusDirectionalIndicatorQuery{"function": []string{"MINUS_DI"}, "symbol": []string{symbol}, "interval": []string{interval}, "apikey": []string{apiKey}}
}

func (query MinusDirectionalIndicatorQuery) Month(value time.Time) MinusDirectionalIndicatorQuery {
	query["month"] = []string{value.Format("2006-01")}
	return query
}

func (query MinusDirectionalIndicatorQuery) TimePeriod(value string) MinusDirectionalIndicatorQuery {
	query["time_period"] = []string{value}
	return query
}

func (query MinusDirectionalIndicatorQuery) DataTypeCSV() MinusDirectionalIndicatorQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query MinusDirectionalIndicatorQuery) DataTypeJSON() MinusDirectionalIndicatorQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query MinusDirectionalIndicatorQuery) DataType(value string) MinusDirectionalIndicatorQuery {
	query["datatype"] = []string{value}
	return query
}

func (q MinusDirectionalIndicatorQuery) DoWith(ctx context.Context, client Doer) (*http.Response, error) {
	return api.DoQuery(ctx, client, url.Values(q))
}

type MinusDirectionalIndicatorRow struct {
	Time  string `column-name:"time"`
	Value string `column-name:"MINUS_DI"`
}

func (q MinusDirectionalIndicatorQuery) CSVRows(ctx context.Context, client Doer) ([]MinusDirectionalIndicatorRow, error) {
	q.DataTypeCSV()
	return api.RequestCSVRows(ctx, client, q)
}

type MinusDirectionalMovementQuery url.Values

func QueryMinusDirectionalMovement(apiKey, symbol, interval string) MinusDirectionalMovementQuery {
	return MinusDirectionalMovementQuery{"function": []string{"MINUS_DM"}, "symbol": []string{symbol}, "interval": []string{interval}, "apikey": []string{apiKey}}
}

func (query MinusDirectionalMovementQuery) Month(value time.Time) MinusDirectionalMovementQuery {
	query["month"] = []string{value.Format("2006-01")}
	return query
}

func (query MinusDirectionalMovementQuery) TimePeriod(value string) MinusDirectionalMovementQuery {
	query["time_period"] = []string{value}
	return query
}

func (query MinusDirectionalMovementQuery) DataTypeCSV() MinusDirectionalMovementQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query MinusDirectionalMovementQuery) DataTypeJSON() MinusDirectionalMovementQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query MinusDirectionalMovementQuery) DataType(value string) MinusDirectionalMovementQuery {
	query["datatype"] = []string{value}
	return query
}

func (q MinusDirectionalMovementQuery) DoWith(ctx context.Context, client Doer) (*http.Response, error) {
	return api.DoQuery(ctx, client, url.Values(q))
}

type MinusDirectionalMovementRow struct {
	Time  string `column-name:"time"`
	Value string `column-name:"MINUS_DM"`
}

func (q MinusDirectionalMovementQuery) CSVRows(ctx context.Context, client Doer) ([]MinusDirectionalMovementRow, error) {
	q.DataTypeCSV()
	return api.RequestCSVRows(ctx, client, q)
}

type PlusDirectionalIndicatorQuery url.Values

func QueryPlusDirectionalIndicator(apiKey, symbol, interval string) PlusDirectionalIndicatorQuery {
	return PlusDirectionalIndicatorQuery{"function": []string{"PLUS_DI"}, "symbol": []string{symbol}, "interval": []string{interval}, "apikey": []string{apiKey}}
}

func (query PlusDirectionalIndicatorQuery) Month(value time.Time) PlusDirectionalIndicatorQuery {
	query["month"] = []string{value.Format("2006-01")}
	return query
}

func (query PlusDirectionalIndicatorQuery) TimePeriod(value string) PlusDirectionalIndicatorQuery {
	query["time_period"] = []string{value}
	return query
}

func (query PlusDirectionalIndicatorQuery) DataTypeCSV() PlusDirectionalIndicatorQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query PlusDirectionalIndicatorQuery) DataTypeJSON() PlusDirectionalIndicatorQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query PlusDirectionalIndicatorQuery) DataType(value string) PlusDirectionalIndicatorQuery {
	query["datatype"] = []string{value}
	return query
}

func (q PlusDirectionalIndicatorQuery) DoWith(ctx context.Context, client Doer) (*http.Response, error) {
	return api.DoQuery(ctx, client, url.Values(q))
}

type PlusDirectionalIndicatorRow struct {
	Time  string `column-name:"time"`
	Value string `column-name:"PLUS_DI"`
}

func (q PlusDirectionalIndicatorQuery) CSVRows(ctx context.Context, client Doer) ([]PlusDirectionalIndicatorRow, error) {
	q.DataTypeCSV()
	return api.RequestCSVRows(ctx, client, q)
}

type PlusDirectionalMovementQuery url.Values

func QueryPlusDirectionalMovement(apiKey, symbol, interval string) PlusDirectionalMovementQuery {
	return PlusDirectionalMovementQuery{"function": []string{"PLUS_DM"}, "symbol": []string{symbol}, "interval": []string{interval}, "apikey": []string{apiKey}}
}

func (query PlusDirectionalMovementQuery) Month(value time.Time) PlusDirectionalMovementQuery {
	query["month"] = []string{value.Format("2006-01")}
	return query
}

func (query PlusDirectionalMovementQuery) TimePeriod(value string) PlusDirectionalMovementQuery {
	query["time_period"] = []string{value}
	return query
}

func (query PlusDirectionalMovementQuery) DataTypeCSV() PlusDirectionalMovementQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query PlusDirectionalMovementQuery) DataTypeJSON() PlusDirectionalMovementQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query PlusDirectionalMovementQuery) DataType(value string) PlusDirectionalMovementQuery {
	query["datatype"] = []string{value}
	return query
}

func (q PlusDirectionalMovementQuery) DoWith(ctx context.Context, client Doer) (*http.Response, error) {
	return api.DoQuery(ctx, client, url.Values(q))
}

type PlusDirectionalMovementRow struct {
	Time  string `column-name:"time"`
	Value string `column-name:"PLUS_DM"`
}

func (q PlusDirectionalMovementQuery) CSVRows(ctx context.Context, client Doer) ([]PlusDirectionalMovementRow, error) {
	q.DataTypeCSV()
	return api.RequestCSVRows(ctx, client, q)
}
