// Code generated by github.com/portfoliotree/alphavantage/cmd/generate; DO NOT EDIT.
package alphavantage

import (
	"context"
	"net/http"
	"net/url"
	"time"
)

type HilbertTransformDCPeriodQuery url.Values

func QueryHilbertTransformDCPeriod(apiKey, symbol, interval, seriesType string) HilbertTransformDCPeriodQuery {
	return HilbertTransformDCPeriodQuery{"function": []string{"HT_DCPERIOD"}, "symbol": []string{symbol}, "interval": []string{interval}, "series_type": []string{seriesType}, "apikey": []string{apiKey}}
}
func (query HilbertTransformDCPeriodQuery) Month(value time.Time) HilbertTransformDCPeriodQuery {
	query["month"] = []string{value.Format("2006-01")}
	return query
}
func (query HilbertTransformDCPeriodQuery) DataTypeCSV() HilbertTransformDCPeriodQuery {
	query["datatype"] = []string{"csv"}
	return query
}
func (query HilbertTransformDCPeriodQuery) DataTypeJSON() HilbertTransformDCPeriodQuery {
	query["datatype"] = []string{"json"}
	return query
}
func (query HilbertTransformDCPeriodQuery) DataType(value string) HilbertTransformDCPeriodQuery {
	query["datatype"] = []string{value}
	return query
}
func (client *Client) GetHilbertTransformDCPeriod(ctx context.Context, q HilbertTransformDCPeriodQuery) (*http.Response, error) {
	req, err := client.newRequest(ctx, url.Values(q))
	if err != nil {
		return nil, err
	}
	res, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	return res, nil
}

type HilbertTransformDCPeriodRow struct {
	Time  string `column-name:"time"`
	Value string `column-name:"DCPERIOD"`
}

func (client *Client) GetHilbertTransformDCPeriodCSVRows(ctx context.Context, q HilbertTransformDCPeriodQuery) ([]HilbertTransformDCPeriodRow, error) {
	q.DataTypeCSV()
	res, err := client.GetHilbertTransformDCPeriod(ctx, q)
	if err != nil {
		return nil, err
	}
	defer res.Body.Close()
	var rows []HilbertTransformDCPeriodRow
	err = ParseCSV(res.Body, &rows, nil)
	if err != nil {
		return nil, err
	}
	return rows, nil
}

type HilbertTransformDCPhaseQuery url.Values

func QueryHilbertTransformDCPhase(apiKey, symbol, interval, seriesType string) HilbertTransformDCPhaseQuery {
	return HilbertTransformDCPhaseQuery{"function": []string{"HT_DCPHASE"}, "symbol": []string{symbol}, "interval": []string{interval}, "series_type": []string{seriesType}, "apikey": []string{apiKey}}
}
func (query HilbertTransformDCPhaseQuery) Month(value time.Time) HilbertTransformDCPhaseQuery {
	query["month"] = []string{value.Format("2006-01")}
	return query
}
func (query HilbertTransformDCPhaseQuery) DataTypeCSV() HilbertTransformDCPhaseQuery {
	query["datatype"] = []string{"csv"}
	return query
}
func (query HilbertTransformDCPhaseQuery) DataTypeJSON() HilbertTransformDCPhaseQuery {
	query["datatype"] = []string{"json"}
	return query
}
func (query HilbertTransformDCPhaseQuery) DataType(value string) HilbertTransformDCPhaseQuery {
	query["datatype"] = []string{value}
	return query
}
func (client *Client) GetHilbertTransformDCPhase(ctx context.Context, q HilbertTransformDCPhaseQuery) (*http.Response, error) {
	req, err := client.newRequest(ctx, url.Values(q))
	if err != nil {
		return nil, err
	}
	res, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	return res, nil
}

type HilbertTransformDCPhaseRow struct {
	Time  string `column-name:"time"`
	Value string `column-name:"HT_DCPHASE"`
}

func (client *Client) GetHilbertTransformDCPhaseCSVRows(ctx context.Context, q HilbertTransformDCPhaseQuery) ([]HilbertTransformDCPhaseRow, error) {
	q.DataTypeCSV()
	res, err := client.GetHilbertTransformDCPhase(ctx, q)
	if err != nil {
		return nil, err
	}
	defer res.Body.Close()
	var rows []HilbertTransformDCPhaseRow
	err = ParseCSV(res.Body, &rows, nil)
	if err != nil {
		return nil, err
	}
	return rows, nil
}

type HilbertTransformPhasorQuery url.Values

func QueryHilbertTransformPhasor(apiKey, symbol, interval, seriesType string) HilbertTransformPhasorQuery {
	return HilbertTransformPhasorQuery{"function": []string{"HT_PHASOR"}, "symbol": []string{symbol}, "interval": []string{interval}, "series_type": []string{seriesType}, "apikey": []string{apiKey}}
}
func (query HilbertTransformPhasorQuery) Month(value time.Time) HilbertTransformPhasorQuery {
	query["month"] = []string{value.Format("2006-01")}
	return query
}
func (query HilbertTransformPhasorQuery) DataTypeCSV() HilbertTransformPhasorQuery {
	query["datatype"] = []string{"csv"}
	return query
}
func (query HilbertTransformPhasorQuery) DataTypeJSON() HilbertTransformPhasorQuery {
	query["datatype"] = []string{"json"}
	return query
}
func (query HilbertTransformPhasorQuery) DataType(value string) HilbertTransformPhasorQuery {
	query["datatype"] = []string{value}
	return query
}
func (client *Client) GetHilbertTransformPhasor(ctx context.Context, q HilbertTransformPhasorQuery) (*http.Response, error) {
	req, err := client.newRequest(ctx, url.Values(q))
	if err != nil {
		return nil, err
	}
	res, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	return res, nil
}

type HilbertTransformPhasorRow struct {
	Time       string `column-name:"time"`
	Phase      string `column-name:"PHASE"`
	Quadrature string `column-name:"QUADRATURE"`
}

func (client *Client) GetHilbertTransformPhasorCSVRows(ctx context.Context, q HilbertTransformPhasorQuery) ([]HilbertTransformPhasorRow, error) {
	q.DataTypeCSV()
	res, err := client.GetHilbertTransformPhasor(ctx, q)
	if err != nil {
		return nil, err
	}
	defer res.Body.Close()
	var rows []HilbertTransformPhasorRow
	err = ParseCSV(res.Body, &rows, nil)
	if err != nil {
		return nil, err
	}
	return rows, nil
}

type HilbertTransformSineQuery url.Values

func QueryHilbertTransformSine(apiKey, symbol, interval, seriesType string) HilbertTransformSineQuery {
	return HilbertTransformSineQuery{"function": []string{"HT_SINE"}, "symbol": []string{symbol}, "interval": []string{interval}, "series_type": []string{seriesType}, "apikey": []string{apiKey}}
}
func (query HilbertTransformSineQuery) Month(value time.Time) HilbertTransformSineQuery {
	query["month"] = []string{value.Format("2006-01")}
	return query
}
func (query HilbertTransformSineQuery) DataTypeCSV() HilbertTransformSineQuery {
	query["datatype"] = []string{"csv"}
	return query
}
func (query HilbertTransformSineQuery) DataTypeJSON() HilbertTransformSineQuery {
	query["datatype"] = []string{"json"}
	return query
}
func (query HilbertTransformSineQuery) DataType(value string) HilbertTransformSineQuery {
	query["datatype"] = []string{value}
	return query
}
func (client *Client) GetHilbertTransformSine(ctx context.Context, q HilbertTransformSineQuery) (*http.Response, error) {
	req, err := client.newRequest(ctx, url.Values(q))
	if err != nil {
		return nil, err
	}
	res, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	return res, nil
}

type HilbertTransformSineRow struct {
	Time     string `column-name:"time"`
	LeadSine string `column-name:"LEAD SINE"`
	Sine     string `column-name:"SINE"`
}

func (client *Client) GetHilbertTransformSineCSVRows(ctx context.Context, q HilbertTransformSineQuery) ([]HilbertTransformSineRow, error) {
	q.DataTypeCSV()
	res, err := client.GetHilbertTransformSine(ctx, q)
	if err != nil {
		return nil, err
	}
	defer res.Body.Close()
	var rows []HilbertTransformSineRow
	err = ParseCSV(res.Body, &rows, nil)
	if err != nil {
		return nil, err
	}
	return rows, nil
}

type HilbertTransformTrendLineQuery url.Values

func QueryHilbertTransformTrendLine(apiKey, symbol, interval, seriesType string) HilbertTransformTrendLineQuery {
	return HilbertTransformTrendLineQuery{"function": []string{"HT_TRENDLINE"}, "symbol": []string{symbol}, "interval": []string{interval}, "series_type": []string{seriesType}, "apikey": []string{apiKey}}
}
func (query HilbertTransformTrendLineQuery) Month(value time.Time) HilbertTransformTrendLineQuery {
	query["month"] = []string{value.Format("2006-01")}
	return query
}
func (query HilbertTransformTrendLineQuery) DataTypeCSV() HilbertTransformTrendLineQuery {
	query["datatype"] = []string{"csv"}
	return query
}
func (query HilbertTransformTrendLineQuery) DataTypeJSON() HilbertTransformTrendLineQuery {
	query["datatype"] = []string{"json"}
	return query
}
func (query HilbertTransformTrendLineQuery) DataType(value string) HilbertTransformTrendLineQuery {
	query["datatype"] = []string{value}
	return query
}
func (client *Client) GetHilbertTransformTrendLine(ctx context.Context, q HilbertTransformTrendLineQuery) (*http.Response, error) {
	req, err := client.newRequest(ctx, url.Values(q))
	if err != nil {
		return nil, err
	}
	res, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	return res, nil
}

type HilbertTransformTrendLineRow struct {
	Time  string `column-name:"time"`
	Value string `column-name:"HT_TRENDLINE"`
}

func (client *Client) GetHilbertTransformTrendLineCSVRows(ctx context.Context, q HilbertTransformTrendLineQuery) ([]HilbertTransformTrendLineRow, error) {
	q.DataTypeCSV()
	res, err := client.GetHilbertTransformTrendLine(ctx, q)
	if err != nil {
		return nil, err
	}
	defer res.Body.Close()
	var rows []HilbertTransformTrendLineRow
	err = ParseCSV(res.Body, &rows, nil)
	if err != nil {
		return nil, err
	}
	return rows, nil
}

type HilbertTransformTrendModeQuery url.Values

func QueryHilbertTransformTrendMode(apiKey, symbol, interval, seriesType string) HilbertTransformTrendModeQuery {
	return HilbertTransformTrendModeQuery{"function": []string{"HT_TRENDMODE"}, "symbol": []string{symbol}, "interval": []string{interval}, "series_type": []string{seriesType}, "apikey": []string{apiKey}}
}
func (query HilbertTransformTrendModeQuery) Month(value time.Time) HilbertTransformTrendModeQuery {
	query["month"] = []string{value.Format("2006-01")}
	return query
}
func (query HilbertTransformTrendModeQuery) DataTypeCSV() HilbertTransformTrendModeQuery {
	query["datatype"] = []string{"csv"}
	return query
}
func (query HilbertTransformTrendModeQuery) DataTypeJSON() HilbertTransformTrendModeQuery {
	query["datatype"] = []string{"json"}
	return query
}
func (query HilbertTransformTrendModeQuery) DataType(value string) HilbertTransformTrendModeQuery {
	query["datatype"] = []string{value}
	return query
}
func (client *Client) GetHilbertTransformTrendMode(ctx context.Context, q HilbertTransformTrendModeQuery) (*http.Response, error) {
	req, err := client.newRequest(ctx, url.Values(q))
	if err != nil {
		return nil, err
	}
	res, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	return res, nil
}

type HilbertTransformTrendModeRow struct {
	Time  string `column-name:"time"`
	Value string `column-name:"TRENDMODE"`
}

func (client *Client) GetHilbertTransformTrendModeCSVRows(ctx context.Context, q HilbertTransformTrendModeQuery) ([]HilbertTransformTrendModeRow, error) {
	q.DataTypeCSV()
	res, err := client.GetHilbertTransformTrendMode(ctx, q)
	if err != nil {
		return nil, err
	}
	defer res.Body.Close()
	var rows []HilbertTransformTrendModeRow
	err = ParseCSV(res.Body, &rows, nil)
	if err != nil {
		return nil, err
	}
	return rows, nil
}
