// Code generated by github.com/portfoliotree/alphavantage/cmd/generate; DO NOT EDIT.

package alphavantage

import (
	"context"
	"net/http"
	"net/url"
	"time"
)

type MidPointQuery url.Values

func QueryMidPoint(apiKey, symbol, interval, timePeriod, seriesType string) MidPointQuery {
	return MidPointQuery{"function": []string{"MIDPOINT"}, "symbol": []string{symbol}, "interval": []string{interval}, "time_period": []string{timePeriod}, "series_type": []string{seriesType}, "apikey": []string{apiKey}}
}
func (query MidPointQuery) Month(value time.Time) MidPointQuery {
	query["month"] = []string{value.Format("2006-01")}
	return query
}
func (query MidPointQuery) DataTypeCSV() MidPointQuery {
	query["datatype"] = []string{"csv"}
	return query
}
func (query MidPointQuery) DataTypeJSON() MidPointQuery {
	query["datatype"] = []string{"json"}
	return query
}
func (query MidPointQuery) DataType(value string) MidPointQuery {
	query["datatype"] = []string{value}
	return query
}
func (client *Client) GetMidPoint(ctx context.Context, q MidPointQuery) (*http.Response, error) {
	req, err := client.newRequest(ctx, url.Values(q))
	if err != nil {
		return nil, err
	}
	res, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	return res, nil
}

type MidPointRow struct {
	Time  string `column-name:"time"`
	Value string `column-name:"MIDPOINT"`
}

func (client *Client) GetMidPointCSVRows(ctx context.Context, q MidPointQuery) ([]MidPointRow, error) {
	q.DataTypeCSV()
	res, err := client.GetMidPoint(ctx, q)
	if err != nil {
		return nil, err
	}
	defer res.Body.Close()
	var rows []MidPointRow
	err = ParseCSV(res.Body, &rows, nil)
	if err != nil {
		return nil, err
	}
	return rows, nil
}

type MidPriceQuery url.Values

func QueryMidPrice(apiKey, symbol, interval, timePeriod string) MidPriceQuery {
	return MidPriceQuery{"function": []string{"MIDPRICE"}, "symbol": []string{symbol}, "interval": []string{interval}, "time_period": []string{timePeriod}, "apikey": []string{apiKey}}
}
func (query MidPriceQuery) Month(value time.Time) MidPriceQuery {
	query["month"] = []string{value.Format("2006-01")}
	return query
}
func (query MidPriceQuery) DataTypeCSV() MidPriceQuery {
	query["datatype"] = []string{"csv"}
	return query
}
func (query MidPriceQuery) DataTypeJSON() MidPriceQuery {
	query["datatype"] = []string{"json"}
	return query
}
func (query MidPriceQuery) DataType(value string) MidPriceQuery {
	query["datatype"] = []string{value}
	return query
}
func (client *Client) GetMidPrice(ctx context.Context, q MidPriceQuery) (*http.Response, error) {
	req, err := client.newRequest(ctx, url.Values(q))
	if err != nil {
		return nil, err
	}
	res, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	return res, nil
}

type MidPriceRow struct {
	Time  string `column-name:"time"`
	Value string `column-name:"MIDPRICE"`
}

func (client *Client) GetMidPriceCSVRows(ctx context.Context, q MidPriceQuery) ([]MidPriceRow, error) {
	q.DataTypeCSV()
	res, err := client.GetMidPrice(ctx, q)
	if err != nil {
		return nil, err
	}
	defer res.Body.Close()
	var rows []MidPriceRow
	err = ParseCSV(res.Body, &rows, nil)
	if err != nil {
		return nil, err
	}
	return rows, nil
}
