// Code generated by av-generate; DO NOT EDIT.

package alphavantage

import (
	"context"
	"github.com/portfoliotree/alphavantage/api"
	"net/http"
	"net/url"
	"strconv"
	"time"
)

type GlobalQuoteQuery url.Values

func QueryGlobalQuote(apiKey, symbol string) GlobalQuoteQuery {
	return GlobalQuoteQuery{"function": []string{"GLOBAL_QUOTE"}, "symbol": []string{symbol}, "apikey": []string{apiKey}}
}

func (query GlobalQuoteQuery) DataTypeCSV() GlobalQuoteQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query GlobalQuoteQuery) DataTypeJSON() GlobalQuoteQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query GlobalQuoteQuery) DataType(value string) GlobalQuoteQuery {
	query["datatype"] = []string{value}
	return query
}

func (q GlobalQuoteQuery) DoWith(ctx context.Context, client Doer) (*http.Response, error) {
	return api.DoQuery(ctx, client, url.Values(q))
}

type GlobalQuoteRow struct {
	Symbol        string `column-name:"symbol"`
	Open          string `column-name:"open"`
	High          string `column-name:"high"`
	Low           string `column-name:"low"`
	Price         string `column-name:"price"`
	Volume        string `column-name:"volume"`
	LatestDay     string `column-name:"latestDay"`
	PreviousClose string `column-name:"previousClose"`
	Change        string `column-name:"change"`
	ChangePercent string `column-name:"changePercent"`
}

func (q GlobalQuoteQuery) CSVRows(ctx context.Context, client Doer) ([]GlobalQuoteRow, error) {
	q.DataTypeCSV()
	return api.RequestCSVRows(ctx, client, q)
}

type MarketStatusQuery url.Values

func QueryMarketStatus(apiKey string) MarketStatusQuery {
	return MarketStatusQuery{"function": []string{"MARKET_STATUS"}, "apikey": []string{apiKey}}
}

func (q MarketStatusQuery) DoWith(ctx context.Context, client Doer) (*http.Response, error) {
	return api.DoQuery(ctx, client, url.Values(q))
}

type RealtimeBulkQuotesQuery url.Values

func QueryRealtimeBulkQuotes(apiKey, symbol string) RealtimeBulkQuotesQuery {
	return RealtimeBulkQuotesQuery{"function": []string{"REALTIME_BULK_QUOTES"}, "symbol": []string{symbol}, "apikey": []string{apiKey}}
}

func (query RealtimeBulkQuotesQuery) DataTypeCSV() RealtimeBulkQuotesQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query RealtimeBulkQuotesQuery) DataTypeJSON() RealtimeBulkQuotesQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query RealtimeBulkQuotesQuery) DataType(value string) RealtimeBulkQuotesQuery {
	query["datatype"] = []string{value}
	return query
}

func (q RealtimeBulkQuotesQuery) DoWith(ctx context.Context, client Doer) (*http.Response, error) {
	return api.DoQuery(ctx, client, url.Values(q))
}

type SymbolSearchQuery url.Values

func QuerySymbolSearch(apiKey, keywords string) SymbolSearchQuery {
	return SymbolSearchQuery{"function": []string{"SYMBOL_SEARCH"}, "keywords": []string{keywords}, "apikey": []string{apiKey}}
}

func (query SymbolSearchQuery) DataTypeCSV() SymbolSearchQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query SymbolSearchQuery) DataTypeJSON() SymbolSearchQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query SymbolSearchQuery) DataType(value string) SymbolSearchQuery {
	query["datatype"] = []string{value}
	return query
}

func (q SymbolSearchQuery) DoWith(ctx context.Context, client Doer) (*http.Response, error) {
	return api.DoQuery(ctx, client, url.Values(q))
}

type SymbolSearchRow struct {
	Symbol      string  `column-name:"symbol"`
	Name        string  `column-name:"name"`
	Type        string  `column-name:"type"`
	Region      string  `column-name:"region"`
	MarketOpen  string  `column-name:"marketOpen"`
	MarketClose string  `column-name:"marketClose"`
	TimeZone    string  `column-name:"timezone"`
	Currency    string  `column-name:"currency"`
	MatchScore  float64 `column-name:"matchScore"`
}

func (q SymbolSearchQuery) CSVRows(ctx context.Context, client Doer) ([]SymbolSearchRow, error) {
	q.DataTypeCSV()
	return api.RequestCSVRows(ctx, client, q)
}

type TimeSeriesDailyQuery url.Values

func QueryTimeSeriesDaily(apiKey, symbol string) TimeSeriesDailyQuery {
	return TimeSeriesDailyQuery{"function": []string{"TIME_SERIES_DAILY"}, "symbol": []string{symbol}, "apikey": []string{apiKey}}
}

func (query TimeSeriesDailyQuery) OutputSizeCompact() TimeSeriesDailyQuery {
	query["outputsize"] = []string{"compact"}
	return query
}

func (query TimeSeriesDailyQuery) OutputSizeFull() TimeSeriesDailyQuery {
	query["outputsize"] = []string{"full"}
	return query
}

func (query TimeSeriesDailyQuery) OutputSize(value string) TimeSeriesDailyQuery {
	query["outputsize"] = []string{value}
	return query
}

func (query TimeSeriesDailyQuery) DataTypeCSV() TimeSeriesDailyQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query TimeSeriesDailyQuery) DataTypeJSON() TimeSeriesDailyQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query TimeSeriesDailyQuery) DataType(value string) TimeSeriesDailyQuery {
	query["datatype"] = []string{value}
	return query
}

func (q TimeSeriesDailyQuery) DoWith(ctx context.Context, client Doer) (*http.Response, error) {
	return api.DoQuery(ctx, client, url.Values(q))
}

type TimeSeriesDailyRow struct {
	TimeStamp time.Time `column-name:"timestamp" time-layout:"2006-01-02"`
	Open      float64   `column-name:"open"`
	High      float64   `column-name:"high"`
	Low       float64   `column-name:"low"`
	Close     float64   `column-name:"close"`
	Volume    int       `column-name:"volume"`
}

func (q TimeSeriesDailyQuery) CSVRows(ctx context.Context, client Doer) ([]TimeSeriesDailyRow, error) {
	q.DataTypeCSV()
	return api.RequestCSVRows(ctx, client, q)
}

type TimeSeriesDailyAdjustedQuery url.Values

func QueryTimeSeriesDailyAdjusted(apiKey, symbol string) TimeSeriesDailyAdjustedQuery {
	return TimeSeriesDailyAdjustedQuery{"function": []string{"TIME_SERIES_DAILY_ADJUSTED"}, "symbol": []string{symbol}, "apikey": []string{apiKey}}
}

func (query TimeSeriesDailyAdjustedQuery) OutputSizeCompact() TimeSeriesDailyAdjustedQuery {
	query["outputsize"] = []string{"compact"}
	return query
}

func (query TimeSeriesDailyAdjustedQuery) OutputSizeFull() TimeSeriesDailyAdjustedQuery {
	query["outputsize"] = []string{"full"}
	return query
}

func (query TimeSeriesDailyAdjustedQuery) OutputSize(value string) TimeSeriesDailyAdjustedQuery {
	query["outputsize"] = []string{value}
	return query
}

func (query TimeSeriesDailyAdjustedQuery) DataTypeCSV() TimeSeriesDailyAdjustedQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query TimeSeriesDailyAdjustedQuery) DataTypeJSON() TimeSeriesDailyAdjustedQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query TimeSeriesDailyAdjustedQuery) DataType(value string) TimeSeriesDailyAdjustedQuery {
	query["datatype"] = []string{value}
	return query
}

func (q TimeSeriesDailyAdjustedQuery) DoWith(ctx context.Context, client Doer) (*http.Response, error) {
	return api.DoQuery(ctx, client, url.Values(q))
}

type TimeSeriesDailyAdjustedRow struct {
	TimeStamp        time.Time `column-name:"timestamp" time-layout:"2006-01-02"`
	Open             float64   `column-name:"open"`
	High             float64   `column-name:"high"`
	Low              float64   `column-name:"low"`
	Close            float64   `column-name:"close"`
	AdjustedClose    float64   `column-name:"adjusted_close"`
	Volume           int       `column-name:"volume"`
	DividendAmount   float64   `column-name:"dividend_amount"`
	SplitCoefficient float64   `column-name:"split_coefficient"`
}

func (q TimeSeriesDailyAdjustedQuery) CSVRows(ctx context.Context, client Doer) ([]TimeSeriesDailyAdjustedRow, error) {
	q.DataTypeCSV()
	return api.RequestCSVRows(ctx, client, q)
}

type TimeSeriesIntradayQuery url.Values

func QueryTimeSeriesIntraday(apiKey, symbol, interval string) TimeSeriesIntradayQuery {
	return TimeSeriesIntradayQuery{"function": []string{"TIME_SERIES_INTRADAY"}, "symbol": []string{symbol}, "interval": []string{interval}, "apikey": []string{apiKey}}
}

func (query TimeSeriesIntradayQuery) Adjusted(value bool) TimeSeriesIntradayQuery {
	query["adjusted"] = []string{strconv.FormatBool(value)}
	return query
}

func (query TimeSeriesIntradayQuery) ExtendedHours(value bool) TimeSeriesIntradayQuery {
	query["extended_hours"] = []string{strconv.FormatBool(value)}
	return query
}

func (query TimeSeriesIntradayQuery) Month(value time.Time) TimeSeriesIntradayQuery {
	query["month"] = []string{value.Format("2006-01")}
	return query
}

func (query TimeSeriesIntradayQuery) OutputSizeCompact() TimeSeriesIntradayQuery {
	query["outputsize"] = []string{"compact"}
	return query
}

func (query TimeSeriesIntradayQuery) OutputSizeFull() TimeSeriesIntradayQuery {
	query["outputsize"] = []string{"full"}
	return query
}

func (query TimeSeriesIntradayQuery) OutputSize(value string) TimeSeriesIntradayQuery {
	query["outputsize"] = []string{value}
	return query
}

func (query TimeSeriesIntradayQuery) DataTypeCSV() TimeSeriesIntradayQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query TimeSeriesIntradayQuery) DataTypeJSON() TimeSeriesIntradayQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query TimeSeriesIntradayQuery) DataType(value string) TimeSeriesIntradayQuery {
	query["datatype"] = []string{value}
	return query
}

func (q TimeSeriesIntradayQuery) DoWith(ctx context.Context, client Doer) (*http.Response, error) {
	return api.DoQuery(ctx, client, url.Values(q))
}

type TimeSeriesIntradayRow struct {
	TimeStamp time.Time `column-name:"timestamp" time-layout:"2006-01-02 15:04:05"`
	Open      float64   `column-name:"open"`
	High      float64   `column-name:"high"`
	Low       float64   `column-name:"low"`
	Close     float64   `column-name:"close"`
	Volume    int       `column-name:"volume"`
}

func (q TimeSeriesIntradayQuery) CSVRows(ctx context.Context, client Doer) ([]TimeSeriesIntradayRow, error) {
	q.DataTypeCSV()
	return api.RequestCSVRows(ctx, client, q)
}

type TimeSeriesMonthlyQuery url.Values

func QueryTimeSeriesMonthly(apiKey, symbol string) TimeSeriesMonthlyQuery {
	return TimeSeriesMonthlyQuery{"function": []string{"TIME_SERIES_MONTHLY"}, "symbol": []string{symbol}, "apikey": []string{apiKey}}
}

func (query TimeSeriesMonthlyQuery) DataTypeCSV() TimeSeriesMonthlyQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query TimeSeriesMonthlyQuery) DataTypeJSON() TimeSeriesMonthlyQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query TimeSeriesMonthlyQuery) DataType(value string) TimeSeriesMonthlyQuery {
	query["datatype"] = []string{value}
	return query
}

func (q TimeSeriesMonthlyQuery) DoWith(ctx context.Context, client Doer) (*http.Response, error) {
	return api.DoQuery(ctx, client, url.Values(q))
}

type TimeSeriesMonthlyRow struct {
	TimeStamp time.Time `column-name:"timestamp" time-layout:"2006-01-02"`
	Open      float64   `column-name:"open"`
	High      float64   `column-name:"high"`
	Low       float64   `column-name:"low"`
	Close     float64   `column-name:"close"`
	Volume    int       `column-name:"volume"`
}

func (q TimeSeriesMonthlyQuery) CSVRows(ctx context.Context, client Doer) ([]TimeSeriesMonthlyRow, error) {
	q.DataTypeCSV()
	return api.RequestCSVRows(ctx, client, q)
}

type TimeSeriesMonthlyAdjustedQuery url.Values

func QueryTimeSeriesMonthlyAdjusted(apiKey, symbol string) TimeSeriesMonthlyAdjustedQuery {
	return TimeSeriesMonthlyAdjustedQuery{"function": []string{"TIME_SERIES_MONTHLY_ADJUSTED"}, "symbol": []string{symbol}, "apikey": []string{apiKey}}
}

func (query TimeSeriesMonthlyAdjustedQuery) DataTypeCSV() TimeSeriesMonthlyAdjustedQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query TimeSeriesMonthlyAdjustedQuery) DataTypeJSON() TimeSeriesMonthlyAdjustedQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query TimeSeriesMonthlyAdjustedQuery) DataType(value string) TimeSeriesMonthlyAdjustedQuery {
	query["datatype"] = []string{value}
	return query
}

func (q TimeSeriesMonthlyAdjustedQuery) DoWith(ctx context.Context, client Doer) (*http.Response, error) {
	return api.DoQuery(ctx, client, url.Values(q))
}

type TimeSeriesMonthlyAdjustedRow struct {
	TimeStamp      time.Time `column-name:"timestamp" time-layout:"2006-01-02"`
	Open           float64   `column-name:"open"`
	High           float64   `column-name:"high"`
	Low            float64   `column-name:"low"`
	Close          float64   `column-name:"close"`
	AdjustedClose  float64   `column-name:"adjusted close"`
	Volume         int       `column-name:"volume"`
	DividendAmount float64   `column-name:"dividend amount"`
}

func (q TimeSeriesMonthlyAdjustedQuery) CSVRows(ctx context.Context, client Doer) ([]TimeSeriesMonthlyAdjustedRow, error) {
	q.DataTypeCSV()
	return api.RequestCSVRows(ctx, client, q)
}

type TimeSeriesWeeklyQuery url.Values

func QueryTimeSeriesWeekly(apiKey, symbol string) TimeSeriesWeeklyQuery {
	return TimeSeriesWeeklyQuery{"function": []string{"TIME_SERIES_WEEKLY"}, "symbol": []string{symbol}, "apikey": []string{apiKey}}
}

func (query TimeSeriesWeeklyQuery) DataTypeCSV() TimeSeriesWeeklyQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query TimeSeriesWeeklyQuery) DataTypeJSON() TimeSeriesWeeklyQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query TimeSeriesWeeklyQuery) DataType(value string) TimeSeriesWeeklyQuery {
	query["datatype"] = []string{value}
	return query
}

func (q TimeSeriesWeeklyQuery) DoWith(ctx context.Context, client Doer) (*http.Response, error) {
	return api.DoQuery(ctx, client, url.Values(q))
}

type TimeSeriesWeeklyRow struct {
	TimeStamp time.Time `column-name:"timestamp" time-layout:"2006-01-02"`
	Open      float64   `column-name:"open"`
	High      float64   `column-name:"high"`
	Low       float64   `column-name:"low"`
	Close     float64   `column-name:"close"`
	Volume    int       `column-name:"volume"`
}

func (q TimeSeriesWeeklyQuery) CSVRows(ctx context.Context, client Doer) ([]TimeSeriesWeeklyRow, error) {
	q.DataTypeCSV()
	return api.RequestCSVRows(ctx, client, q)
}

type TimeSeriesWeeklyAdjustedQuery url.Values

func QueryTimeSeriesWeeklyAdjusted(apiKey, symbol string) TimeSeriesWeeklyAdjustedQuery {
	return TimeSeriesWeeklyAdjustedQuery{"function": []string{"TIME_SERIES_WEEKLY_ADJUSTED"}, "symbol": []string{symbol}, "apikey": []string{apiKey}}
}

func (query TimeSeriesWeeklyAdjustedQuery) DataTypeCSV() TimeSeriesWeeklyAdjustedQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query TimeSeriesWeeklyAdjustedQuery) DataTypeJSON() TimeSeriesWeeklyAdjustedQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query TimeSeriesWeeklyAdjustedQuery) DataType(value string) TimeSeriesWeeklyAdjustedQuery {
	query["datatype"] = []string{value}
	return query
}

func (q TimeSeriesWeeklyAdjustedQuery) DoWith(ctx context.Context, client Doer) (*http.Response, error) {
	return api.DoQuery(ctx, client, url.Values(q))
}

type TimeSeriesWeeklyAdjustedRow struct {
	TimeStamp      time.Time `column-name:"timestamp" time-layout:"2006-01-02"`
	Open           float64   `column-name:"open"`
	High           float64   `column-name:"high"`
	Low            float64   `column-name:"low"`
	Close          float64   `column-name:"close"`
	AdjustedClose  float64   `column-name:"adjusted close"`
	Volume         int       `column-name:"volume"`
	DividendAmount float64   `column-name:"dividend amount"`
}

func (q TimeSeriesWeeklyAdjustedQuery) CSVRows(ctx context.Context, client Doer) ([]TimeSeriesWeeklyAdjustedRow, error) {
	q.DataTypeCSV()
	return api.RequestCSVRows(ctx, client, q)
}
