// Code generated by av-generate; DO NOT EDIT.

package timeseries

import (
	"net/url"
	"strconv"
	"time"
)

type GlobalQuoteQuery url.Values

func QueryGlobalQuote(apiKey, symbol string) GlobalQuoteQuery {
	return GlobalQuoteQuery{"function": []string{"GLOBAL_QUOTE"}, "symbol": []string{symbol}, "apikey": []string{apiKey}}
}

func (query GlobalQuoteQuery) DataTypeCSV() GlobalQuoteQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query GlobalQuoteQuery) DataTypeJSON() GlobalQuoteQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query GlobalQuoteQuery) DataType(value string) GlobalQuoteQuery {
	query["datatype"] = []string{value}
	return query
}

func (q GlobalQuoteQuery) Encode() string {
	return url.Values(q).Encode()
}

type GlobalQuoteRow struct {
	Symbol        string `column-name:"symbol"`
	Open          string `column-name:"open"`
	High          string `column-name:"high"`
	Low           string `column-name:"low"`
	Price         string `column-name:"price"`
	Volume        string `column-name:"volume"`
	LatestDay     string `column-name:"latestDay"`
	PreviousClose string `column-name:"previousClose"`
	Change        string `column-name:"change"`
	ChangePercent string `column-name:"changePercent"`
}

type MarketStatusQuery url.Values

func QueryMarketStatus(apiKey string) MarketStatusQuery {
	return MarketStatusQuery{"function": []string{"MARKET_STATUS"}, "apikey": []string{apiKey}}
}

func (q MarketStatusQuery) Encode() string {
	return url.Values(q).Encode()
}

type RealtimeBulkQuotesQuery url.Values

func QueryRealtimeBulkQuotes(apiKey, symbol string) RealtimeBulkQuotesQuery {
	return RealtimeBulkQuotesQuery{"function": []string{"REALTIME_BULK_QUOTES"}, "symbol": []string{symbol}, "apikey": []string{apiKey}}
}

func (query RealtimeBulkQuotesQuery) DataTypeCSV() RealtimeBulkQuotesQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query RealtimeBulkQuotesQuery) DataTypeJSON() RealtimeBulkQuotesQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query RealtimeBulkQuotesQuery) DataType(value string) RealtimeBulkQuotesQuery {
	query["datatype"] = []string{value}
	return query
}

func (q RealtimeBulkQuotesQuery) Encode() string {
	return url.Values(q).Encode()
}

type SymbolSearchQuery url.Values

func QuerySymbolSearch(apiKey, keywords string) SymbolSearchQuery {
	return SymbolSearchQuery{"function": []string{"SYMBOL_SEARCH"}, "keywords": []string{keywords}, "apikey": []string{apiKey}}
}

func (query SymbolSearchQuery) DataTypeCSV() SymbolSearchQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query SymbolSearchQuery) DataTypeJSON() SymbolSearchQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query SymbolSearchQuery) DataType(value string) SymbolSearchQuery {
	query["datatype"] = []string{value}
	return query
}

func (q SymbolSearchQuery) Encode() string {
	return url.Values(q).Encode()
}

type SymbolSearchRow struct {
	Symbol      string  `column-name:"symbol"`
	Name        string  `column-name:"name"`
	Type        string  `column-name:"type"`
	Region      string  `column-name:"region"`
	MarketOpen  string  `column-name:"marketOpen"`
	MarketClose string  `column-name:"marketClose"`
	TimeZone    string  `column-name:"timezone"`
	Currency    string  `column-name:"currency"`
	MatchScore  float64 `column-name:"matchScore"`
}

type DailyQuery url.Values

func QueryDaily(apiKey, symbol string) DailyQuery {
	return DailyQuery{"function": []string{"TIME_SERIES_DAILY"}, "symbol": []string{symbol}, "apikey": []string{apiKey}}
}

func (query DailyQuery) OutputSizeCompact() DailyQuery {
	query["outputsize"] = []string{"compact"}
	return query
}

func (query DailyQuery) OutputSizeFull() DailyQuery {
	query["outputsize"] = []string{"full"}
	return query
}

func (query DailyQuery) OutputSize(value string) DailyQuery {
	query["outputsize"] = []string{value}
	return query
}

func (query DailyQuery) DataTypeCSV() DailyQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query DailyQuery) DataTypeJSON() DailyQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query DailyQuery) DataType(value string) DailyQuery {
	query["datatype"] = []string{value}
	return query
}

func (q DailyQuery) Encode() string {
	return url.Values(q).Encode()
}

type DailyRow struct {
	TimeStamp time.Time `column-name:"timestamp" time-layout:"2006-01-02"`
	Open      float64   `column-name:"open"`
	High      float64   `column-name:"high"`
	Low       float64   `column-name:"low"`
	Close     float64   `column-name:"close"`
	Volume    int       `column-name:"volume"`
}

type DailyAdjustedQuery url.Values

func QueryDailyAdjusted(apiKey, symbol string) DailyAdjustedQuery {
	return DailyAdjustedQuery{"function": []string{"TIME_SERIES_DAILY_ADJUSTED"}, "symbol": []string{symbol}, "apikey": []string{apiKey}}
}

func (query DailyAdjustedQuery) OutputSizeCompact() DailyAdjustedQuery {
	query["outputsize"] = []string{"compact"}
	return query
}

func (query DailyAdjustedQuery) OutputSizeFull() DailyAdjustedQuery {
	query["outputsize"] = []string{"full"}
	return query
}

func (query DailyAdjustedQuery) OutputSize(value string) DailyAdjustedQuery {
	query["outputsize"] = []string{value}
	return query
}

func (query DailyAdjustedQuery) DataTypeCSV() DailyAdjustedQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query DailyAdjustedQuery) DataTypeJSON() DailyAdjustedQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query DailyAdjustedQuery) DataType(value string) DailyAdjustedQuery {
	query["datatype"] = []string{value}
	return query
}

func (q DailyAdjustedQuery) Encode() string {
	return url.Values(q).Encode()
}

type DailyAdjustedRow struct {
	TimeStamp        time.Time `column-name:"timestamp" time-layout:"2006-01-02"`
	Open             float64   `column-name:"open"`
	High             float64   `column-name:"high"`
	Low              float64   `column-name:"low"`
	Close            float64   `column-name:"close"`
	AdjustedClose    float64   `column-name:"adjusted_close"`
	Volume           int       `column-name:"volume"`
	DividendAmount   float64   `column-name:"dividend_amount"`
	SplitCoefficient float64   `column-name:"split_coefficient"`
}

type IntradayQuery url.Values

func QueryIntraday(apiKey, symbol, interval string) IntradayQuery {
	return IntradayQuery{"function": []string{"TIME_SERIES_INTRADAY"}, "symbol": []string{symbol}, "interval": []string{interval}, "apikey": []string{apiKey}}
}

func (query IntradayQuery) Adjusted(value bool) IntradayQuery {
	query["adjusted"] = []string{strconv.FormatBool(value)}
	return query
}

func (query IntradayQuery) ExtendedHours(value bool) IntradayQuery {
	query["extended_hours"] = []string{strconv.FormatBool(value)}
	return query
}

func (query IntradayQuery) Month(value time.Time) IntradayQuery {
	query["month"] = []string{value.Format("2006-01")}
	return query
}

func (query IntradayQuery) OutputSizeCompact() IntradayQuery {
	query["outputsize"] = []string{"compact"}
	return query
}

func (query IntradayQuery) OutputSizeFull() IntradayQuery {
	query["outputsize"] = []string{"full"}
	return query
}

func (query IntradayQuery) OutputSize(value string) IntradayQuery {
	query["outputsize"] = []string{value}
	return query
}

func (query IntradayQuery) DataTypeCSV() IntradayQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query IntradayQuery) DataTypeJSON() IntradayQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query IntradayQuery) DataType(value string) IntradayQuery {
	query["datatype"] = []string{value}
	return query
}

func (q IntradayQuery) Encode() string {
	return url.Values(q).Encode()
}

type IntradayRow struct {
	TimeStamp time.Time `column-name:"timestamp" time-layout:"2006-01-02 15:04:05"`
	Open      float64   `column-name:"open"`
	High      float64   `column-name:"high"`
	Low       float64   `column-name:"low"`
	Close     float64   `column-name:"close"`
	Volume    int       `column-name:"volume"`
}

type MonthlyQuery url.Values

func QueryMonthly(apiKey, symbol string) MonthlyQuery {
	return MonthlyQuery{"function": []string{"TIME_SERIES_MONTHLY"}, "symbol": []string{symbol}, "apikey": []string{apiKey}}
}

func (query MonthlyQuery) DataTypeCSV() MonthlyQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query MonthlyQuery) DataTypeJSON() MonthlyQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query MonthlyQuery) DataType(value string) MonthlyQuery {
	query["datatype"] = []string{value}
	return query
}

func (q MonthlyQuery) Encode() string {
	return url.Values(q).Encode()
}

type MonthlyRow struct {
	TimeStamp time.Time `column-name:"timestamp" time-layout:"2006-01-02"`
	Open      float64   `column-name:"open"`
	High      float64   `column-name:"high"`
	Low       float64   `column-name:"low"`
	Close     float64   `column-name:"close"`
	Volume    int       `column-name:"volume"`
}

type MonthlyAdjustedQuery url.Values

func QueryMonthlyAdjusted(apiKey, symbol string) MonthlyAdjustedQuery {
	return MonthlyAdjustedQuery{"function": []string{"TIME_SERIES_MONTHLY_ADJUSTED"}, "symbol": []string{symbol}, "apikey": []string{apiKey}}
}

func (query MonthlyAdjustedQuery) DataTypeCSV() MonthlyAdjustedQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query MonthlyAdjustedQuery) DataTypeJSON() MonthlyAdjustedQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query MonthlyAdjustedQuery) DataType(value string) MonthlyAdjustedQuery {
	query["datatype"] = []string{value}
	return query
}

func (q MonthlyAdjustedQuery) Encode() string {
	return url.Values(q).Encode()
}

type MonthlyAdjustedRow struct {
	TimeStamp      time.Time `column-name:"timestamp" time-layout:"2006-01-02"`
	Open           float64   `column-name:"open"`
	High           float64   `column-name:"high"`
	Low            float64   `column-name:"low"`
	Close          float64   `column-name:"close"`
	AdjustedClose  float64   `column-name:"adjusted close"`
	Volume         int       `column-name:"volume"`
	DividendAmount float64   `column-name:"dividend amount"`
}

type WeeklyQuery url.Values

func QueryWeekly(apiKey, symbol string) WeeklyQuery {
	return WeeklyQuery{"function": []string{"TIME_SERIES_WEEKLY"}, "symbol": []string{symbol}, "apikey": []string{apiKey}}
}

func (query WeeklyQuery) DataTypeCSV() WeeklyQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query WeeklyQuery) DataTypeJSON() WeeklyQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query WeeklyQuery) DataType(value string) WeeklyQuery {
	query["datatype"] = []string{value}
	return query
}

func (q WeeklyQuery) Encode() string {
	return url.Values(q).Encode()
}

type WeeklyRow struct {
	TimeStamp time.Time `column-name:"timestamp" time-layout:"2006-01-02"`
	Open      float64   `column-name:"open"`
	High      float64   `column-name:"high"`
	Low       float64   `column-name:"low"`
	Close     float64   `column-name:"close"`
	Volume    int       `column-name:"volume"`
}

type WeeklyAdjustedQuery url.Values

func QueryWeeklyAdjusted(apiKey, symbol string) WeeklyAdjustedQuery {
	return WeeklyAdjustedQuery{"function": []string{"TIME_SERIES_WEEKLY_ADJUSTED"}, "symbol": []string{symbol}, "apikey": []string{apiKey}}
}

func (query WeeklyAdjustedQuery) DataTypeCSV() WeeklyAdjustedQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query WeeklyAdjustedQuery) DataTypeJSON() WeeklyAdjustedQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query WeeklyAdjustedQuery) DataType(value string) WeeklyAdjustedQuery {
	query["datatype"] = []string{value}
	return query
}

func (q WeeklyAdjustedQuery) Encode() string {
	return url.Values(q).Encode()
}

type WeeklyAdjustedRow struct {
	TimeStamp      time.Time `column-name:"timestamp" time-layout:"2006-01-02"`
	Open           float64   `column-name:"open"`
	High           float64   `column-name:"high"`
	Low            float64   `column-name:"low"`
	Close          float64   `column-name:"close"`
	AdjustedClose  float64   `column-name:"adjusted close"`
	Volume         int       `column-name:"volume"`
	DividendAmount float64   `column-name:"dividend amount"`
}
