// Code generated by av-generate; DO NOT EDIT.

package options

import (
	"net/url"
	"strconv"
	"time"
)

type HistoricalQuery url.Values

func QueryHistorical(apiKey, symbol string) HistoricalQuery {
	return HistoricalQuery{"function": []string{"HISTORICAL_OPTIONS"}, "symbol": []string{symbol}, "apikey": []string{apiKey}}
}

func (query HistoricalQuery) Date(value string) HistoricalQuery {
	query["date"] = []string{value}
	return query
}

func (query HistoricalQuery) Contract(value string) HistoricalQuery {
	query["contract"] = []string{value}
	return query
}

func (query HistoricalQuery) Expiration(value time.Time) HistoricalQuery {
	query["expiration"] = []string{value.Format("2006-01-02")}
	return query
}

func (query HistoricalQuery) DataTypeCSV() HistoricalQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query HistoricalQuery) DataTypeJSON() HistoricalQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query HistoricalQuery) DataType(value string) HistoricalQuery {
	query["datatype"] = []string{value}
	return query
}

func (q HistoricalQuery) Encode() string {
	return url.Values(q).Encode()
}

type HistoricalRow struct {
	ContractID        string `column-name:"contractID"`
	Symbol            string `column-name:"symbol"`
	Expiration        string `column-name:"expiration"`
	Strike            string `column-name:"strike"`
	Type              string `column-name:"type"`
	Last              string `column-name:"last"`
	Mark              string `column-name:"mark"`
	Bid               string `column-name:"bid"`
	BidSize           string `column-name:"bid_size"`
	Ask               string `column-name:"ask"`
	AskSize           string `column-name:"ask_size"`
	Volume            string `column-name:"volume"`
	OpenInterest      string `column-name:"open_interest"`
	Date              string `column-name:"date"`
	ImpliedVolatility string `column-name:"implied_volatility"`
	Delta             string `column-name:"delta"`
	Gamma             string `column-name:"gamma"`
	Theta             string `column-name:"theta"`
	Vega              string `column-name:"vega"`
	RHO               string `column-name:"rho"`
}

type HistoricalPutCallRatioQuery url.Values

func QueryHistoricalPutCallRatio(apiKey, symbol string) HistoricalPutCallRatioQuery {
	return HistoricalPutCallRatioQuery{"function": []string{"HISTORICAL_PUT_CALL_RATIO"}, "symbol": []string{symbol}, "apikey": []string{apiKey}}
}

func (query HistoricalPutCallRatioQuery) Date(value string) HistoricalPutCallRatioQuery {
	query["date"] = []string{value}
	return query
}

func (q HistoricalPutCallRatioQuery) Encode() string {
	return url.Values(q).Encode()
}

type HistoricalVolumeOpenInterestRatioQuery url.Values

func QueryHistoricalVolumeOpenInterestRatio(apiKey, symbol string) HistoricalVolumeOpenInterestRatioQuery {
	return HistoricalVolumeOpenInterestRatioQuery{"function": []string{"HISTORICAL_VOLUME_OPEN_INTEREST_RATIO"}, "symbol": []string{symbol}, "apikey": []string{apiKey}}
}

func (query HistoricalVolumeOpenInterestRatioQuery) Date(value string) HistoricalVolumeOpenInterestRatioQuery {
	query["date"] = []string{value}
	return query
}

func (q HistoricalVolumeOpenInterestRatioQuery) Encode() string {
	return url.Values(q).Encode()
}

type RealtimeQuery url.Values

func QueryRealtime(apiKey, symbol string) RealtimeQuery {
	return RealtimeQuery{"function": []string{"REALTIME_OPTIONS"}, "symbol": []string{symbol}, "apikey": []string{apiKey}}
}

func (query RealtimeQuery) RequireGreeks(value bool) RealtimeQuery {
	query["require_greeks"] = []string{strconv.FormatBool(value)}
	return query
}

func (query RealtimeQuery) Contract(value string) RealtimeQuery {
	query["contract"] = []string{value}
	return query
}

func (query RealtimeQuery) Expiration(value time.Time) RealtimeQuery {
	query["expiration"] = []string{value.Format("2006-01-02")}
	return query
}

func (query RealtimeQuery) DataTypeCSV() RealtimeQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query RealtimeQuery) DataTypeJSON() RealtimeQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query RealtimeQuery) DataType(value string) RealtimeQuery {
	query["datatype"] = []string{value}
	return query
}

func (q RealtimeQuery) Encode() string {
	return url.Values(q).Encode()
}

type RealtimePutCallRatioQuery url.Values

func QueryRealtimePutCallRatio(apiKey, symbol string) RealtimePutCallRatioQuery {
	return RealtimePutCallRatioQuery{"function": []string{"REALTIME_PUT_CALL_RATIO"}, "symbol": []string{symbol}, "apikey": []string{apiKey}}
}

func (q RealtimePutCallRatioQuery) Encode() string {
	return url.Values(q).Encode()
}

type RealtimeVolumeOpenInterestRatioQuery url.Values

func QueryRealtimeVolumeOpenInterestRatio(apiKey, symbol string) RealtimeVolumeOpenInterestRatioQuery {
	return RealtimeVolumeOpenInterestRatioQuery{"function": []string{"REALTIME_VOLUME_OPEN_INTEREST_RATIO"}, "symbol": []string{symbol}, "apikey": []string{apiKey}}
}

func (q RealtimeVolumeOpenInterestRatioQuery) Encode() string {
	return url.Values(q).Encode()
}
