package query

import "net/url"

func (q AD) Values() url.Values                        { return url.Values(q) }
func (q ADOSC) Values() url.Values                     { return url.Values(q) }
func (q ADX) Values() url.Values                       { return url.Values(q) }
func (q ADXR) Values() url.Values                      { return url.Values(q) }
func (q APO) Values() url.Values                       { return url.Values(q) }
func (q AROON) Values() url.Values                     { return url.Values(q) }
func (q AROONOSC) Values() url.Values                  { return url.Values(q) }
func (q ATR) Values() url.Values                       { return url.Values(q) }
func (q AllCommodities) Values() url.Values            { return url.Values(q) }
func (q Aluminum) Values() url.Values                  { return url.Values(q) }
func (q AnalyticsFixedWindow) Values() url.Values      { return url.Values(q) }
func (q AnalyticsSlidingWindow) Values() url.Values    { return url.Values(q) }
func (q BBANDS) Values() url.Values                    { return url.Values(q) }
func (q BOP) Values() url.Values                       { return url.Values(q) }
func (q BalanceSheet) Values() url.Values              { return url.Values(q) }
func (q Brent) Values() url.Values                     { return url.Values(q) }
func (q CCI) Values() url.Values                       { return url.Values(q) }
func (q CMO) Values() url.Values                       { return url.Values(q) }
func (q CPI) Values() url.Values                       { return url.Values(q) }
func (q CashFlow) Values() url.Values                  { return url.Values(q) }
func (q Coffee) Values() url.Values                    { return url.Values(q) }
func (q Copper) Values() url.Values                    { return url.Values(q) }
func (q Corn) Values() url.Values                      { return url.Values(q) }
func (q Cotton) Values() url.Values                    { return url.Values(q) }
func (q CryptoIntraday) Values() url.Values            { return url.Values(q) }
func (q CurrencyExchangeRate) Values() url.Values      { return url.Values(q) }
func (q DEMA) Values() url.Values                      { return url.Values(q) }
func (q DX) Values() url.Values                        { return url.Values(q) }
func (q DigitalCurrencyDaily) Values() url.Values      { return url.Values(q) }
func (q DigitalCurrencyMonthly) Values() url.Values    { return url.Values(q) }
func (q DigitalCurrencyWeekly) Values() url.Values     { return url.Values(q) }
func (q Dividends) Values() url.Values                 { return url.Values(q) }
func (q DurablesQuery) Values() url.Values             { return url.Values(q) }
func (q EMA) Values() url.Values                       { return url.Values(q) }
func (q ETFProfile) Values() url.Values                { return url.Values(q) }
func (q Earnings) Values() url.Values                  { return url.Values(q) }
func (q EarningsCalendar) Values() url.Values          { return url.Values(q) }
func (q EarningsCallTranscript) Values() url.Values    { return url.Values(q) }
func (q EarningsEstimates) Values() url.Values         { return url.Values(q) }
func (q FXDaily) Values() url.Values                   { return url.Values(q) }
func (q FXIntraday) Values() url.Values                { return url.Values(q) }
func (q FXMonthly) Values() url.Values                 { return url.Values(q) }
func (q FXWeekly) Values() url.Values                  { return url.Values(q) }
func (q FederalFundsRate) Values() url.Values          { return url.Values(q) }
func (q GlobalQuote) Values() url.Values               { return url.Values(q) }
func (q HilbertTransformDCPeriod) Values() url.Values  { return url.Values(q) }
func (q HilbertTransformDCPhase) Values() url.Values   { return url.Values(q) }
func (q HilbertTransformPhasor) Values() url.Values    { return url.Values(q) }
func (q HilbertTransformSine) Values() url.Values      { return url.Values(q) }
func (q HilbertTransformTrendLine) Values() url.Values { return url.Values(q) }
func (q HilbertTransformTrendMode) Values() url.Values { return url.Values(q) }
func (q HistoricalOptions) Values() url.Values         { return url.Values(q) }
func (q IPOCalendar) Values() url.Values               { return url.Values(q) }
func (q IncomeStatement) Values() url.Values           { return url.Values(q) }
func (q InflationQuery) Values() url.Values            { return url.Values(q) }
func (q InsiderTransactions) Values() url.Values       { return url.Values(q) }
func (q KAMA) Values() url.Values                      { return url.Values(q) }
func (q ListingStatus) Values() url.Values             { return url.Values(q) }
func (q MACD) Values() url.Values                      { return url.Values(q) }
func (q MACDEXT) Values() url.Values                   { return url.Values(q) }
func (q MAMA) Values() url.Values                      { return url.Values(q) }
func (q MFI) Values() url.Values                       { return url.Values(q) }
func (q Midpoint) Values() url.Values                  { return url.Values(q) }
func (q MIDPRICE) Values() url.Values                  { return url.Values(q) }
func (q MINUSDI) Values() url.Values                   { return url.Values(q) }
func (q MINUSDM) Values() url.Values                   { return url.Values(q) }
func (q MOM) Values() url.Values                       { return url.Values(q) }
func (q MarketStatus) Values() url.Values              { return url.Values(q) }
func (q NATR) Values() url.Values                      { return url.Values(q) }
func (q NaturalGas) Values() url.Values                { return url.Values(q) }
func (q NewsSentiment) Values() url.Values             { return url.Values(q) }
func (q NonfarmPayroll) Values() url.Values            { return url.Values(q) }
func (q OBV) Values() url.Values                       { return url.Values(q) }
func (q Overview) Values() url.Values                  { return url.Values(q) }
func (q PLUSDI) Values() url.Values                    { return url.Values(q) }
func (q PLUSDM) Values() url.Values                    { return url.Values(q) }
func (q PPO) Values() url.Values                       { return url.Values(q) }
func (q ROC) Values() url.Values                       { return url.Values(q) }
func (q ROCR) Values() url.Values                      { return url.Values(q) }
func (q RSI) Values() url.Values                       { return url.Values(q) }
func (q RealGDP) Values() url.Values                   { return url.Values(q) }
func (q RealGDPPerCapita) Values() url.Values          { return url.Values(q) }
func (q RealtimeBulkQuotes) Values() url.Values        { return url.Values(q) }
func (q RealtimeOptions) Values() url.Values           { return url.Values(q) }
func (q RetailSalesQuery) Values() url.Values          { return url.Values(q) }
func (q SAR) Values() url.Values                       { return url.Values(q) }
func (q SMA) Values() url.Values                       { return url.Values(q) }
func (q STOCH) Values() url.Values                     { return url.Values(q) }
func (q STOCHF) Values() url.Values                    { return url.Values(q) }
func (q STOCHRSI) Values() url.Values                  { return url.Values(q) }
func (q SharesOutstanding) Values() url.Values         { return url.Values(q) }
func (q Splits) Values() url.Values                    { return url.Values(q) }
func (q Sugar) Values() url.Values                     { return url.Values(q) }
func (q SymbolSearch) Values() url.Values              { return url.Values(q) }
func (q T3) Values() url.Values                        { return url.Values(q) }
func (q TEMA) Values() url.Values                      { return url.Values(q) }
func (q TRANGE) Values() url.Values                    { return url.Values(q) }
func (q TRIMA) Values() url.Values                     { return url.Values(q) }
func (q TRIX) Values() url.Values                      { return url.Values(q) }
func (q TimeSeriesDaily) Values() url.Values           { return url.Values(q) }
func (q TimeSeriesDailyAdjusted) Values() url.Values   { return url.Values(q) }
func (q TimeSeriesIntraday) Values() url.Values        { return url.Values(q) }
func (q TimeSeriesMonthly) Values() url.Values         { return url.Values(q) }
func (q TimeSeriesMonthlyAdjusted) Values() url.Values { return url.Values(q) }
func (q TimeSeriesWeekly) Values() url.Values          { return url.Values(q) }
func (q TimeSeriesWeeklyAdjusted) Values() url.Values  { return url.Values(q) }
func (q TopGainersLosers) Values() url.Values          { return url.Values(q) }
func (q TreasuryYield) Values() url.Values             { return url.Values(q) }
func (q ULTOSC) Values() url.Values                    { return url.Values(q) }
func (q Unemployment) Values() url.Values              { return url.Values(q) }
func (q VWAP) Values() url.Values                      { return url.Values(q) }
func (q WILLR) Values() url.Values                     { return url.Values(q) }
func (q WMA) Values() url.Values                       { return url.Values(q) }
func (q WTI) Values() url.Values                       { return url.Values(q) }
func (q Wheat) Values() url.Values                     { return url.Values(q) }
