// Code generated by av-generate; DO NOT EDIT.

package forex

import "net/url"

type CurrencyExchangeRateQuery url.Values

func QueryCurrencyExchangeRate(apiKey, fromCurrency, toCurrency string) CurrencyExchangeRateQuery {
	return CurrencyExchangeRateQuery{"function": []string{"CURRENCY_EXCHANGE_RATE"}, "from_currency": []string{fromCurrency}, "to_currency": []string{toCurrency}, "apikey": []string{apiKey}}
}

func (q CurrencyExchangeRateQuery) Encode() string {
	return url.Values(q).Encode()
}

type DailyQuery url.Values

func QueryDaily(apiKey, fromSymbol, toSymbol string) DailyQuery {
	return DailyQuery{"function": []string{"FX_DAILY"}, "from_symbol": []string{fromSymbol}, "to_symbol": []string{toSymbol}, "apikey": []string{apiKey}}
}

func (query DailyQuery) OutputSizeCompact() DailyQuery {
	query["outputsize"] = []string{"compact"}
	return query
}

func (query DailyQuery) OutputSizeFull() DailyQuery {
	query["outputsize"] = []string{"full"}
	return query
}

func (query DailyQuery) OutputSize(value string) DailyQuery {
	query["outputsize"] = []string{value}
	return query
}

func (query DailyQuery) DataTypeCSV() DailyQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query DailyQuery) DataTypeJSON() DailyQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query DailyQuery) DataType(value string) DailyQuery {
	query["datatype"] = []string{value}
	return query
}

func (q DailyQuery) Encode() string {
	return url.Values(q).Encode()
}

type DailyRow struct {
	TimeStamp string `column-name:"timestamp"`
	Open      string `column-name:"open"`
	High      string `column-name:"high"`
	Low       string `column-name:"low"`
	Close     string `column-name:"close"`
}

type IntradayQuery url.Values

func QueryIntraday(apiKey, fromSymbol, toSymbol, interval string) IntradayQuery {
	return IntradayQuery{"function": []string{"FX_INTRADAY"}, "from_symbol": []string{fromSymbol}, "to_symbol": []string{toSymbol}, "interval": []string{interval}, "apikey": []string{apiKey}}
}

func (query IntradayQuery) OutputSizeCompact() IntradayQuery {
	query["outputsize"] = []string{"compact"}
	return query
}

func (query IntradayQuery) OutputSizeFull() IntradayQuery {
	query["outputsize"] = []string{"full"}
	return query
}

func (query IntradayQuery) OutputSize(value string) IntradayQuery {
	query["outputsize"] = []string{value}
	return query
}

func (query IntradayQuery) DataTypeCSV() IntradayQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query IntradayQuery) DataTypeJSON() IntradayQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query IntradayQuery) DataType(value string) IntradayQuery {
	query["datatype"] = []string{value}
	return query
}

func (q IntradayQuery) Encode() string {
	return url.Values(q).Encode()
}

type IntradayRow struct {
	TimeStamp string `column-name:"timestamp"`
	Open      string `column-name:"open"`
	High      string `column-name:"high"`
	Low       string `column-name:"low"`
	Close     string `column-name:"close"`
}

type MonthlyQuery url.Values

func QueryMonthly(apiKey, fromSymbol, toSymbol string) MonthlyQuery {
	return MonthlyQuery{"function": []string{"FX_MONTHLY"}, "from_symbol": []string{fromSymbol}, "to_symbol": []string{toSymbol}, "apikey": []string{apiKey}}
}

func (query MonthlyQuery) DataTypeCSV() MonthlyQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query MonthlyQuery) DataTypeJSON() MonthlyQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query MonthlyQuery) DataType(value string) MonthlyQuery {
	query["datatype"] = []string{value}
	return query
}

func (q MonthlyQuery) Encode() string {
	return url.Values(q).Encode()
}

type MonthlyRow struct {
	TimeStamp string `column-name:"timestamp"`
	Open      string `column-name:"open"`
	High      string `column-name:"high"`
	Low       string `column-name:"low"`
	Close     string `column-name:"close"`
}

type WeeklyQuery url.Values

func QueryWeekly(apiKey, fromSymbol, toSymbol string) WeeklyQuery {
	return WeeklyQuery{"function": []string{"FX_WEEKLY"}, "from_symbol": []string{fromSymbol}, "to_symbol": []string{toSymbol}, "apikey": []string{apiKey}}
}

func (query WeeklyQuery) DataTypeCSV() WeeklyQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query WeeklyQuery) DataTypeJSON() WeeklyQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query WeeklyQuery) DataType(value string) WeeklyQuery {
	query["datatype"] = []string{value}
	return query
}

func (q WeeklyQuery) Encode() string {
	return url.Values(q).Encode()
}

type WeeklyRow struct {
	TimeStamp string `column-name:"timestamp"`
	Open      string `column-name:"open"`
	High      string `column-name:"high"`
	Low       string `column-name:"low"`
	Close     string `column-name:"close"`
}
