// Code generated by av-generate; DO NOT EDIT.

package fundamental

import "net/url"

type BalanceSheetQuery url.Values

func QueryBalanceSheet(apiKey, symbol string) BalanceSheetQuery {
	return BalanceSheetQuery{"function": []string{"BALANCE_SHEET"}, "symbol": []string{symbol}, "apikey": []string{apiKey}}
}

func (q BalanceSheetQuery) Encode() string {
	return url.Values(q).Encode()
}

type CashFlowQuery url.Values

func QueryCashFlow(apiKey, symbol string) CashFlowQuery {
	return CashFlowQuery{"function": []string{"CASH_FLOW"}, "symbol": []string{symbol}, "apikey": []string{apiKey}}
}

func (q CashFlowQuery) Encode() string {
	return url.Values(q).Encode()
}

type DividendsQuery url.Values

func QueryDividends(apiKey, symbol string) DividendsQuery {
	return DividendsQuery{"function": []string{"DIVIDENDS"}, "symbol": []string{symbol}, "apikey": []string{apiKey}}
}

func (query DividendsQuery) DataTypeCSV() DividendsQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query DividendsQuery) DataTypeJSON() DividendsQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query DividendsQuery) DataType(value string) DividendsQuery {
	query["datatype"] = []string{value}
	return query
}

func (q DividendsQuery) Encode() string {
	return url.Values(q).Encode()
}

type DividendsRow struct {
	ExDividendDate  string `column-name:"ex_dividend_date"`
	DeclarationDate string `column-name:"declaration_date"`
	RecordDate      string `column-name:"record_date"`
	PaymentDate     string `column-name:"payment_date"`
	Amount          string `column-name:"amount"`
}

type ETFProfileQuery url.Values

func QueryETFProfile(apiKey, symbol string) ETFProfileQuery {
	return ETFProfileQuery{"function": []string{"ETF_PROFILE"}, "symbol": []string{symbol}, "apikey": []string{apiKey}}
}

func (q ETFProfileQuery) Encode() string {
	return url.Values(q).Encode()
}

type EarningsQuery url.Values

func QueryEarnings(apiKey, symbol string) EarningsQuery {
	return EarningsQuery{"function": []string{"EARNINGS"}, "symbol": []string{symbol}, "apikey": []string{apiKey}}
}

func (q EarningsQuery) Encode() string {
	return url.Values(q).Encode()
}

type EarningsCalendarQuery url.Values

func QueryEarningsCalendar(apiKey string) EarningsCalendarQuery {
	return EarningsCalendarQuery{"function": []string{"EARNINGS_CALENDAR"}, "apikey": []string{apiKey}}
}

func (query EarningsCalendarQuery) Symbol(value string) EarningsCalendarQuery {
	query["symbol"] = []string{value}
	return query
}

func (query EarningsCalendarQuery) Horizon(value string) EarningsCalendarQuery {
	query["horizon"] = []string{value}
	return query
}

func (q EarningsCalendarQuery) Encode() string {
	return url.Values(q).Encode()
}

type EarningsCalendarRow struct {
	Symbol           string `column-name:"symbol"`
	Name             string `column-name:"name"`
	ReportDate       string `column-name:"reportDate"`
	FiscalDateEnding string `column-name:"fiscalDateEnding"`
	Estimate         string `column-name:"estimate"`
	Currency         string `column-name:"currency"`
	TimeOfTheDay     string `column-name:"timeOfTheDay"`
}

type EarningsEstimatesQuery url.Values

func QueryEarningsEstimates(apiKey, symbol string) EarningsEstimatesQuery {
	return EarningsEstimatesQuery{"function": []string{"EARNINGS_ESTIMATES"}, "symbol": []string{symbol}, "apikey": []string{apiKey}}
}

func (q EarningsEstimatesQuery) Encode() string {
	return url.Values(q).Encode()
}

type IPOCalendarQuery url.Values

func QueryIPOCalendar(apiKey string) IPOCalendarQuery {
	return IPOCalendarQuery{"function": []string{"IPO_CALENDAR"}, "apikey": []string{apiKey}}
}

func (q IPOCalendarQuery) Encode() string {
	return url.Values(q).Encode()
}

type IPOCalendarRow struct {
	Symbol         string `column-name:"symbol"`
	Name           string `column-name:"name"`
	IPODate        string `column-name:"ipoDate"`
	PriceRangeLow  string `column-name:"priceRangeLow"`
	PriceRangeHigh string `column-name:"priceRangeHigh"`
	Currency       string `column-name:"currency"`
	Exchange       string `column-name:"exchange"`
}

type IncomeStatementQuery url.Values

func QueryIncomeStatement(apiKey, symbol string) IncomeStatementQuery {
	return IncomeStatementQuery{"function": []string{"INCOME_STATEMENT"}, "symbol": []string{symbol}, "apikey": []string{apiKey}}
}

func (q IncomeStatementQuery) Encode() string {
	return url.Values(q).Encode()
}

type ListingStatusQuery url.Values

func QueryListingStatus(apiKey string) ListingStatusQuery {
	return ListingStatusQuery{"function": []string{"LISTING_STATUS"}, "apikey": []string{apiKey}}
}

func (query ListingStatusQuery) Date(value string) ListingStatusQuery {
	query["date"] = []string{value}
	return query
}

func (query ListingStatusQuery) StateActive() ListingStatusQuery {
	query["state"] = []string{"active"}
	return query
}

func (query ListingStatusQuery) StateDelisted() ListingStatusQuery {
	query["state"] = []string{"delisted"}
	return query
}

func (query ListingStatusQuery) State(value string) ListingStatusQuery {
	query["state"] = []string{value}
	return query
}

func (q ListingStatusQuery) Encode() string {
	return url.Values(q).Encode()
}

type ListingStatusRow struct {
	Symbol        string `column-name:"symbol"`
	Name          string `column-name:"name"`
	Exchange      string `column-name:"exchange"`
	AssetType     string `column-name:"assetType"`
	IPODate       string `column-name:"ipoDate"`
	DelistingDate string `column-name:"delistingDate"`
	Status        string `column-name:"status"`
}

type OverviewQuery url.Values

func QueryOverview(apiKey, symbol string) OverviewQuery {
	return OverviewQuery{"function": []string{"OVERVIEW"}, "symbol": []string{symbol}, "apikey": []string{apiKey}}
}

func (q OverviewQuery) Encode() string {
	return url.Values(q).Encode()
}

type SharesOutstandingQuery url.Values

func QuerySharesOutstanding(apiKey, symbol string) SharesOutstandingQuery {
	return SharesOutstandingQuery{"function": []string{"SHARES_OUTSTANDING"}, "symbol": []string{symbol}, "apikey": []string{apiKey}}
}

func (query SharesOutstandingQuery) DataTypeCSV() SharesOutstandingQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query SharesOutstandingQuery) DataTypeJSON() SharesOutstandingQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query SharesOutstandingQuery) DataType(value string) SharesOutstandingQuery {
	query["datatype"] = []string{value}
	return query
}

func (q SharesOutstandingQuery) Encode() string {
	return url.Values(q).Encode()
}

type SharesOutstandingRow struct {
	Date                     string `column-name:"date"`
	SharesOutstandingDiluted string `column-name:"shares_outstanding_diluted"`
	SharesOutstandingBasic   string `column-name:"shares_outstanding_basic"`
}

type SplitsQuery url.Values

func QuerySplits(apiKey, symbol string) SplitsQuery {
	return SplitsQuery{"function": []string{"SPLITS"}, "symbol": []string{symbol}, "apikey": []string{apiKey}}
}

func (query SplitsQuery) DataTypeCSV() SplitsQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query SplitsQuery) DataTypeJSON() SplitsQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query SplitsQuery) DataType(value string) SplitsQuery {
	query["datatype"] = []string{value}
	return query
}

func (q SplitsQuery) Encode() string {
	return url.Values(q).Encode()
}

type SplitsRow struct {
	EffectiveDate string `column-name:"effective_date"`
	SplitFactor   string `column-name:"split_factor"`
}
