package main

import (
	"bytes"
	"cmp"
	"encoding/json"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"net/url"
	"os"
	"path"
	"path/filepath"
	"slices"
	"strconv"
	"strings"

	"github.com/portfoliotree/alphavantage/specification"
)

const (
	generateComment = "// Code generated by av-generate; DO NOT EDIT."
)

func main() {
	idsBuf, err := os.ReadFile(filepath.FromSlash("specification/identifiers.json"))
	if err != nil {
		panic(err)
	}
	var goIdentifiers map[string][]string
	if err := json.Unmarshal(idsBuf, &goIdentifiers); err != nil {
		panic(err)
	}

	qpBuf, err := os.ReadFile(filepath.FromSlash("specification/query_parameters.json"))
	if err != nil {
		panic(err)
	}
	var queryParams []specification.QueryParameter
	if err := json.Unmarshal(qpBuf, &queryParams); err != nil {
		panic(err)
	}

	filePaths, err := filepath.Glob(filepath.FromSlash("specification/functions/*.json"))
	if err != nil {
		panic(err)
	}

	functionFiles := make(map[string][]specification.Function)

	for _, filePath := range filePaths {
		buf, err := os.ReadFile(filePath)
		if err != nil {
			panic(err)
		}
		var functions []specification.Function
		err = json.Unmarshal(buf, &functions)
		if err != nil {
			panic(err)
		}
		functionFiles[filePath] = functions
	}

	packages := map[string]string{
		"commodities":  "commodities.json",
		"crypto":       "crypto.json",
		"economic":     "economic.json",
		"options":      "options.json",
		"forex":        "forex.json",
		"fundamental":  "fundamental.json",
		"intelligence": "intelligence.json",
		"technical":    "technical_*.json",
		"timeseries":   "time_series.json",
	}

	for pkgName := range packages {
		if err := os.MkdirAll(filepath.Join("query", pkgName), 0755); err != nil && !os.IsExist(err) {
			panic(err)
		}
	}

	querierTypes := make(map[string]QuerierType)
	for filePath, functions := range functionFiles {
		baseFileName := strings.TrimSuffix(filepath.Base(filePath), ".json")

		var pkgName string
		for name, pattern := range packages {
			if ok, err := path.Match(pattern, filepath.Base(filePath)); err != nil {
				panic(err)
			} else if ok {
				pkgName = name
			}
		}
		if pkgName == "" {
			panic("package name not found in " + filePath)
		}

		slices.SortFunc(functions, func(a, b specification.Function) int {
			return cmp.Compare(goIdentifiers[a.Name][0], goIdentifiers[b.Name][0])
		})

		outFileName := filepath.Join("query", pkgName, baseFileName+".go")

		if err := generateFile(querierTypes, pkgName, outFileName, baseFileName, functions, goIdentifiers, queryParams); err != nil {
			panic(err)
		}
	}

	// Generate CLI functions.go
	if err := generateCLIFile(querierTypes, functionFiles, goIdentifiers, queryParams); err != nil {
		panic(err)
	}

	// Generate CLI test data
	if err := generateCLITestData(functionFiles); err != nil {
		panic(err)
	}

	buf, err := os.ReadFile(filepath.FromSlash("specification/testdata/examples/index.json"))
	if err != nil {
		panic(err)
	}
	var indexEntrees []specification.IndexEntree
	if err := json.Unmarshal(buf, &indexEntrees); err != nil {
		panic(err)
	}

	// Generate CSV parsing tests
	if err := generateCSVTests(querierTypes, functionFiles, goIdentifiers, indexEntrees); err != nil {
		panic(err)
	}

	// Generate client category helpers (functions.go)
	if err := generateClientHelpers(querierTypes, functionFiles, goIdentifiers, packages); err != nil {
		panic(err)
	}
}

type QuerierType struct {
	PackageIdent string
	PackagePath  string
	NewQueryFunc string
	QueryType    string
	RowType      string
}

func errNeqNil() *ast.BinaryExpr {
	return &ast.BinaryExpr{X: ast.NewIdent("err"), Op: token.NEQ, Y: ast.NewIdent("nil")}
}

func idExprList(ids ...string) []ast.Expr {
	list := make([]ast.Expr, 0, len(ids))
	for _, id := range ids {
		list = append(list, ast.NewIdent(id))
	}
	return list
}

func addTimeForColumnType(functions []specification.Function, imports []string) []string {
	for _, fn := range functions {
		for _, col := range fn.CSVColumns {
			if col.Type == "time" {
				return append(imports, "time")
			}
		}
	}
	return imports
}
func newField(tp ast.Expr, ident ...string) *ast.Field {
	var names []*ast.Ident
	for _, name := range ident {
		names = append(names, ast.NewIdent(name))
	}
	return &ast.Field{Names: names, Type: tp}
}

func newSel(x, sel string) *ast.SelectorExpr {
	return &ast.SelectorExpr{
		X:   ast.NewIdent(x),
		Sel: ast.NewIdent(sel),
	}
}

func newSet[T comparable](keys ...T) map[T]struct{} {
	m := make(map[T]struct{}, len(keys))
	for _, key := range keys {
		m[key] = struct{}{}
	}
	return m
}

func requireNoError() *ast.CallExpr {
	return &ast.CallExpr{
		Fun: newSel("require", "NoError"),
		Args: []ast.Expr{
			ast.NewIdent("t"),
			ast.NewIdent("err"),
		},
	}
}

func formatGo(node *ast.File, fileName string) error {
	var buf bytes.Buffer
	buf.WriteString(generateComment + "\n\n")
	if err := format.Node(&buf, token.NewFileSet(), node); err != nil {
		return err
	}
	result := buf.Bytes()
	result = bytes.ReplaceAll(result, []byte("}\nfunc"), []byte("}\n\nfunc"))
	result = bytes.ReplaceAll(result, []byte("}\ntype"), []byte("}\n\ntype"))

	fp := filepath.FromSlash(fileName)

	return os.WriteFile(fp, result, 0644)
}

func returnIdents(ids ...string) *ast.BlockStmt {
	return &ast.BlockStmt{
		List: []ast.Stmt{
			&ast.ReturnStmt{
				Results: idExprList(ids...),
			},
		},
	}
}

func stringBasicLiteral(str string) *ast.BasicLit {
	return &ast.BasicLit{Kind: token.STRING, Value: strconv.Quote(str)}
}

func generateFile(querierTypes map[string]QuerierType, pkgName, outFileName, baseFileName string, functions []specification.Function, goIdentifiers map[string][]string, queryParams []specification.QueryParameter) error {
	file := ast.File{
		Name: ast.NewIdent(pkgName),
	}
	importsDecl := &ast.GenDecl{
		Tok:   token.IMPORT,
		Specs: []ast.Spec{},
	}
	file.Decls = append(file.Decls, importsDecl)

	imports := []string{
		"net/url",
	}
	imports = addTimeForColumnType(functions, imports)

	for _, fn := range functions {
		goIdent := goIdentifier(goIdentifiers, pkgName, fn.Name)
		rowTypeIdent := goIdent + "Row"
		queryTypeIdent := goIdent + "Query"
		newQueryFunc := "Query" + goIdent
		packagePath := path.Join("github.com/portfoliotree/alphavantage", path.Dir(outFileName))

		file.Decls = append(file.Decls, &ast.GenDecl{
			Tok: token.TYPE,
			Specs: []ast.Spec{
				&ast.TypeSpec{
					Name: ast.NewIdent(queryTypeIdent),
					Type: newSel("url", "Values"),
				},
			},
		})
		queryFuncDecls, im, err := queryInitializerFunc(newQueryFunc, queryTypeIdent, fn, goIdentifiers, queryParams)
		if err != nil {
			return err
		}

		imports = append(imports, im...)
		slices.Sort(imports)
		imports = slices.Compact(imports)

		for _, fnDecl := range queryFuncDecls {
			file.Decls = append(file.Decls, fnDecl)
		}

		if len(fn.CSVColumns) == 0 {
			querierTypes[fn.Name] = QuerierType{
				PackageIdent: pkgName,
				PackagePath:  packagePath,
				QueryType:    queryTypeIdent,
				NewQueryFunc: newQueryFunc,
			}
			continue
		}
		querierTypes[fn.Name] = QuerierType{
			PackageIdent: pkgName,
			PackagePath:  packagePath,
			NewQueryFunc: newQueryFunc,
			QueryType:    queryTypeIdent,
			RowType:      rowTypeIdent,
		}

		file.Decls = append(file.Decls, &ast.GenDecl{
			Tok: token.TYPE,
			Specs: []ast.Spec{
				&ast.TypeSpec{
					Name: ast.NewIdent(rowTypeIdent),
					Type: &ast.StructType{
						Fields: csvFields(baseFileName, fn, goIdentifiers),
					},
				},
			},
		})
	}

	if len(file.Decls) <= 1 {
		return nil
	}

	slices.Sort(imports)
	imports = slices.Compact(imports)
	for _, im := range imports {
		importsDecl.Specs = append(importsDecl.Specs, &ast.ImportSpec{Path: stringBasicLiteral(im)})
	}

	return formatGo(&file, outFileName)
}

func goIdentifier(goIdents map[string][]string, pkgName, name string) string {
	val := goIdents[name][0]
	if idx := strings.Index(strings.ToLower(val), pkgName); idx >= 0 {
		val = val[:idx] + val[idx+len(pkgName):]
	}
	if strings.HasPrefix(val, "FX") {
		val = strings.TrimPrefix(val, "FX")
	}
	return val
}

func queryInitializerFunc(funcName, queryTypeIdent string, fn specification.Function, goIdentifiers map[string][]string, queryParams []specification.QueryParameter) ([]*ast.FuncDecl, []string, error) {
	requiredFields := &ast.Field{
		Type: ast.NewIdent("string"),
	}
	if slices.Contains(fn.Required, "apikey") {
		requiredFields.Names = append(requiredFields.Names, ast.NewIdent(goIdentifiers["apikey"][1]))
	}

	elements := []ast.Expr{
		&ast.KeyValueExpr{
			Key: stringBasicLiteral("function"),
			Value: &ast.CompositeLit{
				Type: &ast.ArrayType{Elt: ast.NewIdent("string")},
				Elts: []ast.Expr{stringBasicLiteral(fn.Name)},
			},
		},
	}

	for _, req := range fn.Required {
		switch req {
		case "function":
		default:
			requiredFields.Names = append(requiredFields.Names, ast.NewIdent(goIdentifiers[req][1]))
			fallthrough
		case "apikey":
			elements = append(elements, &ast.KeyValueExpr{
				Key: stringBasicLiteral(req),
				Value: &ast.CompositeLit{
					Type: &ast.ArrayType{Elt: ast.NewIdent("string")},
					Elts: []ast.Expr{ast.NewIdent(goIdentifiers[req][1])},
				},
			})
		}
	}

	decls := []*ast.FuncDecl{
		{
			Name: ast.NewIdent(funcName),
			Type: &ast.FuncType{
				Params:  &ast.FieldList{List: []*ast.Field{requiredFields}},
				Results: &ast.FieldList{List: []*ast.Field{newField(ast.NewIdent(queryTypeIdent))}},
			},
			Body: &ast.BlockStmt{
				List: []ast.Stmt{
					&ast.ReturnStmt{
						Results: []ast.Expr{
							&ast.CompositeLit{
								Type: ast.NewIdent(queryTypeIdent),
								Elts: elements,
							},
						},
					},
				},
			},
		},
	}

	var imports []string

	for _, opt := range fn.Optional {
		var methodName string
		switch opt {
		case "OHLC":
			methodName = "OHLC"
		default:
			ids, ok := goIdentifiers[opt]
			if ok {
				methodName = ids[0]
			} else {
				panic("unknown option: " + opt)
			}
		}

		if idx := slices.IndexFunc(queryParams, func(p specification.QueryParameter) bool {
			return p.Name == opt
		}); idx >= 0 {
			qp := queryParams[idx]
			switch qp.Type {
			case "enum":
				for _, val := range qp.Values {
					s, err := val.Name()
					if err != nil {
						return nil, nil, fmt.Errorf("failed to get name for query param key %s: %w", opt, err)
					}
					valueIdent, ok := goIdentifiers[s]
					if ok {
						decls = append(decls, queryUpdateMethod(queryTypeIdent, methodName+valueIdent[0], opt,
							[]*ast.Field{},
							&ast.CompositeLit{
								Type: &ast.ArrayType{Elt: ast.NewIdent("string")},
								Elts: []ast.Expr{stringBasicLiteral(s)},
							},
						))
					}
				}
			case "bool":
				decls = append(decls, queryUpdateMethod(queryTypeIdent, methodName, opt,
					[]*ast.Field{newField(ast.NewIdent("bool"), "value")},
					&ast.CompositeLit{
						Type: &ast.ArrayType{Elt: ast.NewIdent("string")},
						Elts: []ast.Expr{&ast.CallExpr{
							Fun:  &ast.SelectorExpr{X: ast.NewIdent("strconv"), Sel: ast.NewIdent("FormatBool")},
							Args: []ast.Expr{ast.NewIdent("value")},
						}},
					},
				))
				imports = append(imports, "strconv")
				continue
			case "time":
				if qp.Format != "" {
					decls = append(decls, queryUpdateMethod(queryTypeIdent, methodName, opt,
						[]*ast.Field{newField(newSel("time", "Time"), "value")},
						&ast.CompositeLit{
							Type: &ast.ArrayType{Elt: ast.NewIdent("string")},
							Elts: []ast.Expr{&ast.CallExpr{
								Fun:  newSel("value", "Format"),
								Args: []ast.Expr{stringBasicLiteral(qp.Format)},
							}},
						},
					))
					imports = append(imports, "time")
				}
				continue
			}
		}
		decls = append(decls, queryUpdateMethod(queryTypeIdent, methodName, opt,
			[]*ast.Field{newField(ast.NewIdent("string"), "value")},
			&ast.CompositeLit{
				Type: &ast.ArrayType{Elt: ast.NewIdent("string")},
				Elts: []ast.Expr{ast.NewIdent("value")},
			},
		))
	}

	slices.Sort(imports)
	imports = slices.Compact(imports)

	decls = append(decls, &ast.FuncDecl{
		Name: ast.NewIdent("Encode"),
		Type: &ast.FuncType{
			Results: &ast.FieldList{List: []*ast.Field{
				{Type: ast.NewIdent("string")},
			}},
		},
		Recv: &ast.FieldList{List: []*ast.Field{
			newField(ast.NewIdent(queryTypeIdent), "q"),
		}},
		Body: &ast.BlockStmt{
			List: []ast.Stmt{
				&ast.ReturnStmt{Results: []ast.Expr{&ast.CallExpr{
					Fun: &ast.SelectorExpr{
						X:   &ast.CallExpr{Fun: newSel("url", "Values"), Args: []ast.Expr{ast.NewIdent("q")}},
						Sel: ast.NewIdent("Encode"),
					},
				}}},
			},
		},
	})

	return decls, imports, nil
}

func queryUpdateMethod(queryTypeIdent, methodName, keyName string, params []*ast.Field, expr ast.Expr) *ast.FuncDecl {
	return &ast.FuncDecl{
		Name: ast.NewIdent(methodName),
		Recv: &ast.FieldList{List: []*ast.Field{newField(ast.NewIdent(queryTypeIdent), "query")}},
		Type: &ast.FuncType{
			Params:  &ast.FieldList{List: params},
			Results: &ast.FieldList{List: []*ast.Field{{Type: ast.NewIdent(queryTypeIdent)}}},
		},
		Body: &ast.BlockStmt{
			List: []ast.Stmt{
				&ast.AssignStmt{
					Lhs: []ast.Expr{
						&ast.IndexExpr{
							X:     ast.NewIdent("query"),
							Index: stringBasicLiteral(keyName),
						},
					},
					Tok: token.ASSIGN,
					Rhs: []ast.Expr{expr},
				},
				&ast.ReturnStmt{Results: []ast.Expr{ast.NewIdent("query")}},
			},
		},
	}
}

func csvFields(baseFileName string, fn specification.Function, goIdentifiers map[string][]string) *ast.FieldList {
	if strings.HasPrefix(baseFileName, "technical_") && len(fn.CSVColumns) == 2 {
		return &ast.FieldList{
			List: []*ast.Field{
				{
					Names: []*ast.Ident{ast.NewIdent(goIdentifiers[fn.CSVColumns[0].Name][0])},
					Type:  ast.NewIdent("string"),
					Tag: &ast.BasicLit{
						Kind:  token.STRING,
						Value: "`" + fmt.Sprintf(`column-name:%q`, fn.CSVColumns[0].Name) + "`",
					},
				},
				{
					Names: []*ast.Ident{ast.NewIdent("Value")},
					Type:  ast.NewIdent("string"),
					Tag: &ast.BasicLit{
						Kind:  token.STRING,
						Value: "`" + fmt.Sprintf(`column-name:%q`, fn.CSVColumns[1].Name) + "`",
					},
				},
			},
		}
	}

	fields := ast.FieldList{}
	for _, col := range fn.CSVColumns {
		fieldName := col.Name
		if fieldName == fn.Name {
			fieldName = "Value"
		} else {
			ns, ok := goIdentifiers[fieldName]
			if ok {
				fieldName = ns[0]
			}
		}
		var (
			fieldType ast.Expr
			tag       string
		)
		switch col.Type {
		case "string", "float64", "int":
			fieldType = ast.Expr(ast.NewIdent(col.Type))
			tag = "`" + fmt.Sprintf(`column-name:%q`, col.Name) + "`"
		case "time":
			fieldType = newSel("time", "Time")
			if col.Format != "" {
				tag = "`" + fmt.Sprintf(`column-name:%q time-layout:%q`, col.Name, col.Format) + "`"
			}

		default:
			panic(fmt.Sprintf("unsupported column type %q for function %q", col.Type, fn.Name))
		}

		fields.List = append(fields.List, &ast.Field{
			Names: []*ast.Ident{ast.NewIdent(fieldName)},
			Type:  fieldType,
			Tag: &ast.BasicLit{
				Kind:  token.STRING,
				Value: tag,
			},
		})
	}
	return &fields
}

func generateCLIFile(querierTypes map[string]QuerierType, functionFiles map[string][]specification.Function, goIdentifiers map[string][]string, queryParams []specification.QueryParameter) error {
	var allFunctions []specification.Function
	for _, functions := range functionFiles {
		allFunctions = append(allFunctions, functions...)
	}

	slices.SortFunc(allFunctions, func(a, b specification.Function) int { return cmp.Compare(a.Name, b.Name) })

	file := &ast.File{Name: ast.NewIdent("main")}

	importsMap := newSet("context", "fmt", "io")

	var caseClauses []ast.Stmt
	for _, fn := range allFunctions {
		caseClauses = append(caseClauses,
			&ast.CaseClause{
				List: []ast.Expr{
					stringBasicLiteral(fn.Name),
					stringBasicLiteral(strings.ToLower(strings.Replace(fn.Name, "_", "-", -1))),
				},
				Body: []ast.Stmt{
					&ast.ReturnStmt{
						Results: []ast.Expr{
							&ast.CallExpr{
								Fun:  ast.NewIdent("handle" + goIdentifiers[fn.Name][0]),
								Args: idExprList("client", "args", "output"),
							},
						},
					},
				},
			},
		)
	}

	caseClauses = append(caseClauses, &ast.CaseClause{
		List: nil, // default case
		Body: []ast.Stmt{
			&ast.ReturnStmt{
				Results: []ast.Expr{
					&ast.CallExpr{
						Fun: newSel("fmt", "Errorf"),
						Args: []ast.Expr{
							stringBasicLiteral("unknown function: %s"),
							ast.NewIdent("functionName"),
						},
					},
				},
			},
		},
	})

	runFunctionDecl := &ast.FuncDecl{
		Doc: &ast.CommentGroup{
			List: []*ast.Comment{
				{Text: "// runFunction executes the specified AlphaVantage API function with the given arguments."},
			},
		},
		Name: ast.NewIdent("runFunction"),
		Type: &ast.FuncType{
			Params: &ast.FieldList{
				List: []*ast.Field{
					newField(&ast.StarExpr{X: newSel("alphavantage", "Client")}, "client"),
					newField(ast.NewIdent("string"), "functionName"),
					newField(&ast.ArrayType{Elt: ast.NewIdent("string")}, "args"),
					newField(newSel("io", "Writer"), "output"),
				},
			},
			Results: &ast.FieldList{
				List: []*ast.Field{{Type: ast.NewIdent("error")}},
			},
		},
		Body: &ast.BlockStmt{
			List: []ast.Stmt{
				&ast.SwitchStmt{
					Tag:  ast.NewIdent("functionName"),
					Body: &ast.BlockStmt{List: caseClauses},
				},
			},
		},
	}

	file.Decls = append(file.Decls, runFunctionDecl)

	for _, fn := range allFunctions {
		funcDecl, fnImports, err := generateHandlerFunction(fn, querierTypes[fn.Name], goIdentifiers, queryParams)
		if err != nil {
			return err
		}
		file.Decls = append(file.Decls, funcDecl)

		for _, imp := range fnImports {
			importsMap[imp] = struct{}{}
		}
	}

	var (
		importSpecs []ast.Spec
		imports     []string
	)
	for imp := range importsMap {
		imports = append(imports, imp)
	}
	slices.Sort(imports)
	imports = append(imports, "github.com/spf13/pflag", "github.com/portfoliotree/alphavantage")

	var querierPackages []string
	for _, id := range querierTypes {
		if id.PackagePath == "" {
			continue
		}
		querierPackages = append(querierPackages, id.PackagePath)
		slices.Sort(querierPackages)
		querierPackages = slices.Compact(querierPackages)
	}
	imports = append(imports, querierPackages...)

	for _, imp := range imports {
		importSpecs = append(importSpecs, &ast.ImportSpec{
			Path: stringBasicLiteral(imp),
		})
	}

	if len(importSpecs) > 0 {
		file.Decls = append([]ast.Decl{
			&ast.GenDecl{
				Tok:   token.IMPORT,
				Specs: importSpecs,
			},
		}, file.Decls...)
	}

	return formatGo(file, "cmd/av/functions.go")
}

func generateHandlerFunction(fn specification.Function, qt QuerierType, goIdentifiers map[string][]string, queryParams []specification.QueryParameter) (*ast.FuncDecl, []string, error) {
	goIdent := goIdentifiers[fn.Name][0]

	var (
		imports []string
		body    []ast.Stmt
	)

	body = append(body, &ast.AssignStmt{
		Lhs: []ast.Expr{ast.NewIdent("flags")},
		Tok: token.DEFINE,
		Rhs: []ast.Expr{
			&ast.CallExpr{
				Fun: newSel("pflag", "NewFlagSet"),
				Args: []ast.Expr{
					stringBasicLiteral(fn.Name),
					newSel("pflag", "ContinueOnError"),
				},
			},
		},
	})

	for _, paramName := range append(fn.Required, fn.Optional...) {
		if paramName == "function" || paramName == "apikey" {
			continue
		}

		varName := goIdentifiers[paramName][1]
		flagName := strings.Replace(paramName, "_", "-", -1)
		flagName = strings.ToLower(flagName)

		paramType := "string"
		var usage string
		for _, qp := range queryParams {
			if qp.Name == paramName {
				paramType = qp.Type
				if qp.Type == "enum" {
					var enumValues []string
					for _, v := range qp.Values {
						val, _ := v.Name()
						if fn.EnumSubset != nil {
							if subset, ok := fn.EnumSubset[paramName]; ok {
								if !slices.Contains(subset, val) {
									continue
								}
							}
						}
						enumValues = append(enumValues, val)
					}
					if len(enumValues) > 0 {
						usage = "options: " + strings.Join(enumValues, ", ")
					}
				}
				break
			}
		}

		if slices.Contains(fn.Required, paramName) {
			usage = "[REQUIRED] " + usage
		}

		var (
			varType      ast.Expr
			flagMethod   string
			defaultValue ast.Expr
		)

		switch paramType {
		case "bool":
			varType = ast.NewIdent("bool")
			flagMethod = "BoolVar"
			defaultValue = ast.NewIdent("false")
		case "int":
			varType = ast.NewIdent("int")
			flagMethod = "IntVar"
			defaultValue = &ast.BasicLit{Kind: token.INT, Value: "0"}
		default:
			varType = ast.NewIdent("string")
			flagMethod = "StringVar"
			defaultValue = &ast.BasicLit{Kind: token.STRING, Value: `""`}
		}

		body = append(body, &ast.DeclStmt{
			Decl: &ast.GenDecl{
				Tok: token.VAR,
				Specs: []ast.Spec{
					&ast.ValueSpec{
						Names: []*ast.Ident{ast.NewIdent(varName)},
						Type:  varType,
					},
				},
			},
		})

		body = append(body, &ast.ExprStmt{
			X: &ast.CallExpr{
				Fun: newSel("flags", flagMethod),
				Args: []ast.Expr{
					&ast.UnaryExpr{Op: token.AND, X: ast.NewIdent(varName)},
					stringBasicLiteral(flagName),
					defaultValue,
					stringBasicLiteral(strings.TrimSpace(usage)),
				},
			},
		})
	}

	body = append(body, &ast.IfStmt{
		Init: &ast.AssignStmt{
			Lhs: []ast.Expr{ast.NewIdent("err")},
			Tok: token.DEFINE,
			Rhs: []ast.Expr{
				&ast.CallExpr{
					Fun:  newSel("flags", "Parse"),
					Args: []ast.Expr{ast.NewIdent("args")},
				},
			},
		},
		Cond: errNeqNil(),
		Body: returnIdents("err"),
	})

	for _, paramName := range fn.Required {
		if paramName == "function" || paramName == "apikey" {
			continue
		}

		varName := goIdentifiers[paramName][1]
		flagName := strings.Replace(paramName, "_", "-", -1)
		flagName = strings.ToLower(flagName)

		paramType := "string"
		for _, qp := range queryParams {
			if qp.Name == paramName {
				paramType = qp.Type
				break
			}
		}

		if paramType == "bool" {
			continue
		}

		var cond ast.Expr
		if paramType == "int" {
			cond = &ast.BinaryExpr{
				X:  ast.NewIdent(varName),
				Op: token.EQL,
				Y:  &ast.BasicLit{Kind: token.INT, Value: "0"},
			}
		} else {
			cond = &ast.BinaryExpr{
				X:  ast.NewIdent(varName),
				Op: token.EQL,
				Y:  &ast.BasicLit{Kind: token.STRING, Value: `""`},
			}
		}

		body = append(body, &ast.IfStmt{
			Cond: cond,
			Body: &ast.BlockStmt{
				List: []ast.Stmt{
					&ast.ReturnStmt{
						Results: []ast.Expr{
							&ast.CallExpr{
								Fun: newSel("fmt", "Errorf"),
								Args: []ast.Expr{
									&ast.BasicLit{
										Kind:  token.STRING,
										Value: strconv.Quote(fmt.Sprintf("required flag --%s not set", flagName)),
									},
								},
							},
						},
					},
				},
			},
		})
	}

	queryArgs := []ast.Expr{newSel("client", "APIKey")}
	needsStrconv := false

	for _, paramName := range fn.Required {
		if paramName == "function" || paramName == "apikey" {
			continue
		}

		varName := goIdentifiers[paramName][1]

		paramType := "string"
		for _, qp := range queryParams {
			if qp.Name == paramName {
				paramType = qp.Type
				break
			}
		}

		if paramType == "int" {
			needsStrconv = true
			queryArgs = append(queryArgs, &ast.CallExpr{
				Fun:  newSel("strconv", "Itoa"),
				Args: []ast.Expr{ast.NewIdent(varName)},
			})
		} else {
			queryArgs = append(queryArgs, ast.NewIdent(varName))
		}
	}

	body = append(body, &ast.AssignStmt{
		Lhs: []ast.Expr{ast.NewIdent("query")},
		Tok: token.DEFINE,
		Rhs: []ast.Expr{
			&ast.CallExpr{
				Fun:  newSel(qt.PackageIdent, qt.NewQueryFunc),
				Args: queryArgs,
			},
		},
	})

	for _, paramName := range fn.Optional {
		varName := goIdentifiers[paramName][1]
		methodName := goIdentifiers[paramName][0]

		if paramName == "OHLC" {
			methodName = "OHLC"
		}

		paramType := "string"
		for _, qp := range queryParams {
			if qp.Name == paramName {
				paramType = qp.Type
				break
			}
		}

		var (
			cond       ast.Expr
			methodArg  ast.Expr
			innerStmts []ast.Stmt
		)

		switch paramType {
		case "bool":
			cond = ast.NewIdent(varName)
			methodArg = ast.NewIdent(varName)
			innerStmts = []ast.Stmt{
				&ast.AssignStmt{
					Lhs: []ast.Expr{ast.NewIdent("query")},
					Tok: token.ASSIGN,
					Rhs: []ast.Expr{
						&ast.CallExpr{
							Fun:  newSel("query", methodName),
							Args: []ast.Expr{methodArg},
						},
					},
				},
			}
		case "int":
			needsStrconv = true
			cond = &ast.BinaryExpr{
				X: ast.NewIdent(varName), Op: token.NEQ, Y: &ast.BasicLit{Kind: token.INT, Value: "0"},
			}
			methodArg = &ast.CallExpr{
				Fun:  newSel("strconv", "Itoa"),
				Args: []ast.Expr{ast.NewIdent(varName)},
			}
			innerStmts = []ast.Stmt{
				&ast.AssignStmt{
					Lhs: idExprList("query"),
					Tok: token.ASSIGN,
					Rhs: []ast.Expr{
						&ast.CallExpr{
							Fun: &ast.SelectorExpr{
								X:   ast.NewIdent("query"),
								Sel: ast.NewIdent(methodName),
							},
							Args: []ast.Expr{methodArg},
						},
					},
				},
			}
		case "time":
			imports = append(imports, "time")
			cond = &ast.BinaryExpr{
				X: ast.NewIdent(varName), Op: token.NEQ, Y: &ast.BasicLit{Kind: token.STRING, Value: `""`},
			}
			innerStmts = []ast.Stmt{
				&ast.AssignStmt{
					Lhs: []ast.Expr{ast.NewIdent("t"), ast.NewIdent("err")},
					Tok: token.DEFINE,
					Rhs: []ast.Expr{
						&ast.CallExpr{
							Fun: newSel("time", "Parse"),
							Args: []ast.Expr{
								stringBasicLiteral("2006-01"),
								ast.NewIdent(varName),
							},
						},
					},
				},
				&ast.IfStmt{
					Cond: errNeqNil(),
					Body: &ast.BlockStmt{
						List: []ast.Stmt{
							&ast.ReturnStmt{
								Results: []ast.Expr{
									&ast.CallExpr{
										Fun: newSel("fmt", "Errorf"),
										Args: []ast.Expr{
											&ast.BasicLit{
												Kind:  token.STRING,
												Value: strconv.Quote(fmt.Sprintf("invalid %s format: %%w", paramName)),
											},
											ast.NewIdent("err"),
										},
									},
								},
							},
						},
					},
				},
				&ast.AssignStmt{
					Lhs: idExprList("query"),
					Tok: token.ASSIGN,
					Rhs: []ast.Expr{
						&ast.CallExpr{
							Fun:  newSel("query", methodName),
							Args: []ast.Expr{ast.NewIdent("t")},
						},
					},
				},
			}
		default:
			cond = &ast.BinaryExpr{
				X: ast.NewIdent(varName), Op: token.NEQ, Y: &ast.BasicLit{Kind: token.STRING, Value: `""`},
			}
			methodArg = ast.NewIdent(varName)
			innerStmts = []ast.Stmt{
				&ast.AssignStmt{
					Lhs: []ast.Expr{ast.NewIdent("query")},
					Tok: token.ASSIGN,
					Rhs: []ast.Expr{
						&ast.CallExpr{
							Fun:  newSel("query", methodName),
							Args: []ast.Expr{methodArg},
						},
					},
				},
			}
		}

		body = append(body, &ast.IfStmt{
			Cond: cond,
			Body: &ast.BlockStmt{List: innerStmts},
		})
	}

	imports = append(imports, "context")
	body = append(body, &ast.AssignStmt{
		Lhs: []ast.Expr{ast.NewIdent("ctx")},
		Tok: token.DEFINE,
		Rhs: []ast.Expr{
			&ast.CallExpr{
				Fun: newSel("context", "Background"),
			},
		},
	})

	body = append(body, &ast.AssignStmt{
		Lhs: []ast.Expr{ast.NewIdent("res"), ast.NewIdent("err")},
		Tok: token.DEFINE,
		Rhs: []ast.Expr{
			&ast.CallExpr{
				Fun: newSel("client", "Query"),
				Args: []ast.Expr{
					ast.NewIdent("ctx"),
					ast.NewIdent("query"),
				},
			},
		},
	})

	body = append(body, &ast.IfStmt{
		Cond: errNeqNil(),
		Body: &ast.BlockStmt{
			List: []ast.Stmt{
				&ast.ReturnStmt{
					Results: []ast.Expr{
						&ast.CallExpr{
							Fun: newSel("fmt", "Errorf"),
							Args: []ast.Expr{
								stringBasicLiteral("API request failed: %w"),
								ast.NewIdent("err"),
							},
						},
					},
				},
			},
		},
	})

	body = append(body, &ast.DeferStmt{
		Call: &ast.CallExpr{
			Fun: &ast.SelectorExpr{
				X:   newSel("res", "Body"),
				Sel: ast.NewIdent("Close"),
			},
		},
	})

	imports = append(imports, "io")
	body = append(body, &ast.IfStmt{
		Init: &ast.AssignStmt{
			Lhs: idExprList("_", "err"),
			Tok: token.DEFINE,
			Rhs: []ast.Expr{
				&ast.CallExpr{
					Fun: newSel("io", "Copy"),
					Args: []ast.Expr{
						ast.NewIdent("output"),
						newSel("res", "Body"),
					},
				},
			},
		},
		Cond: errNeqNil(),
		Body: &ast.BlockStmt{
			List: []ast.Stmt{
				&ast.ReturnStmt{
					Results: []ast.Expr{
						&ast.CallExpr{
							Fun: newSel("fmt", "Errorf"),
							Args: []ast.Expr{
								stringBasicLiteral("failed to write response: %w"),
								ast.NewIdent("err"),
							},
						},
					},
				},
			},
		},
	})

	body = append(body, &ast.ReturnStmt{Results: []ast.Expr{ast.NewIdent("nil")}})

	if needsStrconv {
		imports = append(imports, "strconv")
	}

	funcDecl := &ast.FuncDecl{
		Name: ast.NewIdent("handle" + goIdent),
		Type: &ast.FuncType{
			Params: &ast.FieldList{
				List: []*ast.Field{
					newField(&ast.StarExpr{X: newSel("alphavantage", "Client")}, "client"),
					newField(&ast.ArrayType{Elt: ast.NewIdent("string")}, "args"),
					newField(newSel("io", "Writer"), "output"),
				},
			},
			Results: &ast.FieldList{
				List: []*ast.Field{
					{Type: ast.NewIdent("error")},
				},
			},
		},
		Body: &ast.BlockStmt{
			List: body,
		},
	}

	return funcDecl, imports, nil
}

func generateCLITestData(functionFiles map[string][]specification.Function) error {
	type indexEntry struct {
		ID      string `json:"ID"`
		Path    string `json:"path"`
		Fetched string `json:"fetched"`
		URL     string `json:"url"`
	}

	type testCase struct {
		Name string   `json:"name"`
		Args []string `json:"args"`
	}

	indexPath := filepath.FromSlash("specification/testdata/examples/index.json")
	indexData, err := os.ReadFile(indexPath)
	if err != nil {
		return fmt.Errorf("failed to read index.json: %w", err)
	}

	var index []indexEntry
	if err := json.Unmarshal(indexData, &index); err != nil {
		return fmt.Errorf("failed to parse index.json: %w", err)
	}

	urlToID := make(map[string]string)
	for _, entry := range index {
		parsedURL, err := url.Parse(entry.URL)
		if err != nil {
			continue
		}
		query := parsedURL.Query()
		query.Del("apikey")
		parsedURL.RawQuery = query.Encode()
		urlToID[parsedURL.String()] = entry.ID
	}

	var testCases []testCase
	for _, functions := range functionFiles {
		for _, fn := range functions {
			if len(fn.Examples) == 0 {
				continue
			}

			exampleURL := fn.Examples[0]
			parsedURL, err := url.Parse(exampleURL)
			if err != nil {
				continue
			}

			queryForLookup := parsedURL.Query()
			queryForLookup.Del("apikey")
			parsedURL.RawQuery = queryForLookup.Encode()
			testID, ok := urlToID[parsedURL.String()]
			if !ok {
				testID = fn.Name
			}

			var args []string
			query := parsedURL.Query()
			args = append(args, fn.Name)

			keys := make([]string, 0, len(query))
			for key := range query {
				if key == "function" || key == "apikey" {
					continue
				}
				keys = append(keys, key)
			}
			slices.Sort(keys)

			for _, key := range keys {
				values := query[key]
				flagName := strings.Replace(key, "_", "-", -1)
				flagName = strings.ToLower(flagName)
				if len(values) > 1 {
					args = append(args, fmt.Sprintf("--%s=%s", flagName, strings.Join(values, ",")))
				} else if len(values) == 1 {
					args = append(args, fmt.Sprintf("--%s=%s", flagName, values[0]))
				}
			}

			testCases = append(testCases, testCase{
				Name: testID,
				Args: args,
			})
		}
	}

	slices.SortFunc(testCases, func(a, b testCase) int {
		return cmp.Compare(a.Name, b.Name)
	})

	data, err := json.MarshalIndent(testCases, "", "  ")
	if err != nil {
		return fmt.Errorf("failed to marshal test data: %w", err)
	}

	outputPath := filepath.FromSlash("cmd/av/testdata/args.json")
	if err := os.MkdirAll(filepath.Dir(outputPath), 0755); err != nil {
		return fmt.Errorf("failed to create testdata directory: %w", err)
	}
	if err := os.WriteFile(outputPath, data, 0644); err != nil {
		return fmt.Errorf("failed to write test data: %w", err)
	}

	return nil
}

func generateCSVTests(querierTypes map[string]QuerierType, functionFiles map[string][]specification.Function, goIdentifiers map[string][]string, indexEntrees []specification.IndexEntree) error {
	file := ast.File{
		Name: ast.NewIdent("api_test"),
	}
	importsDecl := &ast.GenDecl{
		Tok:   token.IMPORT,
		Specs: []ast.Spec{},
	}
	file.Decls = append(file.Decls, importsDecl)

	imports := []string{
		"bytes",
		"testing",
		"os",
		"path/filepath",
	}

	slices.Sort(imports)
	imports = slices.Compact(imports)
	imports = append(imports,
		"github.com/stretchr/testify/require",
		"github.com/portfoliotree/alphavantage/api")

	testFunc := &ast.FuncDecl{
		Name: ast.NewIdent("TestCSV"),
		Type: &ast.FuncType{
			Params: &ast.FieldList{
				List: []*ast.Field{newField(&ast.StarExpr{X: newSel("testing", "T")}, "t")},
			},
		},
		Body: &ast.BlockStmt{},
	}
	file.Decls = append(file.Decls, testFunc)

	for _, entree := range indexEntrees {
		u, err := url.Parse(entree.URL)
		if err != nil {
			return err
		}
		functionName := u.Query().Get("function")

		for _, functions := range functionFiles {
			for _, fn := range functions {
				qt := querierTypes[fn.Name]
				if fn.Name != functionName || len(fn.CSVColumns) == 0 || path.Ext(entree.Path) != ".csv" {
					continue
				}
				imports = append(imports, qt.PackagePath)
				slices.Sort(imports)
				imports = slices.Compact(imports)
				testFunc.Body.List = append(testFunc.Body.List, &ast.ExprStmt{X: &ast.CallExpr{
					Fun: newSel("t", "Run"),
					Args: []ast.Expr{
						stringBasicLiteral(entree.ID),
						&ast.FuncLit{
							Type: &ast.FuncType{
								Params: &ast.FieldList{
									List: []*ast.Field{newField(&ast.StarExpr{X: newSel("testing", "T")}, "t")},
								},
							},
							Body: &ast.BlockStmt{
								List: []ast.Stmt{
									&ast.AssignStmt{
										Lhs: []ast.Expr{ast.NewIdent("buf"), ast.NewIdent("err")},
										Tok: token.DEFINE,
										Rhs: []ast.Expr{&ast.CallExpr{
											Fun: newSel("os", "ReadFile"),
											Args: []ast.Expr{
												&ast.CallExpr{
													Fun:  newSel("filepath", "FromSlash"),
													Args: []ast.Expr{stringBasicLiteral(path.Join("../specification", entree.Path))},
												},
											},
										}},
									},
									&ast.ExprStmt{X: requireNoError()},
									&ast.DeclStmt{
										Decl: &ast.GenDecl{
											Tok: token.VAR,
											Specs: []ast.Spec{
												&ast.ValueSpec{
													Names: []*ast.Ident{ast.NewIdent("rows")},
													Type: &ast.ArrayType{
														Elt: newSel(qt.PackageIdent, qt.RowType),
													},
												},
											},
										},
									},
									&ast.AssignStmt{
										Lhs: []ast.Expr{ast.NewIdent("err")},
										Tok: token.ASSIGN,
										Rhs: []ast.Expr{&ast.CallExpr{
											Fun: newSel("api", "ParseCSV"),
											Args: []ast.Expr{
												&ast.CallExpr{Fun: newSel("bytes", "NewReader"), Args: []ast.Expr{ast.NewIdent("buf")}},
												&ast.UnaryExpr{Op: token.AND, X: ast.NewIdent("rows")},
												ast.NewIdent("nil"),
											},
										}},
									},
									&ast.ExprStmt{X: requireNoError()},
								},
							},
						},
					},
				}})
			}
		}
	}

	for _, im := range imports {
		importsDecl.Specs = append(importsDecl.Specs, &ast.ImportSpec{Path: stringBasicLiteral(im)})
	}

	return formatGo(&file, "api/csv_test.go")
}

func generateClientHelpers(querierTypes map[string]QuerierType, functionFiles map[string][]specification.Function, goIdentifiers map[string][]string, packages map[string]string) error {
	// Category names mapped to their exported type names
	categoryNames := map[string]string{
		"timeseries":   "TimeSeries",
		"fundamental":  "Fundamental",
		"technical":    "Technical",
		"economic":     "Economic",
		"forex":        "Forex",
		"crypto":       "Crypto",
		"commodities":  "Commodities",
		"intelligence": "Intelligence",
		"options":      "Options",
	}

	file := &ast.File{Name: ast.NewIdent("alphavantage")}

	importsSet := make(map[string]struct{})
	importsSet["context"] = struct{}{}

	// Gather functions by category
	categoryFunctions := make(map[string][]specification.Function)
	for filePath, functions := range functionFiles {
		var pkgName string
		for name, pattern := range packages {
			if ok, err := path.Match(pattern, filepath.Base(filePath)); err != nil {
				return err
			} else if ok {
				pkgName = name
			}
		}
		if pkgName == "" {
			continue
		}
		categoryFunctions[pkgName] = append(categoryFunctions[pkgName], functions...)
	}

	// Sort category names for deterministic output
	var sortedCategories []string
	for cat := range categoryNames {
		sortedCategories = append(sortedCategories, cat)
	}
	slices.Sort(sortedCategories)

	var decls []ast.Decl

	// Generate type declarations and accessor methods for each category
	for _, pkgName := range sortedCategories {
		categoryTypeName := categoryNames[pkgName] + "Functions"

		// Type declaration: type TimeSeriesFunctions Client
		decls = append(decls, &ast.GenDecl{
			Tok: token.TYPE,
			Specs: []ast.Spec{
				&ast.TypeSpec{
					Name: ast.NewIdent(categoryTypeName),
					Type: ast.NewIdent("Client"),
				},
			},
		})

		// Accessor method: func (c *Client) TimeSeries() *TimeSeriesFunctions
		decls = append(decls, &ast.FuncDecl{
			Recv: &ast.FieldList{
				List: []*ast.Field{
					newField(&ast.StarExpr{X: ast.NewIdent("Client")}, "c"),
				},
			},
			Name: ast.NewIdent(categoryNames[pkgName]),
			Type: &ast.FuncType{
				Results: &ast.FieldList{
					List: []*ast.Field{
						{Type: &ast.StarExpr{X: ast.NewIdent(categoryTypeName)}},
					},
				},
			},
			Body: &ast.BlockStmt{
				List: []ast.Stmt{
					&ast.ReturnStmt{
						Results: []ast.Expr{
							&ast.CallExpr{
								Fun: &ast.ParenExpr{
									X: &ast.StarExpr{X: ast.NewIdent(categoryTypeName)},
								},
								Args: []ast.Expr{ast.NewIdent("c")},
							},
						},
					},
				},
			},
		})
	}

	// Generate helper methods for each function in each category
	for _, pkgName := range sortedCategories {
		categoryTypeName := categoryNames[pkgName] + "Functions"
		functions := categoryFunctions[pkgName]

		// Sort functions by their Go identifier
		slices.SortFunc(functions, func(a, b specification.Function) int {
			return cmp.Compare(goIdentifiers[a.Name][0], goIdentifiers[b.Name][0])
		})

		for _, fn := range functions {
			qt := querierTypes[fn.Name]
			// Skip functions without CSV row types (JSON-only functions)
			if qt.PackagePath == "" || qt.RowType == "" {
				continue
			}

			// Add import for the query package (only when we have a function to generate)
			pkgPath := path.Join("github.com/portfoliotree/alphavantage/query", pkgName)
			importsSet[pkgPath] = struct{}{}

			goIdent := goIdentifier(goIdentifiers, pkgName, fn.Name)
			methodName := goIdent

			// Build the method
			// func (f *TimeSeriesFunctions) GlobalQuote(ctx context.Context, query timeseries.GlobalQuoteQuery) ([]timeseries.GlobalQuoteRow, error)
			resultType := &ast.ArrayType{Elt: newSel(pkgName, qt.RowType)}
			params := []*ast.Field{
				newField(newSel("context", "Context"), "ctx"),
				newField(newSel(pkgName, qt.QueryType), "query"),
			}
			body := []ast.Stmt{
				&ast.ReturnStmt{
					Results: []ast.Expr{
						&ast.CallExpr{
							Fun: &ast.IndexExpr{
								X:     ast.NewIdent("queryRows"),
								Index: newSel(pkgName, qt.RowType),
							},
							Args: []ast.Expr{
								ast.NewIdent("ctx"),
								&ast.CallExpr{
									Fun: &ast.ParenExpr{
										X: &ast.StarExpr{X: ast.NewIdent("Client")},
									},
									Args: []ast.Expr{ast.NewIdent("f")},
								},
								ast.NewIdent("query"),
							},
						},
					},
				},
			}

			decls = append(decls, &ast.FuncDecl{
				Recv: &ast.FieldList{
					List: []*ast.Field{
						newField(&ast.StarExpr{X: ast.NewIdent(categoryTypeName)}, "f"),
					},
				},
				Name: ast.NewIdent(methodName),
				Type: &ast.FuncType{
					Params: &ast.FieldList{List: params},
					Results: &ast.FieldList{
						List: []*ast.Field{
							{Type: resultType},
							{Type: ast.NewIdent("error")},
						},
					},
				},
				Body: &ast.BlockStmt{List: body},
			})
		}
	}

	// Build imports
	var imports []string
	for imp := range importsSet {
		imports = append(imports, imp)
	}
	slices.Sort(imports)

	var importSpecs []ast.Spec
	for _, imp := range imports {
		importSpecs = append(importSpecs, &ast.ImportSpec{
			Path: stringBasicLiteral(imp),
		})
	}

	file.Decls = append([]ast.Decl{
		&ast.GenDecl{
			Tok:   token.IMPORT,
			Specs: importSpecs,
		},
	}, decls...)

	return formatGo(file, "functions.go")
}
