// Code generated by av-generate; DO NOT EDIT.

package technical

import (
	"net/url"
	"time"
)

type DoubleExponentialMovingAverageQuery url.Values

func QueryDoubleExponentialMovingAverage(apiKey, symbol, interval, seriesType string) DoubleExponentialMovingAverageQuery {
	return DoubleExponentialMovingAverageQuery{"function": []string{"DEMA"}, "symbol": []string{symbol}, "interval": []string{interval}, "series_type": []string{seriesType}, "apikey": []string{apiKey}}
}

func (query DoubleExponentialMovingAverageQuery) Month(value time.Time) DoubleExponentialMovingAverageQuery {
	query["month"] = []string{value.Format("2006-01")}
	return query
}

func (query DoubleExponentialMovingAverageQuery) TimePeriod(value string) DoubleExponentialMovingAverageQuery {
	query["time_period"] = []string{value}
	return query
}

func (query DoubleExponentialMovingAverageQuery) DataTypeCSV() DoubleExponentialMovingAverageQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query DoubleExponentialMovingAverageQuery) DataTypeJSON() DoubleExponentialMovingAverageQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query DoubleExponentialMovingAverageQuery) DataType(value string) DoubleExponentialMovingAverageQuery {
	query["datatype"] = []string{value}
	return query
}

func (q DoubleExponentialMovingAverageQuery) Encode() string {
	return url.Values(q).Encode()
}

type DoubleExponentialMovingAverageRow struct {
	Time  string `column-name:"time"`
	Value string `column-name:"DEMA"`
}

type ExponentialMovingAverageQuery url.Values

func QueryExponentialMovingAverage(apiKey, symbol, interval, seriesType string) ExponentialMovingAverageQuery {
	return ExponentialMovingAverageQuery{"function": []string{"EMA"}, "symbol": []string{symbol}, "interval": []string{interval}, "series_type": []string{seriesType}, "apikey": []string{apiKey}}
}

func (query ExponentialMovingAverageQuery) Month(value time.Time) ExponentialMovingAverageQuery {
	query["month"] = []string{value.Format("2006-01")}
	return query
}

func (query ExponentialMovingAverageQuery) TimePeriod(value string) ExponentialMovingAverageQuery {
	query["time_period"] = []string{value}
	return query
}

func (query ExponentialMovingAverageQuery) DataTypeCSV() ExponentialMovingAverageQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query ExponentialMovingAverageQuery) DataTypeJSON() ExponentialMovingAverageQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query ExponentialMovingAverageQuery) DataType(value string) ExponentialMovingAverageQuery {
	query["datatype"] = []string{value}
	return query
}

func (q ExponentialMovingAverageQuery) Encode() string {
	return url.Values(q).Encode()
}

type ExponentialMovingAverageRow struct {
	Time  string `column-name:"time"`
	Value string `column-name:"EMA"`
}

type KaufmanAdaptiveMovingAverageQuery url.Values

func QueryKaufmanAdaptiveMovingAverage(apiKey, symbol, interval, seriesType string) KaufmanAdaptiveMovingAverageQuery {
	return KaufmanAdaptiveMovingAverageQuery{"function": []string{"KAMA"}, "symbol": []string{symbol}, "interval": []string{interval}, "series_type": []string{seriesType}, "apikey": []string{apiKey}}
}

func (query KaufmanAdaptiveMovingAverageQuery) Month(value time.Time) KaufmanAdaptiveMovingAverageQuery {
	query["month"] = []string{value.Format("2006-01")}
	return query
}

func (query KaufmanAdaptiveMovingAverageQuery) TimePeriod(value string) KaufmanAdaptiveMovingAverageQuery {
	query["time_period"] = []string{value}
	return query
}

func (query KaufmanAdaptiveMovingAverageQuery) DataTypeCSV() KaufmanAdaptiveMovingAverageQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query KaufmanAdaptiveMovingAverageQuery) DataTypeJSON() KaufmanAdaptiveMovingAverageQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query KaufmanAdaptiveMovingAverageQuery) DataType(value string) KaufmanAdaptiveMovingAverageQuery {
	query["datatype"] = []string{value}
	return query
}

func (q KaufmanAdaptiveMovingAverageQuery) Encode() string {
	return url.Values(q).Encode()
}

type KaufmanAdaptiveMovingAverageRow struct {
	Time  string `column-name:"time"`
	Value string `column-name:"KAMA"`
}

type SimpleMovingAverageQuery url.Values

func QuerySimpleMovingAverage(apiKey, symbol, interval, seriesType string) SimpleMovingAverageQuery {
	return SimpleMovingAverageQuery{"function": []string{"SMA"}, "symbol": []string{symbol}, "interval": []string{interval}, "series_type": []string{seriesType}, "apikey": []string{apiKey}}
}

func (query SimpleMovingAverageQuery) Month(value time.Time) SimpleMovingAverageQuery {
	query["month"] = []string{value.Format("2006-01")}
	return query
}

func (query SimpleMovingAverageQuery) TimePeriod(value string) SimpleMovingAverageQuery {
	query["time_period"] = []string{value}
	return query
}

func (query SimpleMovingAverageQuery) DataTypeCSV() SimpleMovingAverageQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query SimpleMovingAverageQuery) DataTypeJSON() SimpleMovingAverageQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query SimpleMovingAverageQuery) DataType(value string) SimpleMovingAverageQuery {
	query["datatype"] = []string{value}
	return query
}

func (q SimpleMovingAverageQuery) Encode() string {
	return url.Values(q).Encode()
}

type SimpleMovingAverageRow struct {
	Time  string `column-name:"time"`
	Value string `column-name:"SMA"`
}

type T3Query url.Values

func QueryT3(apiKey, symbol, interval, seriesType string) T3Query {
	return T3Query{"function": []string{"T3"}, "symbol": []string{symbol}, "interval": []string{interval}, "series_type": []string{seriesType}, "apikey": []string{apiKey}}
}

func (query T3Query) Month(value time.Time) T3Query {
	query["month"] = []string{value.Format("2006-01")}
	return query
}

func (query T3Query) TimePeriod(value string) T3Query {
	query["time_period"] = []string{value}
	return query
}

func (query T3Query) DataTypeCSV() T3Query {
	query["datatype"] = []string{"csv"}
	return query
}

func (query T3Query) DataTypeJSON() T3Query {
	query["datatype"] = []string{"json"}
	return query
}

func (query T3Query) DataType(value string) T3Query {
	query["datatype"] = []string{value}
	return query
}

func (q T3Query) Encode() string {
	return url.Values(q).Encode()
}

type T3Row struct {
	Time  string `column-name:"time"`
	Value string `column-name:"T3"`
}

type TriangularMovingAverageQuery url.Values

func QueryTriangularMovingAverage(apiKey, symbol, interval, seriesType string) TriangularMovingAverageQuery {
	return TriangularMovingAverageQuery{"function": []string{"TRIMA"}, "symbol": []string{symbol}, "interval": []string{interval}, "series_type": []string{seriesType}, "apikey": []string{apiKey}}
}

func (query TriangularMovingAverageQuery) Month(value time.Time) TriangularMovingAverageQuery {
	query["month"] = []string{value.Format("2006-01")}
	return query
}

func (query TriangularMovingAverageQuery) TimePeriod(value string) TriangularMovingAverageQuery {
	query["time_period"] = []string{value}
	return query
}

func (query TriangularMovingAverageQuery) DataTypeCSV() TriangularMovingAverageQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query TriangularMovingAverageQuery) DataTypeJSON() TriangularMovingAverageQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query TriangularMovingAverageQuery) DataType(value string) TriangularMovingAverageQuery {
	query["datatype"] = []string{value}
	return query
}

func (q TriangularMovingAverageQuery) Encode() string {
	return url.Values(q).Encode()
}

type TriangularMovingAverageRow struct {
	Time  string `column-name:"time"`
	Value string `column-name:"TRIMA"`
}

type TripleExponentialMovingAverageQuery url.Values

func QueryTripleExponentialMovingAverage(apiKey, symbol, interval, seriesType string) TripleExponentialMovingAverageQuery {
	return TripleExponentialMovingAverageQuery{"function": []string{"TEMA"}, "symbol": []string{symbol}, "interval": []string{interval}, "series_type": []string{seriesType}, "apikey": []string{apiKey}}
}

func (query TripleExponentialMovingAverageQuery) Month(value time.Time) TripleExponentialMovingAverageQuery {
	query["month"] = []string{value.Format("2006-01")}
	return query
}

func (query TripleExponentialMovingAverageQuery) TimePeriod(value string) TripleExponentialMovingAverageQuery {
	query["time_period"] = []string{value}
	return query
}

func (query TripleExponentialMovingAverageQuery) DataTypeCSV() TripleExponentialMovingAverageQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query TripleExponentialMovingAverageQuery) DataTypeJSON() TripleExponentialMovingAverageQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query TripleExponentialMovingAverageQuery) DataType(value string) TripleExponentialMovingAverageQuery {
	query["datatype"] = []string{value}
	return query
}

func (q TripleExponentialMovingAverageQuery) Encode() string {
	return url.Values(q).Encode()
}

type TripleExponentialMovingAverageRow struct {
	Time  string `column-name:"time"`
	Value string `column-name:"TEMA"`
}

type WeightedMovingAverageQuery url.Values

func QueryWeightedMovingAverage(apiKey, symbol, interval, seriesType string) WeightedMovingAverageQuery {
	return WeightedMovingAverageQuery{"function": []string{"WMA"}, "symbol": []string{symbol}, "interval": []string{interval}, "series_type": []string{seriesType}, "apikey": []string{apiKey}}
}

func (query WeightedMovingAverageQuery) Month(value time.Time) WeightedMovingAverageQuery {
	query["month"] = []string{value.Format("2006-01")}
	return query
}

func (query WeightedMovingAverageQuery) TimePeriod(value string) WeightedMovingAverageQuery {
	query["time_period"] = []string{value}
	return query
}

func (query WeightedMovingAverageQuery) DataTypeCSV() WeightedMovingAverageQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query WeightedMovingAverageQuery) DataTypeJSON() WeightedMovingAverageQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query WeightedMovingAverageQuery) DataType(value string) WeightedMovingAverageQuery {
	query["datatype"] = []string{value}
	return query
}

func (q WeightedMovingAverageQuery) Encode() string {
	return url.Values(q).Encode()
}

type WeightedMovingAverageRow struct {
	Time  string `column-name:"time"`
	Value string `column-name:"WMA"`
}
