// Code generated by av-generate; DO NOT EDIT.

package technical

import (
	"net/url"
	"time"
)

type AroonQuery url.Values

func QueryAroon(apiKey, symbol, interval, timePeriod string) AroonQuery {
	return AroonQuery{"function": []string{"AROON"}, "symbol": []string{symbol}, "interval": []string{interval}, "time_period": []string{timePeriod}, "apikey": []string{apiKey}}
}

func (query AroonQuery) Month(value time.Time) AroonQuery {
	query["month"] = []string{value.Format("2006-01")}
	return query
}

func (query AroonQuery) DataTypeCSV() AroonQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query AroonQuery) DataTypeJSON() AroonQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query AroonQuery) DataType(value string) AroonQuery {
	query["datatype"] = []string{value}
	return query
}

func (query AroonQuery) EntitlementRealtime() AroonQuery {
	query["entitlement"] = []string{"realtime"}
	return query
}

func (query AroonQuery) EntitlementDelayed() AroonQuery {
	query["entitlement"] = []string{"delayed"}
	return query
}

func (query AroonQuery) Entitlement(value string) AroonQuery {
	query["entitlement"] = []string{value}
	return query
}

func (q AroonQuery) Encode() string {
	return url.Values(q).Encode()
}

type AroonRow struct {
	Time      string `column-name:"time"`
	AroonDown string `column-name:"Aroon Down"`
	AroonUp   string `column-name:"Aroon Up"`
}

type AroonOscQuery url.Values

func QueryAroonOsc(apiKey, symbol, interval, timePeriod string) AroonOscQuery {
	return AroonOscQuery{"function": []string{"AROONOSC"}, "symbol": []string{symbol}, "interval": []string{interval}, "time_period": []string{timePeriod}, "apikey": []string{apiKey}}
}

func (query AroonOscQuery) Month(value time.Time) AroonOscQuery {
	query["month"] = []string{value.Format("2006-01")}
	return query
}

func (query AroonOscQuery) DataTypeCSV() AroonOscQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query AroonOscQuery) DataTypeJSON() AroonOscQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query AroonOscQuery) DataType(value string) AroonOscQuery {
	query["datatype"] = []string{value}
	return query
}

func (query AroonOscQuery) EntitlementRealtime() AroonOscQuery {
	query["entitlement"] = []string{"realtime"}
	return query
}

func (query AroonOscQuery) EntitlementDelayed() AroonOscQuery {
	query["entitlement"] = []string{"delayed"}
	return query
}

func (query AroonOscQuery) Entitlement(value string) AroonOscQuery {
	query["entitlement"] = []string{value}
	return query
}

func (q AroonOscQuery) Encode() string {
	return url.Values(q).Encode()
}

type AroonOscRow struct {
	Time  string `column-name:"time"`
	Value string `column-name:"AROONOSC"`
}

type AverageDirectionalMovementIndexQuery url.Values

func QueryAverageDirectionalMovementIndex(apiKey, symbol, interval, timePeriod string) AverageDirectionalMovementIndexQuery {
	return AverageDirectionalMovementIndexQuery{"function": []string{"ADX"}, "symbol": []string{symbol}, "interval": []string{interval}, "time_period": []string{timePeriod}, "apikey": []string{apiKey}}
}

func (query AverageDirectionalMovementIndexQuery) Month(value time.Time) AverageDirectionalMovementIndexQuery {
	query["month"] = []string{value.Format("2006-01")}
	return query
}

func (query AverageDirectionalMovementIndexQuery) DataTypeCSV() AverageDirectionalMovementIndexQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query AverageDirectionalMovementIndexQuery) DataTypeJSON() AverageDirectionalMovementIndexQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query AverageDirectionalMovementIndexQuery) DataType(value string) AverageDirectionalMovementIndexQuery {
	query["datatype"] = []string{value}
	return query
}

func (query AverageDirectionalMovementIndexQuery) EntitlementRealtime() AverageDirectionalMovementIndexQuery {
	query["entitlement"] = []string{"realtime"}
	return query
}

func (query AverageDirectionalMovementIndexQuery) EntitlementDelayed() AverageDirectionalMovementIndexQuery {
	query["entitlement"] = []string{"delayed"}
	return query
}

func (query AverageDirectionalMovementIndexQuery) Entitlement(value string) AverageDirectionalMovementIndexQuery {
	query["entitlement"] = []string{value}
	return query
}

func (q AverageDirectionalMovementIndexQuery) Encode() string {
	return url.Values(q).Encode()
}

type AverageDirectionalMovementIndexRow struct {
	Time  string `column-name:"time"`
	Value string `column-name:"ADX"`
}

type AverageDirectionalMovementIndexRatingQuery url.Values

func QueryAverageDirectionalMovementIndexRating(apiKey, symbol, interval, timePeriod string) AverageDirectionalMovementIndexRatingQuery {
	return AverageDirectionalMovementIndexRatingQuery{"function": []string{"ADXR"}, "symbol": []string{symbol}, "interval": []string{interval}, "time_period": []string{timePeriod}, "apikey": []string{apiKey}}
}

func (query AverageDirectionalMovementIndexRatingQuery) Month(value time.Time) AverageDirectionalMovementIndexRatingQuery {
	query["month"] = []string{value.Format("2006-01")}
	return query
}

func (query AverageDirectionalMovementIndexRatingQuery) DataTypeCSV() AverageDirectionalMovementIndexRatingQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query AverageDirectionalMovementIndexRatingQuery) DataTypeJSON() AverageDirectionalMovementIndexRatingQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query AverageDirectionalMovementIndexRatingQuery) DataType(value string) AverageDirectionalMovementIndexRatingQuery {
	query["datatype"] = []string{value}
	return query
}

func (query AverageDirectionalMovementIndexRatingQuery) EntitlementRealtime() AverageDirectionalMovementIndexRatingQuery {
	query["entitlement"] = []string{"realtime"}
	return query
}

func (query AverageDirectionalMovementIndexRatingQuery) EntitlementDelayed() AverageDirectionalMovementIndexRatingQuery {
	query["entitlement"] = []string{"delayed"}
	return query
}

func (query AverageDirectionalMovementIndexRatingQuery) Entitlement(value string) AverageDirectionalMovementIndexRatingQuery {
	query["entitlement"] = []string{value}
	return query
}

func (q AverageDirectionalMovementIndexRatingQuery) Encode() string {
	return url.Values(q).Encode()
}

type AverageDirectionalMovementIndexRatingRow struct {
	Time  string `column-name:"time"`
	Value string `column-name:"ADXR"`
}

type DirectionalMovementIndexQuery url.Values

func QueryDirectionalMovementIndex(apiKey, symbol, interval, timePeriod string) DirectionalMovementIndexQuery {
	return DirectionalMovementIndexQuery{"function": []string{"DX"}, "symbol": []string{symbol}, "interval": []string{interval}, "time_period": []string{timePeriod}, "apikey": []string{apiKey}}
}

func (query DirectionalMovementIndexQuery) Month(value time.Time) DirectionalMovementIndexQuery {
	query["month"] = []string{value.Format("2006-01")}
	return query
}

func (query DirectionalMovementIndexQuery) DataTypeCSV() DirectionalMovementIndexQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query DirectionalMovementIndexQuery) DataTypeJSON() DirectionalMovementIndexQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query DirectionalMovementIndexQuery) DataType(value string) DirectionalMovementIndexQuery {
	query["datatype"] = []string{value}
	return query
}

func (query DirectionalMovementIndexQuery) EntitlementRealtime() DirectionalMovementIndexQuery {
	query["entitlement"] = []string{"realtime"}
	return query
}

func (query DirectionalMovementIndexQuery) EntitlementDelayed() DirectionalMovementIndexQuery {
	query["entitlement"] = []string{"delayed"}
	return query
}

func (query DirectionalMovementIndexQuery) Entitlement(value string) DirectionalMovementIndexQuery {
	query["entitlement"] = []string{value}
	return query
}

func (q DirectionalMovementIndexQuery) Encode() string {
	return url.Values(q).Encode()
}

type DirectionalMovementIndexRow struct {
	Time  string `column-name:"time"`
	Value string `column-name:"DX"`
}

type MinusDirectionalIndicatorQuery url.Values

func QueryMinusDirectionalIndicator(apiKey, symbol, interval, timePeriod string) MinusDirectionalIndicatorQuery {
	return MinusDirectionalIndicatorQuery{"function": []string{"MINUS_DI"}, "symbol": []string{symbol}, "interval": []string{interval}, "time_period": []string{timePeriod}, "apikey": []string{apiKey}}
}

func (query MinusDirectionalIndicatorQuery) Month(value time.Time) MinusDirectionalIndicatorQuery {
	query["month"] = []string{value.Format("2006-01")}
	return query
}

func (query MinusDirectionalIndicatorQuery) DataTypeCSV() MinusDirectionalIndicatorQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query MinusDirectionalIndicatorQuery) DataTypeJSON() MinusDirectionalIndicatorQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query MinusDirectionalIndicatorQuery) DataType(value string) MinusDirectionalIndicatorQuery {
	query["datatype"] = []string{value}
	return query
}

func (query MinusDirectionalIndicatorQuery) EntitlementRealtime() MinusDirectionalIndicatorQuery {
	query["entitlement"] = []string{"realtime"}
	return query
}

func (query MinusDirectionalIndicatorQuery) EntitlementDelayed() MinusDirectionalIndicatorQuery {
	query["entitlement"] = []string{"delayed"}
	return query
}

func (query MinusDirectionalIndicatorQuery) Entitlement(value string) MinusDirectionalIndicatorQuery {
	query["entitlement"] = []string{value}
	return query
}

func (q MinusDirectionalIndicatorQuery) Encode() string {
	return url.Values(q).Encode()
}

type MinusDirectionalIndicatorRow struct {
	Time  string `column-name:"time"`
	Value string `column-name:"MINUS_DI"`
}

type MinusDirectionalMovementQuery url.Values

func QueryMinusDirectionalMovement(apiKey, symbol, interval, timePeriod string) MinusDirectionalMovementQuery {
	return MinusDirectionalMovementQuery{"function": []string{"MINUS_DM"}, "symbol": []string{symbol}, "interval": []string{interval}, "time_period": []string{timePeriod}, "apikey": []string{apiKey}}
}

func (query MinusDirectionalMovementQuery) Month(value time.Time) MinusDirectionalMovementQuery {
	query["month"] = []string{value.Format("2006-01")}
	return query
}

func (query MinusDirectionalMovementQuery) DataTypeCSV() MinusDirectionalMovementQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query MinusDirectionalMovementQuery) DataTypeJSON() MinusDirectionalMovementQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query MinusDirectionalMovementQuery) DataType(value string) MinusDirectionalMovementQuery {
	query["datatype"] = []string{value}
	return query
}

func (query MinusDirectionalMovementQuery) EntitlementRealtime() MinusDirectionalMovementQuery {
	query["entitlement"] = []string{"realtime"}
	return query
}

func (query MinusDirectionalMovementQuery) EntitlementDelayed() MinusDirectionalMovementQuery {
	query["entitlement"] = []string{"delayed"}
	return query
}

func (query MinusDirectionalMovementQuery) Entitlement(value string) MinusDirectionalMovementQuery {
	query["entitlement"] = []string{value}
	return query
}

func (q MinusDirectionalMovementQuery) Encode() string {
	return url.Values(q).Encode()
}

type MinusDirectionalMovementRow struct {
	Time  string `column-name:"time"`
	Value string `column-name:"MINUS_DM"`
}

type PlusDirectionalIndicatorQuery url.Values

func QueryPlusDirectionalIndicator(apiKey, symbol, interval, timePeriod string) PlusDirectionalIndicatorQuery {
	return PlusDirectionalIndicatorQuery{"function": []string{"PLUS_DI"}, "symbol": []string{symbol}, "interval": []string{interval}, "time_period": []string{timePeriod}, "apikey": []string{apiKey}}
}

func (query PlusDirectionalIndicatorQuery) Month(value time.Time) PlusDirectionalIndicatorQuery {
	query["month"] = []string{value.Format("2006-01")}
	return query
}

func (query PlusDirectionalIndicatorQuery) DataTypeCSV() PlusDirectionalIndicatorQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query PlusDirectionalIndicatorQuery) DataTypeJSON() PlusDirectionalIndicatorQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query PlusDirectionalIndicatorQuery) DataType(value string) PlusDirectionalIndicatorQuery {
	query["datatype"] = []string{value}
	return query
}

func (query PlusDirectionalIndicatorQuery) EntitlementRealtime() PlusDirectionalIndicatorQuery {
	query["entitlement"] = []string{"realtime"}
	return query
}

func (query PlusDirectionalIndicatorQuery) EntitlementDelayed() PlusDirectionalIndicatorQuery {
	query["entitlement"] = []string{"delayed"}
	return query
}

func (query PlusDirectionalIndicatorQuery) Entitlement(value string) PlusDirectionalIndicatorQuery {
	query["entitlement"] = []string{value}
	return query
}

func (q PlusDirectionalIndicatorQuery) Encode() string {
	return url.Values(q).Encode()
}

type PlusDirectionalIndicatorRow struct {
	Time  string `column-name:"time"`
	Value string `column-name:"PLUS_DI"`
}

type PlusDirectionalMovementQuery url.Values

func QueryPlusDirectionalMovement(apiKey, symbol, interval, timePeriod string) PlusDirectionalMovementQuery {
	return PlusDirectionalMovementQuery{"function": []string{"PLUS_DM"}, "symbol": []string{symbol}, "interval": []string{interval}, "time_period": []string{timePeriod}, "apikey": []string{apiKey}}
}

func (query PlusDirectionalMovementQuery) Month(value time.Time) PlusDirectionalMovementQuery {
	query["month"] = []string{value.Format("2006-01")}
	return query
}

func (query PlusDirectionalMovementQuery) DataTypeCSV() PlusDirectionalMovementQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query PlusDirectionalMovementQuery) DataTypeJSON() PlusDirectionalMovementQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query PlusDirectionalMovementQuery) DataType(value string) PlusDirectionalMovementQuery {
	query["datatype"] = []string{value}
	return query
}

func (query PlusDirectionalMovementQuery) EntitlementRealtime() PlusDirectionalMovementQuery {
	query["entitlement"] = []string{"realtime"}
	return query
}

func (query PlusDirectionalMovementQuery) EntitlementDelayed() PlusDirectionalMovementQuery {
	query["entitlement"] = []string{"delayed"}
	return query
}

func (query PlusDirectionalMovementQuery) Entitlement(value string) PlusDirectionalMovementQuery {
	query["entitlement"] = []string{value}
	return query
}

func (q PlusDirectionalMovementQuery) Encode() string {
	return url.Values(q).Encode()
}

type PlusDirectionalMovementRow struct {
	Time  string `column-name:"time"`
	Value string `column-name:"PLUS_DM"`
}
