// Code generated by av-generate; DO NOT EDIT.

package technical

import (
	"net/url"
	"time"
)

type AverageTrueRangeQuery url.Values

func QueryAverageTrueRange(apiKey, symbol, interval string) AverageTrueRangeQuery {
	return AverageTrueRangeQuery{"function": []string{"ATR"}, "symbol": []string{symbol}, "interval": []string{interval}, "apikey": []string{apiKey}}
}

func (query AverageTrueRangeQuery) Month(value time.Time) AverageTrueRangeQuery {
	query["month"] = []string{value.Format("2006-01")}
	return query
}

func (query AverageTrueRangeQuery) TimePeriod(value string) AverageTrueRangeQuery {
	query["time_period"] = []string{value}
	return query
}

func (query AverageTrueRangeQuery) DataTypeCSV() AverageTrueRangeQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query AverageTrueRangeQuery) DataTypeJSON() AverageTrueRangeQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query AverageTrueRangeQuery) DataType(value string) AverageTrueRangeQuery {
	query["datatype"] = []string{value}
	return query
}

func (q AverageTrueRangeQuery) Encode() string {
	return url.Values(q).Encode()
}

type AverageTrueRangeRow struct {
	Time  string `column-name:"time"`
	Value string `column-name:"ATR"`
}

type BollingerBandsQuery url.Values

func QueryBollingerBands(apiKey, symbol, interval, seriesType string) BollingerBandsQuery {
	return BollingerBandsQuery{"function": []string{"BBANDS"}, "symbol": []string{symbol}, "interval": []string{interval}, "series_type": []string{seriesType}, "apikey": []string{apiKey}}
}

func (query BollingerBandsQuery) Month(value time.Time) BollingerBandsQuery {
	query["month"] = []string{value.Format("2006-01")}
	return query
}

func (query BollingerBandsQuery) TimePeriod(value string) BollingerBandsQuery {
	query["time_period"] = []string{value}
	return query
}

func (query BollingerBandsQuery) UpperBandStandardDeviationMultiplier(value string) BollingerBandsQuery {
	query["nbdevup"] = []string{value}
	return query
}

func (query BollingerBandsQuery) LowerBandStandardDeviationMultiplier(value string) BollingerBandsQuery {
	query["nbdevdn"] = []string{value}
	return query
}

func (query BollingerBandsQuery) MovingAverageType(value string) BollingerBandsQuery {
	query["matype"] = []string{value}
	return query
}

func (query BollingerBandsQuery) DataTypeCSV() BollingerBandsQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query BollingerBandsQuery) DataTypeJSON() BollingerBandsQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query BollingerBandsQuery) DataType(value string) BollingerBandsQuery {
	query["datatype"] = []string{value}
	return query
}

func (q BollingerBandsQuery) Encode() string {
	return url.Values(q).Encode()
}

type BollingerBandsRow struct {
	Time           string `column-name:"time"`
	RealLowerBand  string `column-name:"Real Lower Band"`
	RealMiddleBand string `column-name:"Real Middle Band"`
	RealUpperBand  string `column-name:"Real Upper Band"`
}

type NormalizedAverageTrueRangeQuery url.Values

func QueryNormalizedAverageTrueRange(apiKey, symbol, interval string) NormalizedAverageTrueRangeQuery {
	return NormalizedAverageTrueRangeQuery{"function": []string{"NATR"}, "symbol": []string{symbol}, "interval": []string{interval}, "apikey": []string{apiKey}}
}

func (query NormalizedAverageTrueRangeQuery) Month(value time.Time) NormalizedAverageTrueRangeQuery {
	query["month"] = []string{value.Format("2006-01")}
	return query
}

func (query NormalizedAverageTrueRangeQuery) TimePeriod(value string) NormalizedAverageTrueRangeQuery {
	query["time_period"] = []string{value}
	return query
}

func (query NormalizedAverageTrueRangeQuery) DataTypeCSV() NormalizedAverageTrueRangeQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query NormalizedAverageTrueRangeQuery) DataTypeJSON() NormalizedAverageTrueRangeQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query NormalizedAverageTrueRangeQuery) DataType(value string) NormalizedAverageTrueRangeQuery {
	query["datatype"] = []string{value}
	return query
}

func (q NormalizedAverageTrueRangeQuery) Encode() string {
	return url.Values(q).Encode()
}

type NormalizedAverageTrueRangeRow struct {
	Time  string `column-name:"time"`
	Value string `column-name:"NATR"`
}

type SARQuery url.Values

func QuerySAR(apiKey, symbol, interval string) SARQuery {
	return SARQuery{"function": []string{"SAR"}, "symbol": []string{symbol}, "interval": []string{interval}, "apikey": []string{apiKey}}
}

func (query SARQuery) Month(value time.Time) SARQuery {
	query["month"] = []string{value.Format("2006-01")}
	return query
}

func (query SARQuery) Acceleration(value string) SARQuery {
	query["acceleration"] = []string{value}
	return query
}

func (query SARQuery) Maximum(value string) SARQuery {
	query["maximum"] = []string{value}
	return query
}

func (query SARQuery) DataTypeCSV() SARQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query SARQuery) DataTypeJSON() SARQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query SARQuery) DataType(value string) SARQuery {
	query["datatype"] = []string{value}
	return query
}

func (q SARQuery) Encode() string {
	return url.Values(q).Encode()
}

type SARRow struct {
	Time  string `column-name:"time"`
	Value string `column-name:"SAR"`
}

type TrueRangeQuery url.Values

func QueryTrueRange(apiKey, symbol, interval string) TrueRangeQuery {
	return TrueRangeQuery{"function": []string{"TRANGE"}, "symbol": []string{symbol}, "interval": []string{interval}, "apikey": []string{apiKey}}
}

func (query TrueRangeQuery) Month(value time.Time) TrueRangeQuery {
	query["month"] = []string{value.Format("2006-01")}
	return query
}

func (query TrueRangeQuery) DataTypeCSV() TrueRangeQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query TrueRangeQuery) DataTypeJSON() TrueRangeQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query TrueRangeQuery) DataType(value string) TrueRangeQuery {
	query["datatype"] = []string{value}
	return query
}

func (q TrueRangeQuery) Encode() string {
	return url.Values(q).Encode()
}

type TrueRangeRow struct {
	Time  string `column-name:"time"`
	Value string `column-name:"TRANGE"`
}

type UltimateOscillatorQuery url.Values

func QueryUltimateOscillator(apiKey, symbol, interval string) UltimateOscillatorQuery {
	return UltimateOscillatorQuery{"function": []string{"ULTOSC"}, "symbol": []string{symbol}, "interval": []string{interval}, "apikey": []string{apiKey}}
}

func (query UltimateOscillatorQuery) Month(value time.Time) UltimateOscillatorQuery {
	query["month"] = []string{value.Format("2006-01")}
	return query
}

func (query UltimateOscillatorQuery) TimePeriod1(value string) UltimateOscillatorQuery {
	query["timeperiod1"] = []string{value}
	return query
}

func (query UltimateOscillatorQuery) TimePeriod2(value string) UltimateOscillatorQuery {
	query["timeperiod2"] = []string{value}
	return query
}

func (query UltimateOscillatorQuery) TimePeriod3(value string) UltimateOscillatorQuery {
	query["timeperiod3"] = []string{value}
	return query
}

func (query UltimateOscillatorQuery) DataTypeCSV() UltimateOscillatorQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query UltimateOscillatorQuery) DataTypeJSON() UltimateOscillatorQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query UltimateOscillatorQuery) DataType(value string) UltimateOscillatorQuery {
	query["datatype"] = []string{value}
	return query
}

func (q UltimateOscillatorQuery) Encode() string {
	return url.Values(q).Encode()
}

type UltimateOscillatorRow struct {
	Time  string `column-name:"time"`
	Value string `column-name:"ULTOSC"`
}
