// Code generated by av-generate; DO NOT EDIT.

package technical

import (
	"net/url"
	"time"
)

type ChaikinADLineQuery url.Values

func QueryChaikinADLine(apiKey, symbol, interval string) ChaikinADLineQuery {
	return ChaikinADLineQuery{"function": []string{"AD"}, "symbol": []string{symbol}, "interval": []string{interval}, "apikey": []string{apiKey}}
}

func (query ChaikinADLineQuery) Month(value time.Time) ChaikinADLineQuery {
	query["month"] = []string{value.Format("2006-01")}
	return query
}

func (query ChaikinADLineQuery) DataTypeCSV() ChaikinADLineQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query ChaikinADLineQuery) DataTypeJSON() ChaikinADLineQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query ChaikinADLineQuery) DataType(value string) ChaikinADLineQuery {
	query["datatype"] = []string{value}
	return query
}

func (query ChaikinADLineQuery) EntitlementRealtime() ChaikinADLineQuery {
	query["entitlement"] = []string{"realtime"}
	return query
}

func (query ChaikinADLineQuery) EntitlementDelayed() ChaikinADLineQuery {
	query["entitlement"] = []string{"delayed"}
	return query
}

func (query ChaikinADLineQuery) Entitlement(value string) ChaikinADLineQuery {
	query["entitlement"] = []string{value}
	return query
}

func (q ChaikinADLineQuery) Encode() string {
	return url.Values(q).Encode()
}

type ChaikinADLineRow struct {
	Time  string `column-name:"time"`
	Value string `column-name:"Chaikin A/D"`
}

type ChaikinADOscillatorQuery url.Values

func QueryChaikinADOscillator(apiKey, symbol, interval string) ChaikinADOscillatorQuery {
	return ChaikinADOscillatorQuery{"function": []string{"ADOSC"}, "symbol": []string{symbol}, "interval": []string{interval}, "apikey": []string{apiKey}}
}

func (query ChaikinADOscillatorQuery) Month(value time.Time) ChaikinADOscillatorQuery {
	query["month"] = []string{value.Format("2006-01")}
	return query
}

func (query ChaikinADOscillatorQuery) FastPeriod(value string) ChaikinADOscillatorQuery {
	query["fastperiod"] = []string{value}
	return query
}

func (query ChaikinADOscillatorQuery) SlowPeriod(value string) ChaikinADOscillatorQuery {
	query["slowperiod"] = []string{value}
	return query
}

func (query ChaikinADOscillatorQuery) DataTypeCSV() ChaikinADOscillatorQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query ChaikinADOscillatorQuery) DataTypeJSON() ChaikinADOscillatorQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query ChaikinADOscillatorQuery) DataType(value string) ChaikinADOscillatorQuery {
	query["datatype"] = []string{value}
	return query
}

func (query ChaikinADOscillatorQuery) EntitlementRealtime() ChaikinADOscillatorQuery {
	query["entitlement"] = []string{"realtime"}
	return query
}

func (query ChaikinADOscillatorQuery) EntitlementDelayed() ChaikinADOscillatorQuery {
	query["entitlement"] = []string{"delayed"}
	return query
}

func (query ChaikinADOscillatorQuery) Entitlement(value string) ChaikinADOscillatorQuery {
	query["entitlement"] = []string{value}
	return query
}

func (q ChaikinADOscillatorQuery) Encode() string {
	return url.Values(q).Encode()
}

type ChaikinADOscillatorRow struct {
	Time  string `column-name:"time"`
	Value string `column-name:"ADOSC"`
}

type MoneyFlowIndexQuery url.Values

func QueryMoneyFlowIndex(apiKey, symbol, interval, timePeriod string) MoneyFlowIndexQuery {
	return MoneyFlowIndexQuery{"function": []string{"MFI"}, "symbol": []string{symbol}, "interval": []string{interval}, "time_period": []string{timePeriod}, "apikey": []string{apiKey}}
}

func (query MoneyFlowIndexQuery) Month(value time.Time) MoneyFlowIndexQuery {
	query["month"] = []string{value.Format("2006-01")}
	return query
}

func (query MoneyFlowIndexQuery) DataTypeCSV() MoneyFlowIndexQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query MoneyFlowIndexQuery) DataTypeJSON() MoneyFlowIndexQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query MoneyFlowIndexQuery) DataType(value string) MoneyFlowIndexQuery {
	query["datatype"] = []string{value}
	return query
}

func (query MoneyFlowIndexQuery) EntitlementRealtime() MoneyFlowIndexQuery {
	query["entitlement"] = []string{"realtime"}
	return query
}

func (query MoneyFlowIndexQuery) EntitlementDelayed() MoneyFlowIndexQuery {
	query["entitlement"] = []string{"delayed"}
	return query
}

func (query MoneyFlowIndexQuery) Entitlement(value string) MoneyFlowIndexQuery {
	query["entitlement"] = []string{value}
	return query
}

func (q MoneyFlowIndexQuery) Encode() string {
	return url.Values(q).Encode()
}

type MoneyFlowIndexRow struct {
	Time  string `column-name:"time"`
	Value string `column-name:"MFI"`
}

type OnBalanceVolumeQuery url.Values

func QueryOnBalanceVolume(apiKey, symbol, interval string) OnBalanceVolumeQuery {
	return OnBalanceVolumeQuery{"function": []string{"OBV"}, "symbol": []string{symbol}, "interval": []string{interval}, "apikey": []string{apiKey}}
}

func (query OnBalanceVolumeQuery) Month(value time.Time) OnBalanceVolumeQuery {
	query["month"] = []string{value.Format("2006-01")}
	return query
}

func (query OnBalanceVolumeQuery) DataTypeCSV() OnBalanceVolumeQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query OnBalanceVolumeQuery) DataTypeJSON() OnBalanceVolumeQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query OnBalanceVolumeQuery) DataType(value string) OnBalanceVolumeQuery {
	query["datatype"] = []string{value}
	return query
}

func (query OnBalanceVolumeQuery) EntitlementRealtime() OnBalanceVolumeQuery {
	query["entitlement"] = []string{"realtime"}
	return query
}

func (query OnBalanceVolumeQuery) EntitlementDelayed() OnBalanceVolumeQuery {
	query["entitlement"] = []string{"delayed"}
	return query
}

func (query OnBalanceVolumeQuery) Entitlement(value string) OnBalanceVolumeQuery {
	query["entitlement"] = []string{value}
	return query
}

func (q OnBalanceVolumeQuery) Encode() string {
	return url.Values(q).Encode()
}

type OnBalanceVolumeRow struct {
	Time  string `column-name:"time"`
	Value string `column-name:"OBV"`
}

type OneDayRateOfChangeTripleSmoothExponentialMovingAverageQuery url.Values

func QueryOneDayRateOfChangeTripleSmoothExponentialMovingAverage(apiKey, symbol, interval, timePeriod, seriesType string) OneDayRateOfChangeTripleSmoothExponentialMovingAverageQuery {
	return OneDayRateOfChangeTripleSmoothExponentialMovingAverageQuery{"function": []string{"TRIX"}, "symbol": []string{symbol}, "interval": []string{interval}, "time_period": []string{timePeriod}, "series_type": []string{seriesType}, "apikey": []string{apiKey}}
}

func (query OneDayRateOfChangeTripleSmoothExponentialMovingAverageQuery) Month(value time.Time) OneDayRateOfChangeTripleSmoothExponentialMovingAverageQuery {
	query["month"] = []string{value.Format("2006-01")}
	return query
}

func (query OneDayRateOfChangeTripleSmoothExponentialMovingAverageQuery) DataTypeCSV() OneDayRateOfChangeTripleSmoothExponentialMovingAverageQuery {
	query["datatype"] = []string{"csv"}
	return query
}

func (query OneDayRateOfChangeTripleSmoothExponentialMovingAverageQuery) DataTypeJSON() OneDayRateOfChangeTripleSmoothExponentialMovingAverageQuery {
	query["datatype"] = []string{"json"}
	return query
}

func (query OneDayRateOfChangeTripleSmoothExponentialMovingAverageQuery) DataType(value string) OneDayRateOfChangeTripleSmoothExponentialMovingAverageQuery {
	query["datatype"] = []string{value}
	return query
}

func (query OneDayRateOfChangeTripleSmoothExponentialMovingAverageQuery) EntitlementRealtime() OneDayRateOfChangeTripleSmoothExponentialMovingAverageQuery {
	query["entitlement"] = []string{"realtime"}
	return query
}

func (query OneDayRateOfChangeTripleSmoothExponentialMovingAverageQuery) EntitlementDelayed() OneDayRateOfChangeTripleSmoothExponentialMovingAverageQuery {
	query["entitlement"] = []string{"delayed"}
	return query
}

func (query OneDayRateOfChangeTripleSmoothExponentialMovingAverageQuery) Entitlement(value string) OneDayRateOfChangeTripleSmoothExponentialMovingAverageQuery {
	query["entitlement"] = []string{value}
	return query
}

func (q OneDayRateOfChangeTripleSmoothExponentialMovingAverageQuery) Encode() string {
	return url.Values(q).Encode()
}

type OneDayRateOfChangeTripleSmoothExponentialMovingAverageRow struct {
	Time  string `column-name:"time"`
	Value string `column-name:"TRIX"`
}
