name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      permissions:
        contents: read
      with:
        go-version-file: go.mod
        check-latest: true

    - name: Build
      permissions:
        contents: read
      run: go build -v ./...

    - name: Test
      permissions:
        contents: read
      run: go test -v ./...
